-- =====================================================================
-- TopicLeap - richer lessons for Grade 3 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Place Value to Thousands
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Place Value to Thousands", "body": "Each digit's value depends on its place: ones, tens, hundreds, thousands. The same digit is worth more the farther left it sits."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the value of the digit 9 in 3694? (Write just the number, e.g. 300)\n\nThe answer is \"90\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the value of the digit 5 in 9651? (Write just the number, e.g. 300)\n\nThe answer is \"50\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the value of the digit 9 in 5295? (Write just the number, e.g. 300)\n\nThe answer is \"90\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the value of the digit 6 in 1086? (Write just the number, e.g. 300)\n\nThe answer is 6."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the value of the digit 7 in 7288? (Write just the number, e.g. 300)\n\nThe answer is 7000."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the value of the digit 6 in 2865? (Write just the number, e.g. 300)\n\nThe answer is 60."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Place Value to Thousands! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$place-value-to-thousands$tl$ and t.grade_level = 3);

-- math: Rounding to 10 and 100
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Rounding to 10 and 100", "body": "To round, look at the digit to the right of the place you're rounding to. 5 or more rounds up; less than 5 rounds down."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Round 37 to the nearest ten.\n\nThe answer is \"40\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Round 999 to the nearest hundred.\n\nThe answer is \"1000\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Round 51 to the nearest ten.\n\nThe answer is \"50\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Round 85 to the nearest ten.\n\nThe answer is 90."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Round 927 to the nearest hundred.\n\nThe answer is 900."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Round 38 to the nearest ten.\n\nThe answer is 40."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Rounding to 10 and 100! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$rounding-to-10-and-100$tl$ and t.grade_level = 3);

-- math: Add & Subtract within 1000
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Add & Subtract within 1000", "body": "Line up numbers by place value and add or subtract one column at a time, regrouping when a column is 10 or more."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add: 469 + 291 = ?\n\nThe answer is \"760\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Subtract: 675 - 182 = ?\n\nThe answer is \"493\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add: 281 + 271 = ?\n\nThe answer is \"552\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Add: 331 + 48 = ?\n\nThe answer is 379."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Subtract: 614 - 287 = ?\n\nThe answer is 327."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Add: 751 + 587 = ?\n\nThe answer is 1338."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Add & Subtract within 1000! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$add-and-subtract-within-1000$tl$ and t.grade_level = 3);

-- math: Multiplication Facts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Multiplication Facts", "body": "Multiplication is fast adding of equal groups. Knowing your facts to 10 x 10 by heart makes bigger math much easier."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Multiply: 4 x 4 = ?\n\nThe answer is \"16\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Multiply: 2 x 3 = ?\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Multiply: 8 x 7 = ?\n\nThe answer is \"56\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Multiply: 6 x 4 = ?\n\nThe answer is 24."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Multiply: 5 x 8 = ?\n\nThe answer is 40."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Multiply: 5 x 2 = ?\n\nThe answer is 10."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Multiplication Facts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$multiplication-facts$tl$ and t.grade_level = 3);

-- math: Division Facts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Division Facts", "body": "Division splits a number into equal groups. It is the opposite of multiplication: if 3 x 4 = 12, then 12 / 4 = 3."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Divide: 49 / 7 = ?\n\nThe answer is \"7\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Divide: 27 / 3 = ?\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Divide: 50 / 5 = ?\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Divide: 48 / 8 = ?\n\nThe answer is 6."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Divide: 10 / 2 = ?\n\nThe answer is 5."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Divide: 42 / 6 = ?\n\nThe answer is 7."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Division Facts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$division-facts$tl$ and t.grade_level = 3);

-- math: Equal Groups
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Equal Groups", "body": "When you have several equal groups, multiply the number of groups by how many are in each group to find the total."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  There are 8 groups with 7 in each group. How many in all?\n\nThe answer is \"56\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  36 things are shared equally into 6 groups. How many in each group?\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  There are 5 groups with 4 in each group. How many in all?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  There are 5 groups with 8 in each group. How many in all?\n\nThe answer is 40."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  24 things are shared equally into 3 groups. How many in each group?\n\nThe answer is 8."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  There are 3 groups with 6 in each group. How many in all?\n\nThe answer is 18."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Equal Groups! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$equal-groups$tl$ and t.grade_level = 3);

-- math: Understanding Fractions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Understanding Fractions", "body": "A fraction names equal parts of a whole. The bottom number tells how many equal parts there are; 1/4 means 1 of 4 equal parts."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The fraction 1/8 means 1 out of how many equal parts?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which fraction is bigger: 1/3 or 1/6?\n\nThe answer is \"1/3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The fraction 1/4 means 1 out of how many equal parts?\n\nThe answer is \"4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is bigger: 1/2 or 1/8?", "choices": [{"id": "a", "label": "1/8"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "Neither"}, {"id": "d", "label": "1/2"}], "answer": "d", "explanation": "Yes! The answer is \"1/2\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is bigger: 1/3 or 1/2?", "choices": [{"id": "a", "label": "1/2"}, {"id": "b", "label": "1/3"}, {"id": "c", "label": "They are equal"}, {"id": "d", "label": "Neither"}], "answer": "a", "explanation": "Yes! The answer is \"1/2\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is bigger: 1/6 or 1/2?", "choices": [{"id": "a", "label": "1/6"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "Neither"}, {"id": "d", "label": "1/2"}], "answer": "d", "explanation": "Yes! The answer is \"1/2\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Understanding Fractions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$unit-fractions$tl$ and t.grade_level = 3);

-- math: Comparing Fractions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Fractions", "body": "When fractions have the same bottom number (denominator), the one with the bigger top number (numerator) is greater."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which fraction is greater: 3/4 or 1/4?\n\nThe answer is \"3/4\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which fraction is greater: 1/8 or 2/8?\n\nThe answer is \"2/8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which fraction is greater: 4/6 or 1/6?\n\nThe answer is \"4/6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is greater: 2/8 or 1/8?", "choices": [{"id": "a", "label": "1/8"}, {"id": "b", "label": "2/8"}, {"id": "c", "label": "They are equal"}, {"id": "d", "label": "3/8"}], "answer": "b", "explanation": "Yes! The answer is \"2/8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is greater: 1/5 or 2/5?", "choices": [{"id": "a", "label": "2/5"}, {"id": "b", "label": "1/5"}, {"id": "c", "label": "They are equal"}, {"id": "d", "label": "3/5"}], "answer": "a", "explanation": "Yes! The answer is \"2/5\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which fraction is greater: 2/4 or 1/4?", "choices": [{"id": "a", "label": "1/4"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "2/4"}, {"id": "d", "label": "3/4"}], "answer": "c", "explanation": "Yes! The answer is \"2/4\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Fractions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$comparing-fractions$tl$ and t.grade_level = 3);

-- math: Area of Rectangles
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Area of Rectangles", "body": "Area is the space inside a shape, measured in square units. For a rectangle, multiply length by width."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A rectangle is 12 units long and 7 units wide. What is its area in square units?\n\nThe answer is \"84\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A rectangle is 11 units long and 3 units wide. What is its area in square units?\n\nThe answer is \"33\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A rectangle is 3 units long and 12 units wide. What is its area in square units?\n\nThe answer is \"36\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A rectangle is 4 units long and 7 units wide. What is its area in square units?\n\nThe answer is 28."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A rectangle is 7 units long and 12 units wide. What is its area in square units?\n\nThe answer is 84."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A rectangle is 3 units long and 6 units wide. What is its area in square units?\n\nThe answer is 18."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Area of Rectangles! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$area-of-rectangles$tl$ and t.grade_level = 3);

-- math: Perimeter of Rectangles
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Perimeter of Rectangles", "body": "Perimeter is the distance all the way around a shape. Add up the lengths of all the sides."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A rectangle is 15 units long and 5 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is \"40\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A rectangle is 3 units long and 13 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is \"32\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A rectangle is 5 units long and 5 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A rectangle is 7 units long and 5 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is 24."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A rectangle is 7 units long and 12 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is 38."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A rectangle is 4 units long and 11 units wide. What is its perimeter (add up all 4 sides)?\n\nThe answer is 30."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Perimeter of Rectangles! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$perimeter-of-rectangles$tl$ and t.grade_level = 3);

-- science: Forces & Motion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Forces & Motion", "body": "A force is a push or a pull. Forces can make things start, stop, speed up, slow down, or change direction."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A push or a pull is called a:\n\nThe answer is \"force\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  To make a still ball start rolling, you must:\n\nThe answer is \"push or pull it\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Kicking a soccer ball is an example of a:\n\nThe answer is \"push\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Opening a drawer toward you is an example of a:", "choices": [{"id": "a", "label": "pull"}, {"id": "b", "label": "push"}, {"id": "c", "label": "spin"}, {"id": "d", "label": "drop"}], "answer": "a", "explanation": "Yes! The answer is \"pull\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The bigger the force on an object, usually the:", "choices": [{"id": "a", "label": "less it moves"}, {"id": "b", "label": "colder it gets"}, {"id": "c", "label": "quieter it gets"}, {"id": "d", "label": "more its motion changes"}], "answer": "d", "explanation": "Yes! The answer is \"more its motion changes\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which makes a wagon speed up more?", "choices": [{"id": "a", "label": "a gentle tap"}, {"id": "b", "label": "no push"}, {"id": "c", "label": "a hard push"}, {"id": "d", "label": "a whisper"}], "answer": "c", "explanation": "Yes! The answer is \"a hard push\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Forces & Motion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$forces-and-motion$tl$ and t.grade_level = 3);

-- science: Balanced & Unbalanced Forces
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Balanced & Unbalanced Forces", "body": "Balanced forces are equal and opposite, so motion stays the same. Unbalanced forces change how something moves."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  When two forces are equal and opposite, they are:\n\nThe answer is \"balanced\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  In a tug-of-war where nobody moves, the forces are:\n\nThe answer is \"balanced\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Balanced forces on a still object make it:\n\nThe answer is \"stay still\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Unbalanced forces cause an object's motion to:", "choices": [{"id": "a", "label": "stay exactly the same"}, {"id": "b", "label": "disappear"}, {"id": "c", "label": "change"}, {"id": "d", "label": "freeze"}], "answer": "c", "explanation": "Yes! The answer is \"change\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A book resting on a table has forces that are:", "choices": [{"id": "a", "label": "unbalanced"}, {"id": "b", "label": "balanced"}, {"id": "c", "label": "spinning"}, {"id": "d", "label": "missing"}], "answer": "b", "explanation": "Yes! The answer is \"balanced\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "If one team in tug-of-war pulls harder, the forces become:", "choices": [{"id": "a", "label": "balanced"}, {"id": "b", "label": "equal"}, {"id": "c", "label": "unbalanced"}, {"id": "d", "label": "silent"}], "answer": "c", "explanation": "Yes! The answer is \"unbalanced\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Balanced & Unbalanced Forces! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$balanced-and-unbalanced-forces$tl$ and t.grade_level = 3);

-- science: Patterns of Motion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Patterns of Motion", "body": "Many motions repeat in patterns, like a swing or a clock. When motion has a pattern, we can predict what comes next."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A swing going back and forth shows a motion that is:\n\nThe answer is \"repeating (a pattern)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Because motion follows patterns, we can:\n\nThe answer is \"predict where it goes next\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A bouncing ball usually bounces:\n\nThe answer is \"a little lower each time\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The hands of a clock move in a pattern that:", "choices": [{"id": "a", "label": "repeats every hour"}, {"id": "b", "label": "never repeats"}, {"id": "c", "label": "is random"}, {"id": "d", "label": "stops at noon"}], "answer": "a", "explanation": "Yes! The answer is \"repeats every hour\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A merry-go-round spins in a motion that is:", "choices": [{"id": "a", "label": "straight only"}, {"id": "b", "label": "round and round (circular)"}, {"id": "c", "label": "zig-zag"}, {"id": "d", "label": "backward only"}], "answer": "b", "explanation": "Yes! The answer is \"round and round (circular)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A pendulum swings in a pattern, so its next swing is:", "choices": [{"id": "a", "label": "impossible to know"}, {"id": "b", "label": "easy to predict"}, {"id": "c", "label": "always different"}, {"id": "d", "label": "invisible"}], "answer": "b", "explanation": "Yes! The answer is \"easy to predict\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Patterns of Motion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$patterns-of-motion$tl$ and t.grade_level = 3);

-- science: Magnets & Forces
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Magnets & Forces", "body": "Magnets pull on iron and can push or pull other magnets without touching. Opposite poles attract; like poles repel."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A magnet can pull objects made of:\n\nThe answer is \"iron\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Magnets can push or pull without:\n\nThe answer is \"touching\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Two north poles brought together will:\n\nThe answer is \"push apart (repel)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A north pole and a south pole will:", "choices": [{"id": "a", "label": "pull together (attract)"}, {"id": "b", "label": "repel"}, {"id": "c", "label": "vanish"}, {"id": "d", "label": "spin"}], "answer": "a", "explanation": "Yes! The answer is \"pull together (attract)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which object would a magnet attract?", "choices": [{"id": "a", "label": "a steel paperclip"}, {"id": "b", "label": "a rubber band"}, {"id": "c", "label": "a paper cup"}, {"id": "d", "label": "a wooden block"}], "answer": "a", "explanation": "Yes! The answer is \"a steel paperclip\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A magnet's force is strongest at its:", "choices": [{"id": "a", "label": "middle"}, {"id": "b", "label": "color"}, {"id": "c", "label": "weight"}, {"id": "d", "label": "poles"}], "answer": "d", "explanation": "Yes! The answer is \"poles\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Magnets & Forces! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$magnets-and-forces$tl$ and t.grade_level = 3);

-- science: Life Cycles
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Life Cycles", "body": "Living things are born, grow, reproduce, and die. Different plants and animals go through different life-cycle stages."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The stages a living thing goes through is called its:\n\nThe answer is \"life cycle\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A butterfly starts its life as an:\n\nThe answer is \"egg\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  After hatching, a butterfly is a:\n\nThe answer is \"caterpillar (larva)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A caterpillar forms a chrysalis and becomes a:", "choices": [{"id": "a", "label": "beetle"}, {"id": "b", "label": "butterfly"}, {"id": "c", "label": "fish"}, {"id": "d", "label": "flower"}], "answer": "b", "explanation": "Yes! The answer is \"butterfly\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A frog begins life as an egg, then becomes a:", "choices": [{"id": "a", "label": "tadpole"}, {"id": "b", "label": "caterpillar"}, {"id": "c", "label": "chick"}, {"id": "d", "label": "puppy"}], "answer": "a", "explanation": "Yes! The answer is \"tadpole\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A plant's life cycle often starts with a:", "choices": [{"id": "a", "label": "seed"}, {"id": "b", "label": "flower first"}, {"id": "c", "label": "fruit first"}, {"id": "d", "label": "leaf first"}], "answer": "a", "explanation": "Yes! The answer is \"seed\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Life Cycles! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$life-cycles$tl$ and t.grade_level = 3);

-- science: Traits & Inheritance
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Traits & Inheritance", "body": "Offspring inherit traits from their parents, which is why young plants and animals resemble the ones they came from."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A feature passed from parents to offspring is a:\n\nThe answer is \"trait\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Puppies often look like their:\n\nThe answer is \"parents\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Eye color in people is mostly a:\n\nThe answer is \"inherited trait\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Offspring inherit traits from:", "choices": [{"id": "a", "label": "the weather"}, {"id": "b", "label": "their friends"}, {"id": "c", "label": "their parents"}, {"id": "d", "label": "the soil"}], "answer": "c", "explanation": "Yes! The answer is \"their parents\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A tall plant often has seeds that grow into plants that are:", "choices": [{"id": "a", "label": "tall too"}, {"id": "b", "label": "always short"}, {"id": "c", "label": "made of metal"}, {"id": "d", "label": "blue"}], "answer": "a", "explanation": "Yes! The answer is \"tall too\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which is an inherited trait of a dog?", "choices": [{"id": "a", "label": "a leash it wears"}, {"id": "b", "label": "its name"}, {"id": "c", "label": "fur color"}, {"id": "d", "label": "its collar"}], "answer": "c", "explanation": "Yes! The answer is \"fur color\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Traits & Inheritance! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$traits-and-inheritance$tl$ and t.grade_level = 3);

-- science: Variation of Traits
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Variation of Traits", "body": "Individuals of the same kind are not all identical. Some differences are inherited and some are shaped by the environment."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Differences in traits among the same kind of animal are called:\n\nThe answer is \"variation\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Some dogs of the same breed have slightly different:\n\nThe answer is \"sizes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Variation means individuals of one kind are:\n\nThe answer is \"not all exactly alike\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Some traits are influenced by the environment, like a plant getting:", "choices": [{"id": "a", "label": "a new name"}, {"id": "b", "label": "a fence"}, {"id": "c", "label": "more sunlight and growing taller"}, {"id": "d", "label": "a sticker"}], "answer": "c", "explanation": "Yes! The answer is \"more sunlight and growing taller\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Two sunflower seeds from the same plant may grow to be:", "choices": [{"id": "a", "label": "different heights"}, {"id": "b", "label": "the same exact height always"}, {"id": "c", "label": "animals"}, {"id": "d", "label": "rocks"}], "answer": "a", "explanation": "Yes! The answer is \"different heights\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A trait that can change with food and care is:", "choices": [{"id": "a", "label": "its species"}, {"id": "b", "label": "an animal's weight"}, {"id": "c", "label": "its number of eyes"}, {"id": "d", "label": "its skeleton count"}], "answer": "b", "explanation": "Yes! The answer is \"an animal's weight\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Variation of Traits! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$variation-of-traits$tl$ and t.grade_level = 3);

-- science: Adaptations & Survival
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adaptations & Survival", "body": "An adaptation is a body part or behavior that helps a living thing survive in its environment."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A body part or behavior that helps an animal survive is an:\n\nThe answer is \"adaptation\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A polar bear's thick fur is an adaptation for:\n\nThe answer is \"staying warm in the cold\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A cactus stores water in its thick stem to survive in the:\n\nThe answer is \"desert\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Camouflage helps an animal:", "choices": [{"id": "a", "label": "glow at night"}, {"id": "b", "label": "fly higher"}, {"id": "c", "label": "hide from predators"}, {"id": "d", "label": "swim faster only"}], "answer": "c", "explanation": "Yes! The answer is \"hide from predators\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A duck's webbed feet are an adaptation for:", "choices": [{"id": "a", "label": "swimming"}, {"id": "b", "label": "climbing trees"}, {"id": "c", "label": "digging"}, {"id": "d", "label": "flying high"}], "answer": "a", "explanation": "Yes! The answer is \"swimming\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Sharp claws help a hawk to:", "choices": [{"id": "a", "label": "stay warm"}, {"id": "b", "label": "see color"}, {"id": "c", "label": "catch prey"}, {"id": "d", "label": "sing"}], "answer": "c", "explanation": "Yes! The answer is \"catch prey\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adaptations & Survival! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$adaptations-and-survival$tl$ and t.grade_level = 3);

-- science: Habitats & Change
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Habitats & Change", "body": "A habitat gives living things food, water, and shelter. When habitats change, living things must move, adapt, or struggle."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The place where a plant or animal naturally lives is its:\n\nThe answer is \"habitat\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A habitat provides an animal with food, water, and:\n\nThe answer is \"shelter\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  If a pond dries up, the fish living there will:\n\nThe answer is \"lose their habitat\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Cutting down a forest can cause animals to:", "choices": [{"id": "a", "label": "gain new planets"}, {"id": "b", "label": "stop needing food"}, {"id": "c", "label": "lose their homes"}, {"id": "d", "label": "turn to stone"}], "answer": "c", "explanation": "Yes! The answer is \"lose their homes\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which animal best fits a desert habitat?", "choices": [{"id": "a", "label": "a polar bear"}, {"id": "b", "label": "a whale"}, {"id": "c", "label": "a penguin"}, {"id": "d", "label": "a lizard"}], "answer": "d", "explanation": "Yes! The answer is \"a lizard\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When the environment changes, some animals:", "choices": [{"id": "a", "label": "move to a new area"}, {"id": "b", "label": "instantly adapt perfectly"}, {"id": "c", "label": "disappear by magic"}, {"id": "d", "label": "grow gills always"}], "answer": "a", "explanation": "Yes! The answer is \"move to a new area\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Habitats & Change! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$habitats-and-environment-change$tl$ and t.grade_level = 3);

-- science: Weather & Climate
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Weather & Climate", "body": "Weather is the day-to-day state of the air. Climate is the usual weather of a place measured over many years."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The day-to-day state of the air (sunny, rainy, windy) is:\n\nThe answer is \"weather\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The usual weather of a place over many years is its:\n\nThe answer is \"climate\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A tool that measures temperature is a:\n\nThe answer is \"thermometer\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Rain, snow, and hail are all kinds of:", "choices": [{"id": "a", "label": "climate"}, {"id": "b", "label": "precipitation"}, {"id": "c", "label": "wind"}, {"id": "d", "label": "sunshine"}], "answer": "b", "explanation": "Yes! The answer is \"precipitation\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A place that is hot and dry most of the year has a:", "choices": [{"id": "a", "label": "polar climate"}, {"id": "b", "label": "desert climate"}, {"id": "c", "label": "rainy climate"}, {"id": "d", "label": "ocean of ice"}], "answer": "b", "explanation": "Yes! The answer is \"desert climate\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Scientists who study and predict weather are:", "choices": [{"id": "a", "label": "dentists"}, {"id": "b", "label": "meteorologists"}, {"id": "c", "label": "pilots"}, {"id": "d", "label": "chefs"}], "answer": "b", "explanation": "Yes! The answer is \"meteorologists\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Weather & Climate! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$weather-and-climate$tl$ and t.grade_level = 3);

-- reading: Finding the Main Idea
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Finding the Main Idea", "body": "The main idea is what a passage is mostly about. Ask yourself the one big thing the author wants you to know."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Sam's dog Biscuit can do tricks. He can sit, roll over, and shake hands.\" What is the main idea?\n\nThe answer is \"Biscuit can do tricks.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Rain helps the Earth. It fills rivers, waters plants, and gives animals water to drink.\" The main idea is that rain:\n\nThe answer is \"helps living things\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Maria cleaned her room. She made her bed, picked up toys, and put away books.\" What is the main idea?\n\nThe answer is \"Maria cleaned her room.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Bees are busy. They fly to flowers, gather nectar, and make honey.\" The passage is mostly about:", "choices": [{"id": "a", "label": "the color of flowers"}, {"id": "b", "label": "how to bake"}, {"id": "c", "label": "rainy days"}, {"id": "d", "label": "what bees do"}], "answer": "d", "explanation": "Yes! The answer is \"what bees do\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Our class went to the farm. We saw cows, fed goats, and picked apples.\" The main idea is that the class:", "choices": [{"id": "a", "label": "ate lunch"}, {"id": "b", "label": "stayed home"}, {"id": "c", "label": "visited a farm"}, {"id": "d", "label": "read a book"}], "answer": "c", "explanation": "Yes! The answer is \"visited a farm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Winter is fun. You can build snowmen, go sledding, and drink hot cocoa.\" The main idea is that winter:", "choices": [{"id": "a", "label": "is short"}, {"id": "b", "label": "is fun"}, {"id": "c", "label": "is warm"}, {"id": "d", "label": "has no snow"}], "answer": "b", "explanation": "Yes! The answer is \"is fun\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Finding the Main Idea! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$main-idea$tl$ and t.grade_level = 3);

-- reading: Key Details
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Key Details", "body": "Key details are the facts in a text that answer who, what, where, when, why, and how."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Lily has a red kite. She flies it in the park on windy days.\" Where does Lily fly her kite?\n\nThe answer is \"in the park\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"The picnic had sandwiches, juice, and grapes.\" Which food was at the picnic?\n\nThe answer is \"grapes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Max woke up early to walk his dog before school.\" When did Max walk his dog?\n\nThe answer is \"before school\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The turtle moved slowly across the warm sand.\" How did the turtle move?", "choices": [{"id": "a", "label": "slowly"}, {"id": "b", "label": "quickly"}, {"id": "c", "label": "backward"}, {"id": "d", "label": "by flying"}], "answer": "a", "explanation": "Yes! The answer is \"slowly\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Ana painted a picture of a blue whale.\" What did Ana paint?", "choices": [{"id": "a", "label": "a red car"}, {"id": "b", "label": "a blue whale"}, {"id": "c", "label": "a green tree"}, {"id": "d", "label": "a yellow sun"}], "answer": "b", "explanation": "Yes! The answer is \"a blue whale\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"It rained all morning, so we played games inside.\" Why did they play inside?", "choices": [{"id": "a", "label": "it was sunny"}, {"id": "b", "label": "it was night"}, {"id": "c", "label": "school was closed"}, {"id": "d", "label": "because it rained"}], "answer": "d", "explanation": "Yes! The answer is \"because it rained\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Key Details! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$key-details$tl$ and t.grade_level = 3);

-- reading: Sequence of Events
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sequence of Events", "body": "Sequence is the order things happen. Words like first, next, then, and last help you keep track."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"First Mia got dressed. Next she ate breakfast. Then she went to school.\" What did Mia do FIRST?\n\nThe answer is \"got dressed\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Jack planted a seed, watered it, and watched it grow.\" What did Jack do LAST?\n\nThe answer is \"watched it grow\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"We packed a bag, drove to the beach, and built a sandcastle.\" What happened SECOND?\n\nThe answer is \"drove to the beach\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The bell rang, the kids lined up, and they walked inside.\" What happened FIRST?", "choices": [{"id": "a", "label": "the bell rang"}, {"id": "b", "label": "kids walked inside"}, {"id": "c", "label": "kids lined up"}, {"id": "d", "label": "class started"}], "answer": "a", "explanation": "Yes! The answer is \"the bell rang\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Dad mixed the batter, poured it in a pan, and baked a cake.\" What did Dad do right after mixing?", "choices": [{"id": "a", "label": "poured it in a pan"}, {"id": "b", "label": "baked the cake"}, {"id": "c", "label": "ate the cake"}, {"id": "d", "label": "washed dishes"}], "answer": "a", "explanation": "Yes! The answer is \"poured it in a pan\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She tied her shoes, grabbed her ball, and ran outside.\" What did she do LAST?", "choices": [{"id": "a", "label": "tied her shoes"}, {"id": "b", "label": "ran outside"}, {"id": "c", "label": "grabbed her ball"}, {"id": "d", "label": "sat down"}], "answer": "b", "explanation": "Yes! The answer is \"ran outside\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sequence of Events! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$story-sequence$tl$ and t.grade_level = 3);

-- reading: Cause & Effect
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Cause & Effect", "body": "A cause is why something happens; the effect is what happens. Words like because and so connect them."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"It started to rain, so we ran inside.\" Why did they run inside?\n\nThe answer is \"because it rained\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Ed forgot his umbrella, so he got wet.\" What was the effect?\n\nThe answer is \"he got wet\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The plant got sunlight and water, so it grew.\" Why did the plant grow?\n\nThe answer is \"it got sunlight and water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She practiced every day, so she got better at piano.\" What caused her to improve?", "choices": [{"id": "a", "label": "she quit"}, {"id": "b", "label": "she practiced every day"}, {"id": "c", "label": "she slept"}, {"id": "d", "label": "it was easy"}], "answer": "b", "explanation": "Yes! The answer is \"she practiced every day\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The ice cream melted because it was hot outside.\" Why did it melt?", "choices": [{"id": "a", "label": "it was frozen"}, {"id": "b", "label": "it was hot outside"}, {"id": "c", "label": "it was night"}, {"id": "d", "label": "it was tiny"}], "answer": "b", "explanation": "Yes! The answer is \"it was hot outside\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"He dropped the cup, so it broke.\" What was the effect of dropping the cup?", "choices": [{"id": "a", "label": "it floated"}, {"id": "b", "label": "it broke"}, {"id": "c", "label": "it grew"}, {"id": "d", "label": "nothing happened"}], "answer": "b", "explanation": "Yes! The answer is \"it broke\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Cause & Effect! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$cause-and-effect$tl$ and t.grade_level = 3);

-- reading: Vocabulary in Context
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Vocabulary in Context", "body": "Use the words around an unknown word as clues to figure out what it means."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The tiny ant was so small I could barely see it.\" What does \"tiny\" mean?\n\nThe answer is \"very small\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"She was joyful and smiled all day.\" What does \"joyful\" mean?\n\nThe answer is \"very happy\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The soup was hot, so he let it cool down.\" What does \"hot\" mean here?\n\nThe answer is \"very warm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The path was narrow, so only one person could pass.\" What does \"narrow\" mean?", "choices": [{"id": "a", "label": "very tall"}, {"id": "b", "label": "bright"}, {"id": "c", "label": "heavy"}, {"id": "d", "label": "not wide"}], "answer": "d", "explanation": "Yes! The answer is \"not wide\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"He was exhausted after running and fell asleep fast.\" What does \"exhausted\" mean?", "choices": [{"id": "a", "label": "excited"}, {"id": "b", "label": "hungry"}, {"id": "c", "label": "very tired"}, {"id": "d", "label": "cold"}], "answer": "c", "explanation": "Yes! The answer is \"very tired\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The huge elephant was the biggest animal there.\" What does \"huge\" mean?", "choices": [{"id": "a", "label": "very big"}, {"id": "b", "label": "very small"}, {"id": "c", "label": "very quiet"}, {"id": "d", "label": "very fast"}], "answer": "a", "explanation": "Yes! The answer is \"very big\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Vocabulary in Context! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$context-clues$tl$ and t.grade_level = 3);

-- reading: Making Predictions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Making Predictions", "body": "A prediction is a smart guess about what will happen next, based on clues in the text."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Dark clouds gathered and the wind grew strong.\" What will probably happen next?\n\nThe answer is \"It will rain.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Tom put on his swimsuit and grabbed a towel.\" What will Tom probably do?\n\nThe answer is \"go swimming\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The cake is in the oven and the timer is almost done.\" What will happen soon?\n\nThe answer is \"The cake will be ready.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Mia yawned and rubbed her eyes at bedtime.\" What will Mia probably do?", "choices": [{"id": "a", "label": "fall asleep"}, {"id": "b", "label": "run a race"}, {"id": "c", "label": "eat lunch"}, {"id": "d", "label": "go to school"}], "answer": "a", "explanation": "Yes! The answer is \"fall asleep\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"He filled the watering can and walked to the garden.\" What will he probably do?", "choices": [{"id": "a", "label": "wash the car"}, {"id": "b", "label": "cook dinner"}, {"id": "c", "label": "fly a kite"}, {"id": "d", "label": "water the plants"}], "answer": "d", "explanation": "Yes! The answer is \"water the plants\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The team is winning with one minute left.\" What will probably happen?", "choices": [{"id": "a", "label": "The game starts over."}, {"id": "b", "label": "Everyone goes home first."}, {"id": "c", "label": "They lose for sure."}, {"id": "d", "label": "The team will likely win."}], "answer": "d", "explanation": "Yes! The answer is \"The team will likely win.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Making Predictions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$making-predictions$tl$ and t.grade_level = 3);

-- reading: Characters & Setting
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Characters & Setting", "body": "Characters are who a story is about. The setting is where and when the story happens."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"In the busy city, Ravi waited for the train.\" Where does this happen (setting)?\n\nThe answer is \"in the city\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Kind Mrs. Lee helped the lost kitten find its way home.\" Who is the character?\n\nThe answer is \"Mrs. Lee\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"It was a snowy night in the quiet village.\" What is the setting?\n\nThe answer is \"a snowy village at night\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Brave Captain Mara sailed her ship through the storm.\" Who is the main character?", "choices": [{"id": "a", "label": "Captain Mara"}, {"id": "b", "label": "the storm"}, {"id": "c", "label": "the ship's flag"}, {"id": "d", "label": "the ocean"}], "answer": "a", "explanation": "Yes! The answer is \"Captain Mara\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"At the farm, the rooster crowed at sunrise.\" Where does the story take place?", "choices": [{"id": "a", "label": "in a city"}, {"id": "b", "label": "on the Moon"}, {"id": "c", "label": "on a farm"}, {"id": "d", "label": "in a cave"}], "answer": "c", "explanation": "Yes! The answer is \"on a farm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Curious Leo loved to ask questions about everything.\" What word describes Leo?", "choices": [{"id": "a", "label": "lazy"}, {"id": "b", "label": "curious"}, {"id": "c", "label": "mean"}, {"id": "d", "label": "sleepy"}], "answer": "b", "explanation": "Yes! The answer is \"curious\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Characters & Setting! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$character-and-setting$tl$ and t.grade_level = 3);

-- reading: Fact vs. Opinion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Fact vs. Opinion", "body": "A fact can be proven true. An opinion tells what someone feels and can't be proven. Words like best signal opinions."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which is a FACT?\n\nThe answer is \"A dog has four legs.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which is an OPINION?\n\nThe answer is \"Summer is the best season.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is a FACT?\n\nThe answer is \"The sun gives us light.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which is an OPINION?", "choices": [{"id": "a", "label": "Pizza has cheese."}, {"id": "b", "label": "A triangle has 3 sides."}, {"id": "c", "label": "Birds lay eggs."}, {"id": "d", "label": "Pizza tastes amazing."}], "answer": "d", "explanation": "Yes! The answer is \"Pizza tastes amazing.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"Our school has 200 students.\" This is a:", "choices": [{"id": "a", "label": "opinion"}, {"id": "b", "label": "question"}, {"id": "c", "label": "fact"}, {"id": "d", "label": "story"}], "answer": "c", "explanation": "Yes! The answer is \"fact\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"Reading is more fun than TV.\" This is an:", "choices": [{"id": "a", "label": "opinion"}, {"id": "b", "label": "fact"}, {"id": "c", "label": "rule"}, {"id": "d", "label": "number"}], "answer": "a", "explanation": "Yes! The answer is \"opinion\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Fact vs. Opinion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$fact-and-opinion$tl$ and t.grade_level = 3);

-- reading: Compare & Contrast
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Compare & Contrast", "body": "Comparing shows how things are alike; contrasting shows how they differ. 'Both' signals alike; 'but' and 'unlike' signal different."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"A cat and a dog are both pets, but a cat purrs and a dog barks.\" How are they ALIKE?\n\nThe answer is \"both are pets\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Apples are crunchy, but bananas are soft.\" This shows a:\n\nThe answer is \"difference\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Both a bike and a car have wheels.\" The word that signals they are alike is:\n\nThe answer is \"both\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Summer is hot, but winter is cold.\" This compares the seasons by:", "choices": [{"id": "a", "label": "color"}, {"id": "b", "label": "size"}, {"id": "c", "label": "name"}, {"id": "d", "label": "temperature"}], "answer": "d", "explanation": "Yes! The answer is \"temperature\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Unlike a fish, a frog can live on land.\" The word \"unlike\" signals a:", "choices": [{"id": "a", "label": "similarity"}, {"id": "b", "label": "sequence"}, {"id": "c", "label": "difference"}, {"id": "d", "label": "cause"}], "answer": "c", "explanation": "Yes! The answer is \"difference\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"A pencil and a crayon are both used to draw, but a pencil can be erased.\" How are they DIFFERENT?", "choices": [{"id": "a", "label": "both draw"}, {"id": "b", "label": "both are tools"}, {"id": "c", "label": "a pencil can be erased"}, {"id": "d", "label": "both are long"}], "answer": "c", "explanation": "Yes! The answer is \"a pencil can be erased\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Compare & Contrast! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-and-contrast$tl$ and t.grade_level = 3);

-- reading: Synonyms & Antonyms
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Synonyms & Antonyms", "body": "Synonyms are words that mean almost the same thing. Antonyms mean the opposite."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word means almost the same as \"happy\"?\n\nThe answer is \"glad\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is the OPPOSITE of \"big\"?\n\nThe answer is \"small\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A synonym for \"fast\" is:\n\nThe answer is \"quick\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The opposite of \"hot\" is:", "choices": [{"id": "a", "label": "cold"}, {"id": "b", "label": "warm"}, {"id": "c", "label": "boiling"}, {"id": "d", "label": "sunny"}], "answer": "a", "explanation": "Yes! The answer is \"cold\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A synonym for \"happy\" is:", "choices": [{"id": "a", "label": "grumpy"}, {"id": "b", "label": "upset"}, {"id": "c", "label": "mad"}, {"id": "d", "label": "cheerful"}], "answer": "d", "explanation": "Yes! The answer is \"cheerful\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The opposite of \"up\" is:", "choices": [{"id": "a", "label": "high"}, {"id": "b", "label": "above"}, {"id": "c", "label": "top"}, {"id": "d", "label": "down"}], "answer": "d", "explanation": "Yes! The answer is \"down\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Synonyms & Antonyms! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$synonyms-and-antonyms$tl$ and t.grade_level = 3);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea. Common nouns are general; proper nouns name a specific one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"kitchen\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"sister\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"mountain\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "river"}, {"id": "b", "label": "whisper"}, {"id": "c", "label": "march"}, {"id": "d", "label": "paint"}], "answer": "a", "explanation": "Yes! The answer is \"river\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "bounce"}, {"id": "b", "label": "puppy"}, {"id": "c", "label": "brave"}, {"id": "d", "label": "march"}], "answer": "b", "explanation": "Yes! The answer is \"puppy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "forest"}, {"id": "b", "label": "scribble"}, {"id": "c", "label": "shiny"}, {"id": "d", "label": "cheerful"}], "answer": "a", "explanation": "Yes! The answer is \"forest\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 3);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action. Action verbs tell what the subject does, like run, jump, or think."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"explore\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"wander\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"shout\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "stormy"}, {"id": "b", "label": "build"}, {"id": "c", "label": "sister"}, {"id": "d", "label": "slippery"}], "answer": "b", "explanation": "Yes! The answer is \"build\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "enormous"}, {"id": "b", "label": "jump"}, {"id": "c", "label": "brave"}, {"id": "d", "label": "blanket"}], "answer": "b", "explanation": "Yes! The answer is \"jump\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "enormous"}, {"id": "b", "label": "curious"}, {"id": "c", "label": "bounce"}, {"id": "d", "label": "garden"}], "answer": "c", "explanation": "Yes! The answer is \"bounce\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 3);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun, telling what kind, how many, or which one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"stormy\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"gentle\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"slippery\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "sister"}, {"id": "b", "label": "tiny"}, {"id": "c", "label": "doctor"}, {"id": "d", "label": "island"}], "answer": "b", "explanation": "Yes! The answer is \"tiny\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "ancient"}, {"id": "b", "label": "sister"}, {"id": "c", "label": "build"}, {"id": "d", "label": "puppy"}], "answer": "a", "explanation": "Yes! The answer is \"ancient\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "jump"}, {"id": "b", "label": "forest"}, {"id": "c", "label": "golden"}, {"id": "d", "label": "library"}], "answer": "c", "explanation": "Yes! The answer is \"golden\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 3);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun, like he, she, it, we, or they."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"us\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"you\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"them\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "it"}, {"id": "b", "label": "gallop"}, {"id": "c", "label": "swim"}, {"id": "d", "label": "library"}], "answer": "a", "explanation": "Yes! The answer is \"it\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "stretch"}, {"id": "b", "label": "whisper"}, {"id": "c", "label": "discover"}, {"id": "d", "label": "they"}], "answer": "d", "explanation": "Yes! The answer is \"they\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "window"}, {"id": "b", "label": "kitchen"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "she"}], "answer": "d", "explanation": "Yes! The answer is \"she\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 3);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must match the subject. A singular subject usually takes a verb ending in -s."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The puppy ____ every day.\"\n\nThe answer is \"wags\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The student ____ every day.\"\n\nThe answer is \"reads\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The dog ____ every day.\"\n\nThe answer is \"barks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The singer ____ every day.\"", "choices": [{"id": "a", "label": "performs"}, {"id": "b", "label": "perform"}, {"id": "c", "label": "performsed"}, {"id": "d", "label": "performsing"}], "answer": "a", "explanation": "Yes! The answer is \"performs\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The flower ____ every day.\"", "choices": [{"id": "a", "label": "grow"}, {"id": "b", "label": "growsed"}, {"id": "c", "label": "growsing"}, {"id": "d", "label": "grows"}], "answer": "d", "explanation": "Yes! The answer is \"grows\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The bird ____ every day.\"", "choices": [{"id": "a", "label": "sings"}, {"id": "b", "label": "sing"}, {"id": "c", "label": "singsed"}, {"id": "d", "label": "singsing"}], "answer": "a", "explanation": "Yes! The answer is \"sings\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 3);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs tell about something that already happened. Many add -ed; some are irregular."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"catch\"?\n\nThe answer is \"caught\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"think\"?\n\nThe answer is \"thought\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"see\"?\n\nThe answer is \"saw\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"draw\"?\n\nThe answer is drew."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"begin\"?\n\nThe answer is began."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"know\"?\n\nThe answer is knew."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 3);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals mean more than one. Add -s or -es, or change y to -ies after a consonant."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"city\".\n\nThe answer is \"cities\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"wolf\".\n\nThe answer is \"wolves\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"match\".\n\nThe answer is \"matches\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"berry\".\n\nThe answer is berries."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"baby\".\n\nThe answer is babies."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"branch\".\n\nThe answer is branches."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 3);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize the first word of a sentence, the word I, and proper nouns like names, places, days, and months."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Tokyo\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"New York\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Australia\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "Tuesday"}, {"id": "b", "label": "country"}, {"id": "c", "label": "ocean"}, {"id": "d", "label": "day"}], "answer": "a", "explanation": "Yes! The answer is \"Tuesday\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "ocean"}, {"id": "b", "label": "country"}, {"id": "c", "label": "day"}, {"id": "d", "label": "Mount Everest"}], "answer": "d", "explanation": "Yes! The answer is \"Mount Everest\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "friend"}, {"id": "b", "label": "ocean"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "Sarah"}], "answer": "d", "explanation": "Yes! The answer is \"Sarah\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization-proper-nouns$tl$ and t.grade_level = 3);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End a telling sentence with a period, a question with a question mark, and an excited sentence with an exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"Can you help me___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"When does it start___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"Where are we going___\"\n\nThe answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"What time is it___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "."}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"We had lunch___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Stop right now___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "c", "explanation": "Yes! The answer is \"!\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 3);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "When you list three or more things, separate them with commas and put 'and' before the last item."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like trains, planes, and buses.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like apples, oranges, and pears.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like run, jump, and swim.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like lions, tigers, and bears."}, {"id": "b", "label": "I like lions tigers and bears."}, {"id": "c", "label": "I like lions, tigers and bears"}, {"id": "d", "label": "I like, lions tigers bears."}], "answer": "a", "explanation": "Yes! The answer is \"I like lions, tigers, and bears.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like apples, grapes, and plums."}, {"id": "b", "label": "I like apples grapes and plums."}, {"id": "c", "label": "I like apples, grapes and plums"}, {"id": "d", "label": "I like, apples grapes plums."}], "answer": "a", "explanation": "Yes! The answer is \"I like apples, grapes, and plums.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like walk, skip, and hop."}, {"id": "b", "label": "I like walk skip and hop."}, {"id": "c", "label": "I like walk, skip and hop"}, {"id": "d", "label": "I like, walk skip hop."}], "answer": "a", "explanation": "Yes! The answer is \"I like walk, skip, and hop.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 3);

