-- =====================================================================
-- TopicLeap - richer lessons for Grade 8 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Exponent Rules
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Exponent Rules", "body": "Use the laws of exponents to multiply, divide, and raise powers to powers."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Simplify and evaluate:  2^1 x 2^1 = ?\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Simplify and evaluate:  3^3 / 3^2 = ?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Simplify and evaluate:  (2^2)^3 = ?\n\nThe answer is \"64\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Simplify and evaluate:  3^4 / 3^3 = ?\n\nThe answer is 3."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Simplify and evaluate:  (4^3)^2 = ?\n\nThe answer is 4096."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Simplify and evaluate:  2^5 / 2^4 = ?\n\nThe answer is 2."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Exponent Rules! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$exponent-rules$tl$ and t.grade_level = 8);

-- math: Scientific Notation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Scientific Notation", "body": "Scientific notation writes very large or small numbers as a number times a power of ten."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write 3.2 x 10^2 as a standard number (no commas).\n\nThe answer is \"320\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write 7.2 x 10^2 as a standard number (no commas).\n\nThe answer is \"720\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write 5.2 x 10^2 as a standard number (no commas).\n\nThe answer is \"520\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write 9.7 x 10^3 as a standard number (no commas).\n\nThe answer is 9700."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write 2.7 x 10^3 as a standard number (no commas).\n\nThe answer is 2700."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write 3.6 x 10^3 as a standard number (no commas).\n\nThe answer is 3600."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Scientific Notation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$scientific-notation$tl$ and t.grade_level = 8);

-- math: Square & Cube Roots
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Square & Cube Roots", "body": "A square root undoes squaring; a cube root undoes cubing."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the square root of 25?\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the square root of 9?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the square root of 64?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the square root of 324?\n\nThe answer is 18."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the square root of 144?\n\nThe answer is 12."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the square root of 256?\n\nThe answer is 16."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Square & Cube Roots! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$roots$tl$ and t.grade_level = 8);

-- math: Linear Equations
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Linear Equations", "body": "Solve equations with variables on both sides by collecting like terms."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Solve for x:  3x + 1 = 1x + 13\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Solve for x:  4x + 3 = 3x + 10\n\nThe answer is \"7\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Solve for x:  4x + 7 = 3x + 9\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Solve for x:  4x + 5 = 2x + 17\n\nThe answer is 6."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Solve for x:  7x + 10 = 1x + 52\n\nThe answer is 7."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Solve for x:  3x + 12 = 2x + 18\n\nThe answer is 6."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Linear Equations! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$linear-equations$tl$ and t.grade_level = 8);

-- math: Slope
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Slope", "body": "Slope is the rate of change: the rise (change in y) divided by the run (change in x)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Find the slope of the line through (3, 2) and (6, 11).\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Find the slope of the line through (4, 6) and (5, 9).\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Find the slope of the line through (3, 4) and (7, 20).\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Find the slope of the line through (5, 6) and (9, 26).\n\nThe answer is 5."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Find the slope of the line through (5, 2) and (9, 14).\n\nThe answer is 3."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Find the slope of the line through (4, 3) and (9, 28).\n\nThe answer is 5."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Slope! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$slope$tl$ and t.grade_level = 8);

-- math: Pythagorean Theorem
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pythagorean Theorem", "body": "In a right triangle, a^2 + b^2 = c^2, where c is the hypotenuse."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A right triangle has legs of 6 and 8. What is the length of the hypotenuse?\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A right triangle has legs of 8 and 15. What is the length of the hypotenuse?\n\nThe answer is \"17\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A right triangle has legs of 3 and 4. What is the length of the hypotenuse?\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A right triangle has a hypotenuse of 25 and one leg of 7. What is the other leg?\n\nThe answer is 24."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A right triangle has a hypotenuse of 10 and one leg of 6. What is the other leg?\n\nThe answer is 8."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A right triangle has a hypotenuse of 15 and one leg of 9. What is the other leg?\n\nThe answer is 12."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pythagorean Theorem! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$pythagorean-theorem$tl$ and t.grade_level = 8);

-- math: Functions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Functions", "body": "A function pairs each input with exactly one output. Evaluate f(x) by substituting."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  If f(x) = 5x + 2, what is f(3)?\n\nThe answer is \"17\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  If f(x) = 5x + 6, what is f(6)?\n\nThe answer is \"36\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  If f(x) = 5x + 7, what is f(3)?\n\nThe answer is \"22\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  If f(x) = 3x + 5, what is f(8)?\n\nThe answer is 29."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  If f(x) = 4x + 1, what is f(6)?\n\nThe answer is 25."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  If f(x) = 3x + 2, what is f(8)?\n\nThe answer is 26."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Functions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$functions$tl$ and t.grade_level = 8);

-- math: Volume of Cylinders & Cones
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Volume of Cylinders & Cones", "body": "Cylinder volume = pi x r x r x h; a cone is one-third of that. Use 3.14 for pi."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Find the volume of a cylinder with radius 3 and height 3. Use 3.14 for pi. (V = pi x r x r x h)\n\nThe answer is \"84.78\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Find the volume of a cylinder with radius 3 and height 7. Use 3.14 for pi. (V = pi x r x r x h)\n\nThe answer is \"197.82\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Find the volume of a cylinder with radius 4 and height 6. Use 3.14 for pi. (V = pi x r x r x h)\n\nThe answer is \"301.44\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the volume of a cylinder with radius 3 and height 4. Use 3.14 for pi. (V = pi x r x r x h)", "choices": [{"id": "a", "label": "226.08"}, {"id": "b", "label": "37.68"}, {"id": "c", "label": "113.04"}, {"id": "d", "label": "75.36"}], "answer": "c", "explanation": "Yes! The answer is \"113.04\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the volume of a cylinder with radius 2 and height 6. Use 3.14 for pi. (V = pi x r x r x h)", "choices": [{"id": "a", "label": "24"}, {"id": "b", "label": "75.36"}, {"id": "c", "label": "37.68"}, {"id": "d", "label": "150.72"}], "answer": "b", "explanation": "Yes! The answer is \"75.36\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the volume of a cone with radius 5 and height 6. Use 3.14 for pi. (V = (1/3) x pi x r x r x h)", "choices": [{"id": "a", "label": "157"}, {"id": "b", "label": "150"}, {"id": "c", "label": "471"}, {"id": "d", "label": "78.5"}], "answer": "a", "explanation": "Yes! The answer is \"157\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Volume of Cylinders & Cones! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$volume-cylinders-cones$tl$ and t.grade_level = 8);

-- math: Rational & Irrational Numbers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Rational & Irrational Numbers", "body": "Rational numbers can be written as fractions; irrational numbers (like pi) cannot."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Is the number 5 rational or irrational?\n\nThe answer is \"rational\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Is the decimal 0.1010010001... (never repeats) rational or irrational?\n\nThe answer is \"irrational\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Is the square root of 5 rational or irrational?\n\nThe answer is \"irrational\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the fraction 2/7 rational or irrational?", "choices": [{"id": "a", "label": "irrational"}, {"id": "b", "label": "both"}, {"id": "c", "label": "rational"}, {"id": "d", "label": "neither"}], "answer": "c", "explanation": "Yes! The answer is \"rational\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the square root of 20 rational or irrational?", "choices": [{"id": "a", "label": "rational"}, {"id": "b", "label": "both"}, {"id": "c", "label": "neither"}, {"id": "d", "label": "irrational"}], "answer": "d", "explanation": "Yes! The answer is \"irrational\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the number pi rational or irrational?", "choices": [{"id": "a", "label": "rational"}, {"id": "b", "label": "irrational"}, {"id": "c", "label": "both"}, {"id": "d", "label": "neither"}], "answer": "b", "explanation": "Yes! The answer is \"irrational\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Rational & Irrational Numbers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$rational-irrational$tl$ and t.grade_level = 8);

-- math: Slope-Intercept Form
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Slope-Intercept Form", "body": "In y = mx + b, m is the slope and b is the y-intercept."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  For the line y = 3x + 5, what is the slope?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  For the line y = 5x + 1, what is the y-intercept?\n\nThe answer is \"1\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  For the line y = 5x + 3, what is the slope?\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  For the line y = 7x + 4, what is the slope?\n\nThe answer is 7."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  For the line y = 6x + 3, what is the y-intercept?\n\nThe answer is 3."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  For the line y = 3x + 1, what is the y-intercept?\n\nThe answer is 1."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Slope-Intercept Form! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$slope-intercept$tl$ and t.grade_level = 8);

-- science: Forces & Motion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Forces & Motion", "body": "Newton's laws and graphs describe how forces change an object's motion."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Newton's second law is written as the equation:\n\nThe answer is \"F = ma\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  If the net force on an object is zero, its velocity is:\n\nThe answer is \"constant (unchanging)\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A 2 kg object accelerating at 3 m/s^2 experiences a net force of:\n\nThe answer is \"6 N\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Acceleration is the rate of change of:", "choices": [{"id": "a", "label": "velocity"}, {"id": "b", "label": "mass"}, {"id": "c", "label": "force"}, {"id": "d", "label": "distance"}], "answer": "a", "explanation": "Yes! The answer is \"velocity\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "On a distance-time graph, a steeper line means a:", "choices": [{"id": "a", "label": "slower speed"}, {"id": "b", "label": "object at rest"}, {"id": "c", "label": "negative mass"}, {"id": "d", "label": "greater speed"}], "answer": "d", "explanation": "Yes! The answer is \"greater speed\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A flat (horizontal) line on a distance-time graph means the object is:", "choices": [{"id": "a", "label": "speeding up"}, {"id": "b", "label": "at rest"}, {"id": "c", "label": "slowing down"}, {"id": "d", "label": "moving fastest"}], "answer": "b", "explanation": "Yes! The answer is \"at rest\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Forces & Motion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$forces-and-motion$tl$ and t.grade_level = 8);

-- science: Energy & Its Conservation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Energy & Its Conservation", "body": "Energy changes form and is conserved; work transfers energy to objects."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Kinetic energy depends on an object's mass and its:\n\nThe answer is \"speed (velocity)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Gravitational potential energy depends on mass, gravity, and:\n\nThe answer is \"height\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The law of conservation of energy says energy is:\n\nThe answer is \"never created or destroyed\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "As a roller coaster descends, potential energy transforms into:", "choices": [{"id": "a", "label": "chemical energy"}, {"id": "b", "label": "mass"}, {"id": "c", "label": "kinetic energy"}, {"id": "d", "label": "sound only"}], "answer": "c", "explanation": "Yes! The answer is \"kinetic energy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Doing work on an object transfers ____ to it.", "choices": [{"id": "a", "label": "mass"}, {"id": "b", "label": "color"}, {"id": "c", "label": "charge"}, {"id": "d", "label": "energy"}], "answer": "d", "explanation": "Yes! The answer is \"energy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The SI unit of energy and work is the:", "choices": [{"id": "a", "label": "newton"}, {"id": "b", "label": "watt"}, {"id": "c", "label": "joule"}, {"id": "d", "label": "meter"}], "answer": "c", "explanation": "Yes! The answer is \"joule\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Energy & Its Conservation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$energy-transfer$tl$ and t.grade_level = 8);

-- science: Waves & Information
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Waves & Information", "body": "Waves carry energy and information; light and sound have measurable properties."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Waves transfer ____ without permanently transferring matter.\n\nThe answer is \"energy\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The number of wave cycles per second is the:\n\nThe answer is \"frequency\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Wave speed equals frequency times:\n\nThe answer is \"wavelength\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Sound is a ____ wave that needs a medium.", "choices": [{"id": "a", "label": "longitudinal (mechanical)"}, {"id": "b", "label": "transverse only"}, {"id": "c", "label": "electromagnetic"}, {"id": "d", "label": "light"}], "answer": "a", "explanation": "Yes! The answer is \"longitudinal (mechanical)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Light is an ____ wave that can travel through a vacuum.", "choices": [{"id": "a", "label": "mechanical"}, {"id": "b", "label": "sound"}, {"id": "c", "label": "electromagnetic"}, {"id": "d", "label": "water"}], "answer": "c", "explanation": "Yes! The answer is \"electromagnetic\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Higher frequency light corresponds to:", "choices": [{"id": "a", "label": "lower energy"}, {"id": "b", "label": "no energy"}, {"id": "c", "label": "slower speed"}, {"id": "d", "label": "higher energy"}], "answer": "d", "explanation": "Yes! The answer is \"higher energy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Waves & Information! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$waves$tl$ and t.grade_level = 8);

-- science: Chemical Reactions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Chemical Reactions", "body": "Reactions rearrange atoms and conserve mass; bonds form by sharing or transferring electrons."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  In a chemical reaction, atoms are:\n\nThe answer is \"rearranged, not created or destroyed\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A balanced equation has equal numbers of each atom on:\n\nThe answer is \"both sides\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The principle that mass is the same before and after a reaction is:\n\nThe answer is \"conservation of mass\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Evidence of a chemical reaction can include a color change, gas, or:", "choices": [{"id": "a", "label": "a change in shape only"}, {"id": "b", "label": "melting only"}, {"id": "c", "label": "dissolving only"}, {"id": "d", "label": "temperature change"}], "answer": "d", "explanation": "Yes! The answer is \"temperature change\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A reaction that releases energy (heat) is:", "choices": [{"id": "a", "label": "endothermic"}, {"id": "b", "label": "physical"}, {"id": "c", "label": "neutral"}, {"id": "d", "label": "exothermic"}], "answer": "d", "explanation": "Yes! The answer is \"exothermic\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A reaction that absorbs energy is:", "choices": [{"id": "a", "label": "exothermic"}, {"id": "b", "label": "physical"}, {"id": "c", "label": "endothermic"}, {"id": "d", "label": "instant"}], "answer": "c", "explanation": "Yes! The answer is \"endothermic\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Chemical Reactions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$chemical-reactions$tl$ and t.grade_level = 8);

-- science: Atoms & the Periodic Table
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Atoms & the Periodic Table", "body": "Atomic structure and the periodic table explain elements' properties and reactivity."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The number of protons in an atom defines its:\n\nThe answer is \"element (atomic number)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Atoms of the same element with different neutron counts are:\n\nThe answer is \"isotopes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An atom that has lost or gained electrons is an:\n\nThe answer is \"ion\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Vertical columns of the periodic table are:", "choices": [{"id": "a", "label": "periods"}, {"id": "b", "label": "rows only"}, {"id": "c", "label": "groups (families)"}, {"id": "d", "label": "cells"}], "answer": "c", "explanation": "Yes! The answer is \"groups (families)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Elements in the same group tend to have similar:", "choices": [{"id": "a", "label": "masses exactly"}, {"id": "b", "label": "colors"}, {"id": "c", "label": "prices"}, {"id": "d", "label": "chemical properties"}], "answer": "d", "explanation": "Yes! The answer is \"chemical properties\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Across a period, atomic number ____ from left to right.", "choices": [{"id": "a", "label": "decreases"}, {"id": "b", "label": "increases"}, {"id": "c", "label": "stays the same"}, {"id": "d", "label": "is random"}], "answer": "b", "explanation": "Yes! The answer is \"increases\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Atoms & the Periodic Table! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$atoms-and-periodic-table$tl$ and t.grade_level = 8);

-- science: Evolution & Natural Selection
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Evolution & Natural Selection", "body": "Natural selection, supported by fossil, anatomical, and DNA evidence, shapes species over time."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Heritable traits that improve survival and reproduction tend to become:\n\nThe answer is \"more common over generations\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The raw material for new variation in populations comes from:\n\nThe answer is \"mutations\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An organism's reproductive success is a measure of its:\n\nThe answer is \"fitness\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Natural selection requires variation, heredity, and differences in:", "choices": [{"id": "a", "label": "survival and reproduction"}, {"id": "b", "label": "color only"}, {"id": "c", "label": "names"}, {"id": "d", "label": "habitats only"}], "answer": "a", "explanation": "Yes! The answer is \"survival and reproduction\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Fossils, anatomy, and DNA all provide ____ for evolution.", "choices": [{"id": "a", "label": "disproof"}, {"id": "b", "label": "evidence"}, {"id": "c", "label": "randomness"}, {"id": "d", "label": "opinions"}], "answer": "b", "explanation": "Yes! The answer is \"evidence\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Over very long times, accumulated changes can produce new:", "choices": [{"id": "a", "label": "planets"}, {"id": "b", "label": "minerals"}, {"id": "c", "label": "seasons"}, {"id": "d", "label": "species"}], "answer": "d", "explanation": "Yes! The answer is \"species\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Evolution & Natural Selection! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$natural-selection$tl$ and t.grade_level = 8);

-- science: Genetics & Heredity
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Genetics & Heredity", "body": "Genes made of DNA pass traits to offspring; mutations create variation."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Genes are segments of:\n\nThe answer is \"DNA\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Different versions of the same gene are called:\n\nThe answer is \"alleles\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An organism's genetic makeup is its:\n\nThe answer is \"genotype\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An organism's observable traits make up its:", "choices": [{"id": "a", "label": "genotype"}, {"id": "b", "label": "phenotype"}, {"id": "c", "label": "allele"}, {"id": "d", "label": "gene"}], "answer": "b", "explanation": "Yes! The answer is \"phenotype\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A capital letter usually represents a ____ allele.", "choices": [{"id": "a", "label": "recessive"}, {"id": "b", "label": "mutated"}, {"id": "c", "label": "dominant"}, {"id": "d", "label": "missing"}], "answer": "c", "explanation": "Yes! The answer is \"dominant\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A trait expressed only when two recessive alleles are present is:", "choices": [{"id": "a", "label": "dominant"}, {"id": "b", "label": "codominant always"}, {"id": "c", "label": "recessive"}, {"id": "d", "label": "blended"}], "answer": "c", "explanation": "Yes! The answer is \"recessive\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Genetics & Heredity! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$heredity-and-genes$tl$ and t.grade_level = 8);

-- science: Gravity & the Solar System
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Gravity & the Solar System", "body": "Gravity governs orbits, tides, eclipses, and the motions of the solar system."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The force that keeps planets in orbit around the Sun is:\n\nThe answer is \"gravity\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Gravitational force between two objects increases with greater ____ and less distance.\n\nThe answer is \"mass\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Earth's seasons are caused by the:\n\nThe answer is \"tilt of Earth's axis as it orbits\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A solar eclipse occurs when the ____ blocks sunlight to Earth.", "choices": [{"id": "a", "label": "Sun"}, {"id": "b", "label": "Moon"}, {"id": "c", "label": "another planet"}, {"id": "d", "label": "a comet"}], "answer": "b", "explanation": "Yes! The answer is \"Moon\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A lunar eclipse occurs when ____ shadow falls on the Moon.", "choices": [{"id": "a", "label": "Earth's"}, {"id": "b", "label": "the Sun's"}, {"id": "c", "label": "Mars's"}, {"id": "d", "label": "Jupiter's"}], "answer": "a", "explanation": "Yes! The answer is \"Earth's\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The Moon shines because it ____ sunlight.", "choices": [{"id": "a", "label": "produces"}, {"id": "b", "label": "reflects"}, {"id": "c", "label": "absorbs all"}, {"id": "d", "label": "blocks"}], "answer": "b", "explanation": "Yes! The answer is \"reflects\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Gravity & the Solar System! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$solar-system$tl$ and t.grade_level = 8);

-- science: Climate & Human Impact
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Climate & Human Impact", "body": "Human activities affect Earth's climate and systems; solutions reduce harm."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The buildup of carbon dioxide and methane in the atmosphere enhances the:\n\nThe answer is \"greenhouse effect\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Burning fossil fuels is a major source of:\n\nThe answer is \"carbon dioxide emissions\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Average global temperatures have been:\n\nThe answer is \"rising over the past century\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Renewable energy sources include solar, wind, and:", "choices": [{"id": "a", "label": "coal"}, {"id": "b", "label": "hydroelectric"}, {"id": "c", "label": "oil"}, {"id": "d", "label": "natural gas"}], "answer": "b", "explanation": "Yes! The answer is \"hydroelectric\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Deforestation contributes to climate change partly by removing trees that absorb:", "choices": [{"id": "a", "label": "oxygen"}, {"id": "b", "label": "carbon dioxide"}, {"id": "c", "label": "plastic"}, {"id": "d", "label": "metal"}], "answer": "b", "explanation": "Yes! The answer is \"carbon dioxide\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Loss of habitat is a leading cause of declining:", "choices": [{"id": "a", "label": "biodiversity"}, {"id": "b", "label": "pollution"}, {"id": "c", "label": "traffic"}, {"id": "d", "label": "erosion"}], "answer": "a", "explanation": "Yes! The answer is \"biodiversity\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Climate & Human Impact! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$human-impact$tl$ and t.grade_level = 8);

-- science: Plate Tectonics
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plate Tectonics", "body": "Moving plates, driven by mantle convection, reshape Earth and cause quakes and volcanoes."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Earth's lithosphere is broken into moving:\n\nThe answer is \"tectonic plates\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Plates move because of ____ currents in the mantle.\n\nThe answer is \"convection\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  At a divergent boundary, plates:\n\nThe answer is \"move apart, forming new crust\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "At a convergent boundary, plates:", "choices": [{"id": "a", "label": "spread apart"}, {"id": "b", "label": "slide past only"}, {"id": "c", "label": "vanish"}, {"id": "d", "label": "collide"}], "answer": "d", "explanation": "Yes! The answer is \"collide\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "At a transform boundary, plates:", "choices": [{"id": "a", "label": "collide head-on"}, {"id": "b", "label": "spread apart"}, {"id": "c", "label": "melt"}, {"id": "d", "label": "slide past each other"}], "answer": "d", "explanation": "Yes! The answer is \"slide past each other\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Most earthquakes and volcanoes occur:", "choices": [{"id": "a", "label": "along plate boundaries"}, {"id": "b", "label": "randomly anywhere"}, {"id": "c", "label": "in the sky"}, {"id": "d", "label": "only midplate"}], "answer": "a", "explanation": "Yes! The answer is \"along plate boundaries\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plate Tectonics! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$plate-tectonics$tl$ and t.grade_level = 8);

-- reading: Central Idea & Analysis
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Central Idea & Analysis", "body": "Determine central ideas and analyze how they develop through supporting details."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A central idea is best described as a text's:\n\nThe answer is \"most important controlling point\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Two or more central ideas in a longer text are usually connected by a:\n\nThe answer is \"shared overall message or topic\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Automation boosts productivity but also displaces some workers, forcing society to adapt.\" The central idea is that automation:\n\nThe answer is \"brings both gains and challenges\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Supporting details strengthen a central idea by providing:", "choices": [{"id": "a", "label": "evidence and examples"}, {"id": "b", "label": "distractions"}, {"id": "c", "label": "the title"}, {"id": "d", "label": "page numbers"}], "answer": "a", "explanation": "Yes! The answer is \"evidence and examples\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To analyze how a central idea develops, trace it across:", "choices": [{"id": "a", "label": "a single word"}, {"id": "b", "label": "paragraphs and sections"}, {"id": "c", "label": "the cover"}, {"id": "d", "label": "the index"}], "answer": "b", "explanation": "Yes! The answer is \"paragraphs and sections\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An objective statement of a central idea omits the reader's:", "choices": [{"id": "a", "label": "the main point"}, {"id": "b", "label": "key evidence"}, {"id": "c", "label": "topic"}, {"id": "d", "label": "personal judgments"}], "answer": "d", "explanation": "Yes! The answer is \"personal judgments\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Central Idea & Analysis! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$central-idea$tl$ and t.grade_level = 8);

-- reading: Theme Development
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Theme Development", "body": "Analyze how a theme develops over the course of a text through plot and character."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A theme is a literary work's:\n\nThe answer is \"central message about life or human nature\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Authors develop a theme through plot, conflict, and:\n\nThe answer is \"characters' choices and changes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A theme differs from a subject because a theme is a:\n\nThe answer is \"complete insight or claim\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Warned of the danger, the leaders ignored it and the city fell.\" A theme is:", "choices": [{"id": "a", "label": "ignoring wisdom invites disaster"}, {"id": "b", "label": "cities are old"}, {"id": "c", "label": "warnings are fun"}, {"id": "d", "label": "leaders are tall"}], "answer": "a", "explanation": "Yes! The answer is \"ignoring wisdom invites disaster\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A recurring symbol throughout a story often reinforces the:", "choices": [{"id": "a", "label": "index"}, {"id": "b", "label": "theme"}, {"id": "c", "label": "page count"}, {"id": "d", "label": "glossary"}], "answer": "b", "explanation": "Yes! The answer is \"theme\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To analyze theme development, track how it emerges:", "choices": [{"id": "a", "label": "only at the start"}, {"id": "b", "label": "in the title only"}, {"id": "c", "label": "over the entire text"}, {"id": "d", "label": "never"}], "answer": "c", "explanation": "Yes! The answer is \"over the entire text\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Theme Development! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$theme-development$tl$ and t.grade_level = 8);

-- reading: Objective Summary
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Objective Summary", "body": "Summarize a text's central ideas and key details objectively."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An objective summary remains:\n\nThe answer is \"neutral and free of personal opinion\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A strong summary captures the central idea and the:\n\nThe answer is \"most significant supporting details\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A summary should be ____ than the original text.\n\nThe answer is \"more concise\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Summaries should be written in:", "choices": [{"id": "a", "label": "the author's exact words"}, {"id": "b", "label": "code"}, {"id": "c", "label": "the reader's own words"}, {"id": "d", "label": "emojis"}], "answer": "c", "explanation": "Yes! The answer is \"the reader's own words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What does NOT belong in an objective summary?", "choices": [{"id": "a", "label": "the central idea"}, {"id": "b", "label": "the reader's evaluation"}, {"id": "c", "label": "key points"}, {"id": "d", "label": "the topic"}], "answer": "b", "explanation": "Yes! The answer is \"the reader's evaluation\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In summarizing an argument, include the author's claim and:", "choices": [{"id": "a", "label": "favorite color"}, {"id": "b", "label": "main supporting reasons"}, {"id": "c", "label": "birthday"}, {"id": "d", "label": "font"}], "answer": "b", "explanation": "Yes! The answer is \"main supporting reasons\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Objective Summary! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$summarizing$tl$ and t.grade_level = 8);

-- reading: Citing Strong Evidence
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Citing Strong Evidence", "body": "Cite the strongest textual evidence to support analysis and inferences."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The strongest support for an analysis is:\n\nThe answer is \"specific evidence drawn from the text\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An inference must be supported by:\n\nThe answer is \"clues and evidence in the text\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Strong textual evidence is relevant and:\n\nThe answer is \"accurate (truly stated in the text)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Quotation marks indicate the words are the:", "choices": [{"id": "a", "label": "reader's words"}, {"id": "b", "label": "a summary"}, {"id": "c", "label": "the title"}, {"id": "d", "label": "author's exact words"}], "answer": "d", "explanation": "Yes! The answer is \"author's exact words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which best supports the claim 'the narrator is unreliable'?", "choices": [{"id": "a", "label": "The book is long."}, {"id": "b", "label": "It was a Tuesday."}, {"id": "c", "label": "The cover is gray."}, {"id": "d", "label": "'I'm sure I locked it,' he said, though the door stood open."}], "answer": "d", "explanation": "Yes! The answer is \"'I'm sure I locked it,' he said, though the door stood open.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When asked to justify an interpretation, cite:", "choices": [{"id": "a", "label": "textual evidence"}, {"id": "b", "label": "a guess"}, {"id": "c", "label": "the page color"}, {"id": "d", "label": "the author's age"}], "answer": "a", "explanation": "Yes! The answer is \"textual evidence\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Citing Strong Evidence! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$textual-evidence$tl$ and t.grade_level = 8);

-- reading: Author's Purpose & Rhetoric
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Author's Purpose & Rhetoric", "body": "Analyze an author's purpose, perspective, and use of rhetorical appeals."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An author's purpose could be to inform, entertain, persuade, or:\n\nThe answer is \"explain a process\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An author's perspective is their:\n\nThe answer is \"stance or attitude toward the topic\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A persuasive essay primarily aims to:\n\nThe answer is \"convince the reader\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Emotionally charged word choice can reveal an author's:", "choices": [{"id": "a", "label": "page number"}, {"id": "b", "label": "font"}, {"id": "c", "label": "bias / perspective"}, {"id": "d", "label": "binding"}], "answer": "c", "explanation": "Yes! The answer is \"bias / perspective\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text presenting only one side of an issue is likely:", "choices": [{"id": "a", "label": "objective"}, {"id": "b", "label": "fictional"}, {"id": "c", "label": "biased"}, {"id": "d", "label": "a poem"}], "answer": "c", "explanation": "Yes! The answer is \"biased\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To find the author's purpose, ask:", "choices": [{"id": "a", "label": "why was this written?"}, {"id": "b", "label": "how long is it?"}, {"id": "c", "label": "who printed it?"}, {"id": "d", "label": "what font?"}], "answer": "a", "explanation": "Yes! The answer is \"why was this written?\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Author's Purpose & Rhetoric! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$authors-perspective$tl$ and t.grade_level = 8);

-- reading: Word Meaning & Connotation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Word Meaning & Connotation", "body": "Analyze denotation, connotation, roots, and affixes to determine meaning."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A word's denotation is its:\n\nThe answer is \"literal dictionary meaning\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A word's connotation is its:\n\nThe answer is \"emotional or implied association\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  'Frugal' and 'stingy' share a denotation but differ in:\n\nThe answer is \"connotation\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which has the more POSITIVE connotation?", "choices": [{"id": "a", "label": "arrogant"}, {"id": "b", "label": "confident"}, {"id": "c", "label": "cocky"}, {"id": "d", "label": "smug"}], "answer": "b", "explanation": "Yes! The answer is \"confident\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which has the more NEGATIVE connotation?", "choices": [{"id": "a", "label": "curious"}, {"id": "b", "label": "interested"}, {"id": "c", "label": "inquisitive"}, {"id": "d", "label": "nosy"}], "answer": "d", "explanation": "Yes! The answer is \"nosy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"A delicate aroma drifted from the kitchen.\" \"Aroma\" carries a ____ connotation.", "choices": [{"id": "a", "label": "negative"}, {"id": "b", "label": "positive"}, {"id": "c", "label": "strictly neutral"}, {"id": "d", "label": "no"}], "answer": "b", "explanation": "Yes! The answer is \"positive\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Word Meaning & Connotation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$word-connotation$tl$ and t.grade_level = 8);

-- reading: Text Structure
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Text Structure", "body": "Analyze how a text's structure organizes information and develops ideas."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A text arranged in time order uses a ____ structure.\n\nThe answer is \"chronological / sequence\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A text explaining reasons and their results uses:\n\nThe answer is \"cause and effect\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text examining similarities and differences uses:\n\nThe answer is \"compare and contrast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text that raises an issue and proposes remedies uses:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "problem and solution"}, {"id": "c", "label": "description"}, {"id": "d", "label": "compare"}], "answer": "b", "explanation": "Yes! The answer is \"problem and solution\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'consequently, thus, due to' indicate:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "compare"}, {"id": "c", "label": "description"}, {"id": "d", "label": "cause and effect"}], "answer": "d", "explanation": "Yes! The answer is \"cause and effect\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'conversely, likewise, in contrast' indicate:", "choices": [{"id": "a", "label": "compare and contrast"}, {"id": "b", "label": "sequence"}, {"id": "c", "label": "cause-effect"}, {"id": "d", "label": "problem-solution"}], "answer": "a", "explanation": "Yes! The answer is \"compare and contrast\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Text Structure! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$text-structure$tl$ and t.grade_level = 8);

-- reading: Figurative Language & Tone
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Figurative Language & Tone", "body": "Interpret figurative language and analyze how word choice creates tone and mood."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  \"The news was a punch to the gut\" is a:\n\nThe answer is \"metaphor\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  \"She fought like a tiger\" is a:\n\nThe answer is \"simile\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Giving human qualities to nonhuman things is:\n\nThe answer is \"personification\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"I'm so hungry I could eat a horse\" is:", "choices": [{"id": "a", "label": "a simile"}, {"id": "b", "label": "hyperbole"}, {"id": "c", "label": "a metaphor"}, {"id": "d", "label": "an idiom"}], "answer": "b", "explanation": "Yes! The answer is \"hyperbole\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "'Bite the bullet,' meaning to endure hardship, is an:", "choices": [{"id": "a", "label": "idiom"}, {"id": "b", "label": "literal action"}, {"id": "c", "label": "simile"}, {"id": "d", "label": "fact"}], "answer": "a", "explanation": "Yes! The answer is \"idiom\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tone is the author's ____ toward the subject.", "choices": [{"id": "a", "label": "attitude"}, {"id": "b", "label": "page count"}, {"id": "c", "label": "font"}, {"id": "d", "label": "spelling"}], "answer": "a", "explanation": "Yes! The answer is \"attitude\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Figurative Language & Tone! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$figurative-tone$tl$ and t.grade_level = 8);

-- reading: Analyzing Conflicting Sources
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Analyzing Conflicting Sources", "body": "Analyze how two texts present and interpret the same topic or event differently."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Comparing two texts on the same topic highlights their differing:\n\nThe answer is \"approaches and perspectives\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A firsthand memoir and a researched article on one event differ most in:\n\nThe answer is \"point of view and type of detail\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  When two authors disagree, a critical reader:\n\nThe answer is \"weighs the evidence and reasoning in each\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Reading several sources on a topic helps a reader develop a:", "choices": [{"id": "a", "label": "more balanced, informed view"}, {"id": "b", "label": "narrower view"}, {"id": "c", "label": "less knowledge"}, {"id": "d", "label": "ignorance of facts"}], "answer": "a", "explanation": "Yes! The answer is \"more balanced, informed view\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A primary source is created by someone who:", "choices": [{"id": "a", "label": "wrote a later textbook"}, {"id": "b", "label": "invented a story"}, {"id": "c", "label": "studied an unrelated topic"}, {"id": "d", "label": "witnessed or took part in the event"}], "answer": "d", "explanation": "Yes! The answer is \"witnessed or took part in the event\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A secondary source typically:", "choices": [{"id": "a", "label": "analyzes or interprets events afterward"}, {"id": "b", "label": "is always firsthand"}, {"id": "c", "label": "is fiction"}, {"id": "d", "label": "contains no facts"}], "answer": "a", "explanation": "Yes! The answer is \"analyzes or interprets events afterward\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Analyzing Conflicting Sources! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-authors$tl$ and t.grade_level = 8);

-- reading: Plot & Character Development
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plot & Character Development", "body": "Analyze how dialogue and events drive plot and reveal character."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The arrangement of events in a narrative is the:\n\nThe answer is \"plot\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The central struggle that drives a story is the:\n\nThe answer is \"conflict\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A character who undergoes significant change is:\n\nThe answer is \"dynamic\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A complex, multi-faceted character is described as:", "choices": [{"id": "a", "label": "flat"}, {"id": "b", "label": "static only"}, {"id": "c", "label": "round"}, {"id": "d", "label": "off-page"}], "answer": "c", "explanation": "Yes! The answer is \"round\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The moment of greatest tension and turning point is the:", "choices": [{"id": "a", "label": "climax"}, {"id": "b", "label": "exposition"}, {"id": "c", "label": "resolution"}, {"id": "d", "label": "setting"}], "answer": "a", "explanation": "Yes! The answer is \"climax\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Events that build tension before the climax are the:", "choices": [{"id": "a", "label": "resolution"}, {"id": "b", "label": "exposition"}, {"id": "c", "label": "rising action"}, {"id": "d", "label": "falling action"}], "answer": "c", "explanation": "Yes! The answer is \"rising action\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plot & Character Development! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$plot-character-development$tl$ and t.grade_level = 8);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"mountain\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"puppy\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"kitchen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "whisper"}, {"id": "b", "label": "shout"}, {"id": "c", "label": "forest"}, {"id": "d", "label": "shiny"}], "answer": "c", "explanation": "Yes! The answer is \"forest\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "fluffy"}, {"id": "b", "label": "narrow"}, {"id": "c", "label": "doctor"}, {"id": "d", "label": "shiny"}], "answer": "c", "explanation": "Yes! The answer is \"doctor\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "frozen"}, {"id": "b", "label": "gallop"}, {"id": "c", "label": "teacher"}, {"id": "d", "label": "slippery"}], "answer": "c", "explanation": "Yes! The answer is \"teacher\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 8);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action or a state of being."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"jump\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"scribble\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"bounce\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "build"}, {"id": "b", "label": "mountain"}, {"id": "c", "label": "farmer"}, {"id": "d", "label": "tiny"}], "answer": "a", "explanation": "Yes! The answer is \"build\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "discover"}, {"id": "b", "label": "gentle"}, {"id": "c", "label": "ancient"}, {"id": "d", "label": "stormy"}], "answer": "a", "explanation": "Yes! The answer is \"discover\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "golden"}, {"id": "b", "label": "river"}, {"id": "c", "label": "shout"}, {"id": "d", "label": "balloon"}], "answer": "c", "explanation": "Yes! The answer is \"shout\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 8);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"fluffy\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"shiny\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"cheerful\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "window"}, {"id": "b", "label": "swim"}, {"id": "c", "label": "discover"}, {"id": "d", "label": "frozen"}], "answer": "d", "explanation": "Yes! The answer is \"frozen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "scribble"}, {"id": "b", "label": "swim"}, {"id": "c", "label": "tiny"}, {"id": "d", "label": "village"}], "answer": "c", "explanation": "Yes! The answer is \"tiny\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "bounce"}, {"id": "b", "label": "scribble"}, {"id": "c", "label": "ancient"}, {"id": "d", "label": "whisper"}], "answer": "c", "explanation": "Yes! The answer is \"ancient\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 8);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"it\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"they\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"him\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "paint"}, {"id": "b", "label": "sister"}, {"id": "c", "label": "farmer"}, {"id": "d", "label": "you"}], "answer": "d", "explanation": "Yes! The answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "build"}, {"id": "b", "label": "garden"}, {"id": "c", "label": "jump"}, {"id": "d", "label": "her"}], "answer": "d", "explanation": "Yes! The answer is \"her\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "blanket"}, {"id": "b", "label": "discover"}, {"id": "c", "label": "jump"}, {"id": "d", "label": "I"}], "answer": "d", "explanation": "Yes! The answer is \"I\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 8);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must agree with its subject in number."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The flower ____ every day.\"\n\nThe answer is \"grows\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The singer ____ every day.\"\n\nThe answer is \"performs\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The artist ____ every day.\"\n\nThe answer is \"paints\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The snake ____ every day.\"", "choices": [{"id": "a", "label": "slither"}, {"id": "b", "label": "slithersed"}, {"id": "c", "label": "slithersing"}, {"id": "d", "label": "slithers"}], "answer": "d", "explanation": "Yes! The answer is \"slithers\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The rabbit ____ every day.\"", "choices": [{"id": "a", "label": "hop"}, {"id": "b", "label": "hops"}, {"id": "c", "label": "hopsed"}, {"id": "d", "label": "hopsing"}], "answer": "b", "explanation": "Yes! The answer is \"hops\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The student ____ every day.\"", "choices": [{"id": "a", "label": "read"}, {"id": "b", "label": "reads"}, {"id": "c", "label": "readsed"}, {"id": "d", "label": "readsing"}], "answer": "b", "explanation": "Yes! The answer is \"reads\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 8);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs describe actions that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"think\"?\n\nThe answer is \"thought\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"know\"?\n\nThe answer is \"knew\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"buy\"?\n\nThe answer is \"bought\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"grow\"?\n\nThe answer is grew."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"draw\"?\n\nThe answer is drew."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"swim\"?\n\nThe answer is swam."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 8);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals show more than one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"shelf\".\n\nThe answer is \"shelves\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"loaf\".\n\nThe answer is \"loaves\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"wish\".\n\nThe answer is \"wishes\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"penny\".\n\nThe answer is pennies."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"baby\".\n\nThe answer is babies."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"half\".\n\nThe answer is halves."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 8);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize sentence beginnings, I, and proper nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"India\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Pacific Ocean\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Australia\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "month"}, {"id": "c", "label": "river"}, {"id": "d", "label": "Nile River"}], "answer": "d", "explanation": "Yes! The answer is \"Nile River\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "December"}, {"id": "b", "label": "month"}, {"id": "c", "label": "city"}, {"id": "d", "label": "country"}], "answer": "a", "explanation": "Yes! The answer is \"December\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "river"}, {"id": "b", "label": "month"}, {"id": "c", "label": "Saturn"}, {"id": "d", "label": "country"}], "answer": "c", "explanation": "Yes! The answer is \"Saturn\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 8);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End sentences with a period, question mark, or exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"That is amazing___\"\n\nThe answer is \"!\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"When does it start___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"Look at that___\"\n\nThe answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"The cake is delicious___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "!"}, {"id": "c", "label": "."}, {"id": "d", "label": ","}], "answer": "c", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"I love to read___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "!"}, {"id": "c", "label": "."}, {"id": "d", "label": ","}], "answer": "c", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"My dog is brown___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \".\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 8);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "Use commas to separate three or more items in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like trains, planes, and buses.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like ham, cheese, and lettuce.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like piano, drums, and guitar.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like apples, grapes, and plums."}, {"id": "b", "label": "I like apples grapes and plums."}, {"id": "c", "label": "I like apples, grapes and plums"}, {"id": "d", "label": "I like, apples grapes plums."}], "answer": "a", "explanation": "Yes! The answer is \"I like apples, grapes, and plums.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like cats dogs and fish."}, {"id": "b", "label": "I like cats, dogs and fish"}, {"id": "c", "label": "I like cats, dogs, and fish."}, {"id": "d", "label": "I like, cats dogs fish."}], "answer": "c", "explanation": "Yes! The answer is \"I like cats, dogs, and fish.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like pencils pens and markers."}, {"id": "b", "label": "I like pencils, pens, and markers."}, {"id": "c", "label": "I like pencils, pens and markers"}, {"id": "d", "label": "I like, pencils pens markers."}], "answer": "b", "explanation": "Yes! The answer is \"I like pencils, pens, and markers.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 8);

