-- =====================================================================
-- TopicLeap - richer lessons for Grade 2 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Place Value to 1000
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Place Value to 1000", "body": "A three-digit number is made of hundreds, tens, and ones. In 482 the 4 means 400."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the value of the digit 7 in 782? (Write the number, e.g. 300)\n\nThe answer is \"700\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the value of the digit 3 in 403? (Write the number, e.g. 300)\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the value of the digit 4 in 554? (Write the number, e.g. 300)\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the value of the digit 4 in 345? (Write the number, e.g. 300)\n\nThe answer is 40."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the value of the digit 3 in 352? (Write the number, e.g. 300)\n\nThe answer is 300."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the value of the digit 3 in 134? (Write the number, e.g. 300)\n\nThe answer is 30."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Place Value to 1000! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$place-value-to-1000$tl$ and t.grade_level = 2);

-- math: Addition within 100
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Addition within 100", "body": "Add two-digit numbers, regrouping ones into a ten when needed."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add: 86 + 14 = ?\n\nThe answer is \"100\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Add: 38 + 53 = ?\n\nThe answer is \"91\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add: 20 + 24 = ?\n\nThe answer is \"44\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Add: 19 + 54 = ?\n\nThe answer is 73."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Add: 20 + 18 = ?\n\nThe answer is 38."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Add: 37 + 54 = ?\n\nThe answer is 91."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Addition within 100! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$addition-within-100$tl$ and t.grade_level = 2);

-- math: Subtraction within 100
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subtraction within 100", "body": "Subtract two-digit numbers, regrouping a ten into ones when needed."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Subtract: 43 - 35 = ?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Subtract: 98 - 49 = ?\n\nThe answer is \"49\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Subtract: 99 - 98 = ?\n\nThe answer is \"1\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Subtract: 82 - 27 = ?\n\nThe answer is 55."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Subtract: 71 - 52 = ?\n\nThe answer is 19."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Subtract: 22 - 10 = ?\n\nThe answer is 12."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subtraction within 100! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$subtraction-within-100$tl$ and t.grade_level = 2);

-- math: Add & Subtract within 1000
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Add & Subtract within 1000", "body": "Add and subtract three-digit numbers using hundreds, tens, and ones."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add: 425 + 387 = ?\n\nThe answer is \"812\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Subtract: 590 - 191 = ?\n\nThe answer is \"399\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add: 252 + 369 = ?\n\nThe answer is \"621\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Add: 158 + 375 = ?\n\nThe answer is 533."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Subtract: 508 - 346 = ?\n\nThe answer is 162."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Add: 309 + 108 = ?\n\nThe answer is 417."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Add & Subtract within 1000! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$add-subtract-within-1000$tl$ and t.grade_level = 2);

-- math: Skip Counting
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Skip Counting", "body": "Count by 2s, 5s, 10s, and 100s to find what comes next."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Skip count by 10s: 50, 60, 70, ___\n\nThe answer is \"80\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Skip count by 100s: 400, 500, 600, ___\n\nThe answer is \"700\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Skip count by 100s: 800, 900, 1000, ___\n\nThe answer is \"1100\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Skip count by 10s: 60, 70, 80, ___\n\nThe answer is 90."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Skip count by 10s: 40, 50, 60, ___\n\nThe answer is 70."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Skip count by 100s: 100, 200, 300, ___\n\nThe answer is 400."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Skip Counting! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$skip-counting$tl$ and t.grade_level = 2);

-- math: Comparing Numbers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Numbers", "body": "Compare three-digit numbers to tell which is greater or less."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which number is greater: 250 or 646?\n\nThe answer is \"646\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which number is greater: 948 or 703?\n\nThe answer is \"948\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which number is greater: 436 or 577?\n\nThe answer is \"577\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is greater: 472 or 427?", "choices": [{"id": "a", "label": "427"}, {"id": "b", "label": "472"}, {"id": "c", "label": "They are equal"}, {"id": "d", "label": "899"}], "answer": "b", "explanation": "Yes! The answer is \"472\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is greater: 778 or 959?", "choices": [{"id": "a", "label": "778"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "1737"}, {"id": "d", "label": "959"}], "answer": "d", "explanation": "Yes! The answer is \"959\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is greater: 166 or 799?", "choices": [{"id": "a", "label": "166"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "799"}, {"id": "d", "label": "965"}], "answer": "c", "explanation": "Yes! The answer is \"799\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Numbers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$comparing-numbers$tl$ and t.grade_level = 2);

-- math: Arrays & Equal Groups
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Arrays & Equal Groups", "body": "An array has equal rows. Add the rows up (or multiply) to find the total."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An array has 5 rows with 4 in each row. How many are there in all?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An array has 6 rows with 2 in each row. How many are there in all?\n\nThe answer is \"12\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An array has 5 rows with 5 in each row. How many are there in all?\n\nThe answer is \"25\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  An array has 5 rows with 2 in each row. How many are there in all?\n\nThe answer is 10."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  An array has 3 rows with 2 in each row. How many are there in all?\n\nThe answer is 6."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  An array has 2 rows with 4 in each row. How many are there in all?\n\nThe answer is 8."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Arrays & Equal Groups! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$arrays$tl$ and t.grade_level = 2);

-- math: Money
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Money", "body": "Count coins: a quarter is 25 cents, a dime 10, a nickel 5, and a penny 1."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  You have 1 quarter, 2 dimes, 3 nickels, 1 penny. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is \"61\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  You have 3 quarters, 1 dime, 2 nickels, 1 penny. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is \"96\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  You have 2 quarters, 2 nickels, 2 pennies. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is \"62\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  You have 1 quarter, 4 dimes, 1 nickel. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is 70."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  You have 2 quarters, 2 nickels. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is 60."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  You have 2 dimes, 3 pennies. How many cents is that in all? (quarter=25, dime=10, nickel=5, penny=1)\n\nThe answer is 23."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Money! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$money$tl$ and t.grade_level = 2);

-- math: Telling Time (5 min)
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Telling Time (5 min)", "body": "Read clocks to the nearest five minutes, like 4:15 or 7:30."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which clock time is '11 10' - 11 hours and 10 minutes?\n\nThe answer is \"11:10\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which clock time is '6 25' - 6 hours and 25 minutes?\n\nThe answer is \"6:25\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which clock time is '10 10' - 10 hours and 10 minutes?\n\nThe answer is \"10:10\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which clock time is '6 45' - 6 hours and 45 minutes?", "choices": [{"id": "a", "label": "8:55"}, {"id": "b", "label": "6:45"}, {"id": "c", "label": "4:55"}, {"id": "d", "label": "7:40"}], "answer": "b", "explanation": "Yes! The answer is \"6:45\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which clock time is '2 10' - 2 hours and 10 minutes?", "choices": [{"id": "a", "label": "3:35"}, {"id": "b", "label": "1:15"}, {"id": "c", "label": "2:10"}, {"id": "d", "label": "11:25"}], "answer": "c", "explanation": "Yes! The answer is \"2:10\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which clock time is '3 50' - 3 hours and 50 minutes?", "choices": [{"id": "a", "label": "6:35"}, {"id": "b", "label": "3:50"}, {"id": "c", "label": "2:10"}, {"id": "d", "label": "11:35"}], "answer": "b", "explanation": "Yes! The answer is \"3:50\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Telling Time (5 min)! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$telling-time$tl$ and t.grade_level = 2);

-- math: Even & Odd
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Even & Odd", "body": "Even numbers can be split into two equal groups; odd numbers have one left over."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Is the number 100 even or odd?\n\nThe answer is \"even\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Is the number 83 even or odd?\n\nThe answer is \"odd\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Is the number 79 even or odd?\n\nThe answer is \"odd\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the number 10 even or odd?", "choices": [{"id": "a", "label": "odd"}, {"id": "b", "label": "both"}, {"id": "c", "label": "neither"}, {"id": "d", "label": "even"}], "answer": "d", "explanation": "Yes! The answer is \"even\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the number 25 even or odd?", "choices": [{"id": "a", "label": "even"}, {"id": "b", "label": "both"}, {"id": "c", "label": "odd"}, {"id": "d", "label": "neither"}], "answer": "c", "explanation": "Yes! The answer is \"odd\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Is the number 11 even or odd?", "choices": [{"id": "a", "label": "odd"}, {"id": "b", "label": "even"}, {"id": "c", "label": "both"}, {"id": "d", "label": "neither"}], "answer": "a", "explanation": "Yes! The answer is \"odd\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Even & Odd! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$even-and-odd$tl$ and t.grade_level = 2);

-- science: Properties of Materials
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Properties of Materials", "body": "Materials have properties like hardness, color, texture, and flexibility that suit different jobs."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A property tells you about a material, like its color and:\n\nThe answer is \"texture (how it feels)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which material is usually hard?\n\nThe answer is \"a rock\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which material is usually soft?\n\nThe answer is \"a cotton ball\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which material is clear (you can see through it)?", "choices": [{"id": "a", "label": "wood"}, {"id": "b", "label": "glass"}, {"id": "c", "label": "a brick"}, {"id": "d", "label": "cardboard"}], "answer": "b", "explanation": "Yes! The answer is \"glass\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which material is best for keeping you warm?", "choices": [{"id": "a", "label": "ice"}, {"id": "b", "label": "glass"}, {"id": "c", "label": "wool"}, {"id": "d", "label": "metal"}], "answer": "c", "explanation": "Yes! The answer is \"wool\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which material bends easily (it is flexible)?", "choices": [{"id": "a", "label": "a brick"}, {"id": "b", "label": "rubber"}, {"id": "c", "label": "glass"}, {"id": "d", "label": "stone"}], "answer": "b", "explanation": "Yes! The answer is \"rubber\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Properties of Materials! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$properties-of-materials$tl$ and t.grade_level = 2);

-- science: Solids & Liquids
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Solids & Liquids", "body": "Solids keep their shape; liquids take the shape of their container."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A solid keeps its own:\n\nThe answer is \"shape\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A liquid takes the shape of its:\n\nThe answer is \"container\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is a solid?\n\nThe answer is \"a rock\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which is a liquid?", "choices": [{"id": "a", "label": "water"}, {"id": "b", "label": "a brick"}, {"id": "c", "label": "a chair"}, {"id": "d", "label": "a spoon"}], "answer": "a", "explanation": "Yes! The answer is \"water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "If you pour juice into a cup, it takes the shape of the:", "choices": [{"id": "a", "label": "cup"}, {"id": "b", "label": "spoon"}, {"id": "c", "label": "table"}, {"id": "d", "label": "sky"}], "answer": "a", "explanation": "Yes! The answer is \"cup\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which can you hold in your hand without it spilling?", "choices": [{"id": "a", "label": "water"}, {"id": "b", "label": "milk"}, {"id": "c", "label": "juice"}, {"id": "d", "label": "a block (solid)"}], "answer": "d", "explanation": "Yes! The answer is \"a block (solid)\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Solids & Liquids! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$solids-and-liquids$tl$ and t.grade_level = 2);

-- science: Changing Materials
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Changing Materials", "body": "Heating and cooling change materials. Some changes can be undone; some cannot."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Heating ice makes it:\n\nThe answer is \"melt into water\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Freezing water makes it:\n\nThe answer is \"turn into ice\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Melting and freezing water can be done:\n\nThe answer is \"again and again (reversible)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Baking cake batter into a cake is a change that:", "choices": [{"id": "a", "label": "cannot easily be undone"}, {"id": "b", "label": "can be undone easily"}, {"id": "c", "label": "makes more batter"}, {"id": "d", "label": "freezes it"}], "answer": "a", "explanation": "Yes! The answer is \"cannot easily be undone\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Cutting paper into pieces changes its:", "choices": [{"id": "a", "label": "shape"}, {"id": "b", "label": "material into metal"}, {"id": "c", "label": "color to gold"}, {"id": "d", "label": "weight a lot"}], "answer": "a", "explanation": "Yes! The answer is \"shape\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which change can be reversed?", "choices": [{"id": "a", "label": "burning toast"}, {"id": "b", "label": "melting butter, then cooling it"}, {"id": "c", "label": "baking bread"}, {"id": "d", "label": "frying an egg"}], "answer": "b", "explanation": "Yes! The answer is \"melting butter, then cooling it\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Changing Materials! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$changing-materials$tl$ and t.grade_level = 2);

-- science: What Plants Need
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: What Plants Need", "body": "Plants need water and sunlight to grow and make their own food."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  To grow well, plants need water, air, and:\n\nThe answer is \"sunlight\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A plant kept in a dark closet with no light will:\n\nThe answer is \"grow poorly or die\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Plants take in water mostly through their:\n\nThe answer is \"roots\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Leaves use sunlight to help make the plant's:", "choices": [{"id": "a", "label": "roots"}, {"id": "b", "label": "soil"}, {"id": "c", "label": "food"}, {"id": "d", "label": "rocks"}], "answer": "c", "explanation": "Yes! The answer is \"food\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "If you never water a plant, it will:", "choices": [{"id": "a", "label": "grow taller"}, {"id": "b", "label": "dry out and wilt"}, {"id": "c", "label": "turn blue"}, {"id": "d", "label": "make rain"}], "answer": "b", "explanation": "Yes! The answer is \"dry out and wilt\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which two things does a plant need from its surroundings?", "choices": [{"id": "a", "label": "candy and toys"}, {"id": "b", "label": "TV and music"}, {"id": "c", "label": "water and sunlight"}, {"id": "d", "label": "plastic and metal"}], "answer": "c", "explanation": "Yes! The answer is \"water and sunlight\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about What Plants Need! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$plants-need-sun-and-water$tl$ and t.grade_level = 2);

-- science: Seeds & Pollination
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Seeds & Pollination", "body": "Animals and wind help plants by moving pollen and spreading seeds to new places."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Many plants make ____ that can grow into new plants.\n\nThe answer is \"seeds\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Bees help plants by moving:\n\nThe answer is \"pollen from flower to flower\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Moving pollen between flowers is called:\n\nThe answer is \"pollination\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Some seeds are spread by sticking to animal:", "choices": [{"id": "a", "label": "teeth"}, {"id": "b", "label": "eyes"}, {"id": "c", "label": "fur"}, {"id": "d", "label": "ears only"}], "answer": "c", "explanation": "Yes! The answer is \"fur\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A dandelion's fluffy seeds are spread by the:", "choices": [{"id": "a", "label": "ocean"}, {"id": "b", "label": "wind"}, {"id": "c", "label": "fire"}, {"id": "d", "label": "Moon"}], "answer": "b", "explanation": "Yes! The answer is \"wind\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When an animal eats a fruit, it can spread the:", "choices": [{"id": "a", "label": "leaves"}, {"id": "b", "label": "roots"}, {"id": "c", "label": "seeds inside"}, {"id": "d", "label": "petals"}], "answer": "c", "explanation": "Yes! The answer is \"seeds inside\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Seeds & Pollination! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$seeds-and-pollination$tl$ and t.grade_level = 2);

-- science: Habitats & Diversity
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Habitats & Diversity", "body": "Different habitats are home to many different kinds of plants and animals."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The natural home of a living thing is its:\n\nThe answer is \"habitat\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which animal best fits a desert habitat?\n\nThe answer is \"a lizard\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which animal best fits a cold, icy habitat?\n\nThe answer is \"a polar bear\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A pond habitat is home to:", "choices": [{"id": "a", "label": "camels"}, {"id": "b", "label": "polar bears"}, {"id": "c", "label": "lions"}, {"id": "d", "label": "frogs and fish"}], "answer": "d", "explanation": "Yes! The answer is \"frogs and fish\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Different habitats are home to different kinds of:", "choices": [{"id": "a", "label": "cars"}, {"id": "b", "label": "plants and animals"}, {"id": "c", "label": "toys"}, {"id": "d", "label": "phones"}], "answer": "b", "explanation": "Yes! The answer is \"plants and animals\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A rainforest habitat is:", "choices": [{"id": "a", "label": "cold and dry"}, {"id": "b", "label": "sandy and dry"}, {"id": "c", "label": "icy"}, {"id": "d", "label": "warm and very rainy"}], "answer": "d", "explanation": "Yes! The answer is \"warm and very rainy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Habitats & Diversity! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$habitats-and-diversity$tl$ and t.grade_level = 2);

-- science: Fast & Slow Earth Changes
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Fast & Slow Earth Changes", "body": "Some land changes happen quickly (volcanoes, floods) and some slowly (erosion)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which change to the land happens FAST?\n\nThe answer is \"a volcano erupting\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which change to the land happens SLOWLY?\n\nThe answer is \"a canyon being carved by a river\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An earthquake changes the land:\n\nThe answer is \"quickly\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Water slowly wearing away rock over many years is:", "choices": [{"id": "a", "label": "a fast flood"}, {"id": "b", "label": "an earthquake"}, {"id": "c", "label": "a volcano"}, {"id": "d", "label": "slow erosion"}], "answer": "d", "explanation": "Yes! The answer is \"slow erosion\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A sudden flood can change the land:", "choices": [{"id": "a", "label": "quickly"}, {"id": "b", "label": "very slowly"}, {"id": "c", "label": "never"}, {"id": "d", "label": "only at night"}], "answer": "a", "explanation": "Yes! The answer is \"quickly\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Wind slowly shaping a sand dune is a change that is:", "choices": [{"id": "a", "label": "instant"}, {"id": "b", "label": "explosive"}, {"id": "c", "label": "loud"}, {"id": "d", "label": "slow"}], "answer": "d", "explanation": "Yes! The answer is \"slow\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Fast & Slow Earth Changes! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$fast-and-slow-earth-changes$tl$ and t.grade_level = 2);

-- science: Landforms & Maps
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Landforms & Maps", "body": "Earth has mountains, valleys, rivers, and oceans, and maps show where they are."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A tall landform that rises high above the land is a:\n\nThe answer is \"mountain\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A large body of salt water is an:\n\nThe answer is \"ocean\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A map uses symbols and a key to show:\n\nThe answer is \"places and land features\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A low area of land between mountains is a:", "choices": [{"id": "a", "label": "peak"}, {"id": "b", "label": "valley"}, {"id": "c", "label": "cliff"}, {"id": "d", "label": "plateau"}], "answer": "b", "explanation": "Yes! The answer is \"valley\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A flat, wide area of land is a:", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "canyon"}, {"id": "c", "label": "plain"}, {"id": "d", "label": "volcano"}], "answer": "c", "explanation": "Yes! The answer is \"plain\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "On many maps, which direction is at the top?", "choices": [{"id": "a", "label": "north"}, {"id": "b", "label": "south"}, {"id": "c", "label": "east"}, {"id": "d", "label": "down"}], "answer": "a", "explanation": "Yes! The answer is \"north\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Landforms & Maps! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$landforms-and-maps$tl$ and t.grade_level = 2);

-- science: Water on Earth
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Water on Earth", "body": "Water is found in oceans, lakes, rivers, ice, and underground; ocean water is salty."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Most of the water on Earth is found in the:\n\nThe answer is \"oceans\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Ocean water is:\n\nThe answer is \"salty\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which holds fresh water we can drink?\n\nThe answer is \"a lake or river\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Frozen water at the cold poles is found as:", "choices": [{"id": "a", "label": "sand"}, {"id": "b", "label": "ice"}, {"id": "c", "label": "soil"}, {"id": "d", "label": "steam"}], "answer": "b", "explanation": "Yes! The answer is \"ice\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which is a body of fresh water?", "choices": [{"id": "a", "label": "a pond"}, {"id": "b", "label": "the ocean"}, {"id": "c", "label": "a sea"}, {"id": "d", "label": "a salty bay"}], "answer": "a", "explanation": "Yes! The answer is \"a pond\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Water in the sky inside clouds is made of tiny:", "choices": [{"id": "a", "label": "rocks"}, {"id": "b", "label": "sand"}, {"id": "c", "label": "water droplets"}, {"id": "d", "label": "smoke"}], "answer": "c", "explanation": "Yes! The answer is \"water droplets\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Water on Earth! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$water-on-earth$tl$ and t.grade_level = 2);

-- science: Wind & Water Shape Land
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Wind & Water Shape Land", "body": "Wind and water slowly wear away and move soil and rock, changing the land."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Moving water can carry away soil and sand. This is:\n\nThe answer is \"erosion\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Wind can shape the land by moving:\n\nThe answer is \"sand into dunes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A river slowly carving a path through rock makes a:\n\nThe answer is \"canyon or valley\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Ocean waves hitting a cliff cause the cliff to:", "choices": [{"id": "a", "label": "wear away"}, {"id": "b", "label": "grow taller"}, {"id": "c", "label": "get colder"}, {"id": "d", "label": "turn to metal"}], "answer": "a", "explanation": "Yes! The answer is \"wear away\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which slows down soil erosion on a hill?", "choices": [{"id": "a", "label": "removing all plants"}, {"id": "b", "label": "planting grass and trees"}, {"id": "c", "label": "adding loose sand"}, {"id": "d", "label": "pouring more water"}], "answer": "b", "explanation": "Yes! The answer is \"planting grass and trees\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When a river drops the sand it carried, it builds up:", "choices": [{"id": "a", "label": "a mountain instantly"}, {"id": "b", "label": "a cloud"}, {"id": "c", "label": "a canyon"}, {"id": "d", "label": "new land (deposition)"}], "answer": "d", "explanation": "Yes! The answer is \"new land (deposition)\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Wind & Water Shape Land! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$wind-and-water-shape-land$tl$ and t.grade_level = 2);

-- reading: Main Idea
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Main Idea", "body": "The main idea is the most important point a text makes."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Honeybees are helpful. They make honey and help flowers grow by moving pollen.\" The main idea is that honeybees:\n\nThe answer is \"are helpful\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Recycling is good. It saves trees, uses less energy, and keeps trash out of landfills.\" The main idea is that recycling:\n\nThe answer is \"is good for the Earth\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Penguins stay warm with thick feathers, a layer of fat, and by huddling together.\" The passage is mostly about how penguins:\n\nThe answer is \"stay warm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Our class garden grew well. We planted seeds, watered them, and pulled weeds.\" The main idea is that the class:", "choices": [{"id": "a", "label": "went on a trip"}, {"id": "b", "label": "grew a garden"}, {"id": "c", "label": "had a party"}, {"id": "d", "label": "read books"}], "answer": "b", "explanation": "Yes! The answer is \"grew a garden\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Firefighters are brave. They put out fires, rescue people, and teach safety.\" The main idea is that firefighters:", "choices": [{"id": "a", "label": "are tall"}, {"id": "b", "label": "drive fast"}, {"id": "c", "label": "do an important job"}, {"id": "d", "label": "like red"}], "answer": "c", "explanation": "Yes! The answer is \"do an important job\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Sea turtles travel far in the ocean and return to the beach where they were born.\" The main idea is that sea turtles:", "choices": [{"id": "a", "label": "travel far and return home"}, {"id": "b", "label": "eat plants"}, {"id": "c", "label": "are small"}, {"id": "d", "label": "sleep a lot"}], "answer": "a", "explanation": "Yes! The answer is \"travel far and return home\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Main Idea! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$main-idea$tl$ and t.grade_level = 2);

-- reading: Key Details
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Key Details", "body": "Key details are the facts that tell more about the main idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The hike was perfect. We saw a calm lake, tall pines, and a fire pit.\" Which detail was on the hike?\n\nThe answer is \"a calm lake\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Our hamster runs on its wheel, stuffs food in its cheeks, and naps a lot.\" Which detail is true?\n\nThe answer is \"it runs on its wheel\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The storm was fierce: lightning flashed and wind bent the trees.\" Which detail shows it was fierce?\n\nThe answer is \"wind bent the trees\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Grandpa grows tomatoes, sunflowers, and sweet strawberries.\" Which does Grandpa grow?", "choices": [{"id": "a", "label": "a car"}, {"id": "b", "label": "strawberries"}, {"id": "c", "label": "a boat"}, {"id": "d", "label": "a kite"}], "answer": "b", "explanation": "Yes! The answer is \"strawberries\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"At the museum we saw dinosaur bones, old coins, and paintings.\" Which detail is true?", "choices": [{"id": "a", "label": "the bus was late"}, {"id": "b", "label": "we saw dinosaur bones"}, {"id": "c", "label": "lunch was good"}, {"id": "d", "label": "it was sunny"}], "answer": "b", "explanation": "Yes! The answer is \"we saw dinosaur bones\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"My brother carries groceries, walks the dog, and helps with homework.\" Which detail shows he helps?", "choices": [{"id": "a", "label": "he walks the dog"}, {"id": "b", "label": "he watches TV all day"}, {"id": "c", "label": "he is tall"}, {"id": "d", "label": "he likes pizza"}], "answer": "a", "explanation": "Yes! The answer is \"he walks the dog\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Key Details! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$key-details$tl$ and t.grade_level = 2);

-- reading: Story Lessons
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Story Lessons", "body": "Many stories teach a lesson or moral about how to live or treat others."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The hare bragged and napped during the race. The slow tortoise kept going and won.\" The lesson is:\n\nThe answer is \"slow and steady wins the race\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"The ant worked all summer storing food. The grasshopper played and had none in winter.\" The lesson is:\n\nThe answer is \"plan ahead and work hard\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Maya kept trying to ride her bike, fell many times, but finally did it.\" The lesson is:\n\nThe answer is \"don't give up\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Leo shared his snack, and his friend shared back the next day.\" The lesson is:", "choices": [{"id": "a", "label": "never share"}, {"id": "b", "label": "being kind comes back to you"}, {"id": "c", "label": "food is bad"}, {"id": "d", "label": "friends are mean"}], "answer": "b", "explanation": "Yes! The answer is \"being kind comes back to you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The boy cried 'wolf' as a joke so often that no one believed him when it was real.\" The lesson is:", "choices": [{"id": "a", "label": "tell the truth"}, {"id": "b", "label": "jokes are great"}, {"id": "c", "label": "wolves are nice"}, {"id": "d", "label": "shout a lot"}], "answer": "a", "explanation": "Yes! The answer is \"tell the truth\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Ana told the truth even though she was scared, and her mom was proud.\" The lesson is:", "choices": [{"id": "a", "label": "hide mistakes"}, {"id": "b", "label": "never speak"}, {"id": "c", "label": "honesty is important"}, {"id": "d", "label": "fear is bad"}], "answer": "c", "explanation": "Yes! The answer is \"honesty is important\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Story Lessons! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$story-lesson$tl$ and t.grade_level = 2);

-- reading: Character Feelings
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Character Feelings", "body": "Look at what characters do and say to understand how they feel."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Tia smiled wide and hugged her trophy.\" How does Tia feel?\n\nThe answer is \"happy / proud\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Ben's eyes filled with tears when his balloon popped.\" How does Ben feel?\n\nThe answer is \"sad\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Mia stomped her feet and crossed her arms.\" How does Mia feel?\n\nThe answer is \"angry\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Leo hid under the blanket during the loud storm.\" How does Leo feel?", "choices": [{"id": "a", "label": "proud"}, {"id": "b", "label": "scared"}, {"id": "c", "label": "bored"}, {"id": "d", "label": "silly"}], "answer": "b", "explanation": "Yes! The answer is \"scared\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Ana jumped up and down when she heard the great news.\" How does Ana feel?", "choices": [{"id": "a", "label": "sad"}, {"id": "b", "label": "angry"}, {"id": "c", "label": "tired"}, {"id": "d", "label": "excited"}], "answer": "d", "explanation": "Yes! The answer is \"excited\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Sam yawned and rubbed his eyes at bedtime.\" How does Sam feel?", "choices": [{"id": "a", "label": "excited"}, {"id": "b", "label": "angry"}, {"id": "c", "label": "scared"}, {"id": "d", "label": "sleepy"}], "answer": "d", "explanation": "Yes! The answer is \"sleepy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Character Feelings! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$character-feelings$tl$ and t.grade_level = 2);

-- reading: Sequence of Events
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sequence of Events", "body": "Sequence is the order things happen: first, next, then, and last."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"First Ana woke up. Next she ate. Then she went to school.\" What did Ana do FIRST?\n\nThe answer is \"woke up\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"He read the recipe, gathered the food, then cooked.\" What did he do BEFORE cooking?\n\nThe answer is \"gathered the food\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The caterpillar ate leaves, made a chrysalis, then became a butterfly.\" What happened LAST?\n\nThe answer is \"it became a butterfly\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"We bought tickets, found our seats, and watched the show.\" What came SECOND?", "choices": [{"id": "a", "label": "bought tickets"}, {"id": "b", "label": "found our seats"}, {"id": "c", "label": "watched the show"}, {"id": "d", "label": "went home"}], "answer": "b", "explanation": "Yes! The answer is \"found our seats\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"First fill the pot, next turn on the stove, then add pasta.\" What is the SECOND step?", "choices": [{"id": "a", "label": "add pasta"}, {"id": "b", "label": "turn on the stove"}, {"id": "c", "label": "fill the pot"}, {"id": "d", "label": "eat"}], "answer": "b", "explanation": "Yes! The answer is \"turn on the stove\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She drew a picture, colored it, then hung it up.\" What did she do LAST?", "choices": [{"id": "a", "label": "drew it"}, {"id": "b", "label": "hung it up"}, {"id": "c", "label": "colored it"}, {"id": "d", "label": "erased it"}], "answer": "b", "explanation": "Yes! The answer is \"hung it up\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sequence of Events! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$sequence$tl$ and t.grade_level = 2);

-- reading: Cause & Effect
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Cause & Effect", "body": "A cause is why something happens; the effect is what happens."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"It rained all day, so the game was canceled.\" What was the CAUSE?\n\nThe answer is \"it rained all day\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Tom forgot to water his plant, so it wilted.\" What was the EFFECT?\n\nThe answer is \"the plant wilted\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The ice melted because the day was hot.\" Why did the ice melt?\n\nThe answer is \"the day was hot\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She studied hard, so she passed the test.\" What caused her to pass?", "choices": [{"id": "a", "label": "the test was easy"}, {"id": "b", "label": "she was late"}, {"id": "c", "label": "she studied hard"}, {"id": "d", "label": "she slept"}], "answer": "c", "explanation": "Yes! The answer is \"she studied hard\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The dog barked loudly, so the baby woke up.\" What was the effect of the barking?", "choices": [{"id": "a", "label": "the dog slept"}, {"id": "b", "label": "the baby woke up"}, {"id": "c", "label": "the baby ate"}, {"id": "d", "label": "the dog ran"}], "answer": "b", "explanation": "Yes! The answer is \"the baby woke up\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Because the road was icy, the cars drove slowly.\" Why did the cars drive slowly?", "choices": [{"id": "a", "label": "the road was icy"}, {"id": "b", "label": "the cars were red"}, {"id": "c", "label": "it was sunny"}, {"id": "d", "label": "the road was new"}], "answer": "a", "explanation": "Yes! The answer is \"the road was icy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Cause & Effect! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$cause-and-effect$tl$ and t.grade_level = 2);

-- reading: Vocabulary in Context
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Vocabulary in Context", "body": "Use the words around an unknown word to figure out its meaning."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The path was narrow, so only one person could pass.\" What does \"narrow\" mean?\n\nThe answer is \"not wide\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"The soup was scalding, so she let it cool.\" What does \"scalding\" mean?\n\nThe answer is \"very hot\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"He was exhausted after the long run.\" What does \"exhausted\" mean?\n\nThe answer is \"very tired\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The ancient ruins were thousands of years old.\" What does \"ancient\" mean?", "choices": [{"id": "a", "label": "brand new"}, {"id": "b", "label": "colorful"}, {"id": "c", "label": "very old"}, {"id": "d", "label": "tiny"}], "answer": "c", "explanation": "Yes! The answer is \"very old\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The timid puppy hid behind the couch.\" What does \"timid\" mean?", "choices": [{"id": "a", "label": "shy or fearful"}, {"id": "b", "label": "loud"}, {"id": "c", "label": "huge"}, {"id": "d", "label": "fast"}], "answer": "a", "explanation": "Yes! The answer is \"shy or fearful\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The enormous elephant was the biggest animal there.\" What does \"enormous\" mean?", "choices": [{"id": "a", "label": "very large"}, {"id": "b", "label": "very small"}, {"id": "c", "label": "very fast"}, {"id": "d", "label": "very quiet"}], "answer": "a", "explanation": "Yes! The answer is \"very large\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Vocabulary in Context! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$context-clues$tl$ and t.grade_level = 2);

-- reading: Synonyms & Antonyms
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Synonyms & Antonyms", "body": "Synonyms mean almost the same; antonyms mean the opposite."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word means almost the same as \"happy\"?\n\nThe answer is \"glad\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is the OPPOSITE of \"big\"?\n\nThe answer is \"small\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A synonym for \"fast\" is:\n\nThe answer is \"quick\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The opposite of \"hot\" is:", "choices": [{"id": "a", "label": "warm"}, {"id": "b", "label": "boiling"}, {"id": "c", "label": "sunny"}, {"id": "d", "label": "cold"}], "answer": "d", "explanation": "Yes! The answer is \"cold\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A synonym for \"begin\" is:", "choices": [{"id": "a", "label": "stop"}, {"id": "b", "label": "start"}, {"id": "c", "label": "end"}, {"id": "d", "label": "finish"}], "answer": "b", "explanation": "Yes! The answer is \"start\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An antonym for \"empty\" is:", "choices": [{"id": "a", "label": "bare"}, {"id": "b", "label": "hollow"}, {"id": "c", "label": "full"}, {"id": "d", "label": "vacant"}], "answer": "c", "explanation": "Yes! The answer is \"full\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Synonyms & Antonyms! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$synonyms-and-antonyms$tl$ and t.grade_level = 2);

-- reading: Fact vs. Opinion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Fact vs. Opinion", "body": "A fact can be proven; an opinion tells what someone feels."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence is a FACT?\n\nThe answer is \"Water freezes when it gets very cold.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence is an OPINION?\n\nThe answer is \"Recess is the most fun part of the day.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is a FACT?\n\nThe answer is \"A triangle has three sides.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which is an OPINION?", "choices": [{"id": "a", "label": "Chocolate is the best flavor."}, {"id": "b", "label": "Ice melts when heated."}, {"id": "c", "label": "There are 12 months."}, {"id": "d", "label": "Plants need sunlight."}], "answer": "a", "explanation": "Yes! The answer is \"Chocolate is the best flavor.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"Our school has 300 students.\" This is a:", "choices": [{"id": "a", "label": "opinion"}, {"id": "b", "label": "fact"}, {"id": "c", "label": "question"}, {"id": "d", "label": "story"}], "answer": "b", "explanation": "Yes! The answer is \"fact\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"Reading is more fun than TV.\" This is an:", "choices": [{"id": "a", "label": "fact"}, {"id": "b", "label": "rule"}, {"id": "c", "label": "number"}, {"id": "d", "label": "opinion"}], "answer": "d", "explanation": "Yes! The answer is \"opinion\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Fact vs. Opinion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$fact-and-opinion$tl$ and t.grade_level = 2);

-- reading: Comparing Texts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Texts", "body": "We can compare two texts to see how they are alike and different."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  One book says dogs make great pets; another says cats do. Both books are about:\n\nThe answer is \"good pets\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Two stories both have a brave hero, but one is in space and one is under the sea. They are alike because both have:\n\nThe answer is \"a brave hero\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Book A is about how rain forms; Book B is about how snow forms. Both are about:\n\nThe answer is \"kinds of weather\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "One text says summer is best; another says winter is best. They differ on the best:", "choices": [{"id": "a", "label": "color"}, {"id": "b", "label": "number"}, {"id": "c", "label": "letter"}, {"id": "d", "label": "season"}], "answer": "d", "explanation": "Yes! The answer is \"season\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Two articles describe bees and butterflies. Both insects:", "choices": [{"id": "a", "label": "live in water"}, {"id": "b", "label": "have fur"}, {"id": "c", "label": "help pollinate flowers"}, {"id": "d", "label": "bark"}], "answer": "c", "explanation": "Yes! The answer is \"help pollinate flowers\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Story 1 ends happily; Story 2 ends sadly. They differ in their:", "choices": [{"id": "a", "label": "title only"}, {"id": "b", "label": "ending"}, {"id": "c", "label": "number of pages only"}, {"id": "d", "label": "author's name"}], "answer": "b", "explanation": "Yes! The answer is \"ending\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Texts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-texts$tl$ and t.grade_level = 2);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"engine\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"doctor\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"forest\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "gentle"}, {"id": "b", "label": "window"}, {"id": "c", "label": "wander"}, {"id": "d", "label": "whisper"}], "answer": "b", "explanation": "Yes! The answer is \"window\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "curious"}, {"id": "b", "label": "mountain"}, {"id": "c", "label": "narrow"}, {"id": "d", "label": "ancient"}], "answer": "b", "explanation": "Yes! The answer is \"mountain\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "golden"}, {"id": "b", "label": "library"}, {"id": "c", "label": "cheerful"}, {"id": "d", "label": "stormy"}], "answer": "b", "explanation": "Yes! The answer is \"library\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 2);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action - what the subject does."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"discover\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"explore\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"gallop\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "gentle"}, {"id": "b", "label": "puppy"}, {"id": "c", "label": "wander"}, {"id": "d", "label": "sister"}], "answer": "c", "explanation": "Yes! The answer is \"wander\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "whisper"}, {"id": "b", "label": "pencil"}, {"id": "c", "label": "stormy"}, {"id": "d", "label": "window"}], "answer": "a", "explanation": "Yes! The answer is \"whisper\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "blanket"}, {"id": "b", "label": "frozen"}, {"id": "c", "label": "slippery"}, {"id": "d", "label": "scribble"}], "answer": "d", "explanation": "Yes! The answer is \"scribble\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 2);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun, telling what kind or how many."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"golden\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"enormous\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"slippery\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "gallop"}, {"id": "b", "label": "sister"}, {"id": "c", "label": "stretch"}, {"id": "d", "label": "frozen"}], "answer": "d", "explanation": "Yes! The answer is \"frozen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "island"}, {"id": "b", "label": "tiny"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "pencil"}], "answer": "b", "explanation": "Yes! The answer is \"tiny\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "paint"}, {"id": "b", "label": "cheerful"}, {"id": "c", "label": "scribble"}, {"id": "d", "label": "doctor"}], "answer": "b", "explanation": "Yes! The answer is \"cheerful\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 2);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun, like he, she, it, or they."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"her\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"us\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "him"}, {"id": "b", "label": "shout"}, {"id": "c", "label": "village"}, {"id": "d", "label": "doctor"}], "answer": "a", "explanation": "Yes! The answer is \"him\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "paint"}, {"id": "b", "label": "puppy"}, {"id": "c", "label": "I"}, {"id": "d", "label": "whisper"}], "answer": "c", "explanation": "Yes! The answer is \"I\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "gallop"}, {"id": "b", "label": "wander"}, {"id": "c", "label": "they"}, {"id": "d", "label": "forest"}], "answer": "c", "explanation": "Yes! The answer is \"they\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 2);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must match the subject, like 'The dog runs.'"}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The rabbit ____ every day.\"\n\nThe answer is \"hops\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The baby ____ every day.\"\n\nThe answer is \"cries\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The singer ____ every day.\"\n\nThe answer is \"performs\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The bird ____ every day.\"", "choices": [{"id": "a", "label": "sing"}, {"id": "b", "label": "singsed"}, {"id": "c", "label": "singsing"}, {"id": "d", "label": "sings"}], "answer": "d", "explanation": "Yes! The answer is \"sings\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The engine ____ every day.\"", "choices": [{"id": "a", "label": "roar"}, {"id": "b", "label": "roars"}, {"id": "c", "label": "roarsed"}, {"id": "d", "label": "roarsing"}], "answer": "b", "explanation": "Yes! The answer is \"roars\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The girl ____ every day.\"", "choices": [{"id": "a", "label": "run"}, {"id": "b", "label": "runs"}, {"id": "c", "label": "runsed"}, {"id": "d", "label": "runsing"}], "answer": "b", "explanation": "Yes! The answer is \"runs\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 2);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs tell about something that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"draw\"?\n\nThe answer is \"drew\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"drink\"?\n\nThe answer is \"drank\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"throw\"?\n\nThe answer is \"threw\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"eat\"?\n\nThe answer is ate."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"go\"?\n\nThe answer is went."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"make\"?\n\nThe answer is made."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 2);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals mean more than one. Add -s or -es, or change y to -ies."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"fairy\".\n\nThe answer is \"fairies\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"baby\".\n\nThe answer is \"babies\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"half\".\n\nThe answer is \"halves\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"knife\".\n\nThe answer is knives."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"story\".\n\nThe answer is stories."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"fox\".\n\nThe answer is foxes."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 2);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize the first word of a sentence, the word I, and proper nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Nile River\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"July\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"New York\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "friend"}, {"id": "b", "label": "mountain"}, {"id": "c", "label": "India"}, {"id": "d", "label": "city"}], "answer": "c", "explanation": "Yes! The answer is \"India\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "Mount Everest"}, {"id": "b", "label": "city"}, {"id": "c", "label": "country"}, {"id": "d", "label": "river"}], "answer": "a", "explanation": "Yes! The answer is \"Mount Everest\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "river"}, {"id": "c", "label": "friend"}, {"id": "d", "label": "Friday"}], "answer": "d", "explanation": "Yes! The answer is \"Friday\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 2);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End a sentence with a period, question mark, or exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"Watch out___\"\n\nThe answer is \"!\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"Are you ready___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"The sky is blue___\"\n\nThe answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Where are we going___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "."}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"She likes apples___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "."}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "b", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"The cake is delicious___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \".\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 2);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "Use commas to separate three or more items in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like milk, eggs, and bread.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like red, green, and blue.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like apples, oranges, and pears.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like cats, dogs, and fish."}, {"id": "b", "label": "I like cats dogs and fish."}, {"id": "c", "label": "I like cats, dogs and fish"}, {"id": "d", "label": "I like, cats dogs fish."}], "answer": "a", "explanation": "Yes! The answer is \"I like cats, dogs, and fish.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like pencils pens and markers."}, {"id": "b", "label": "I like pencils, pens and markers"}, {"id": "c", "label": "I like, pencils pens markers."}, {"id": "d", "label": "I like pencils, pens, and markers."}], "answer": "d", "explanation": "Yes! The answer is \"I like pencils, pens, and markers.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like soccer tennis and golf."}, {"id": "b", "label": "I like soccer, tennis, and golf."}, {"id": "c", "label": "I like soccer, tennis and golf"}, {"id": "d", "label": "I like, soccer tennis golf."}], "answer": "b", "explanation": "Yes! The answer is \"I like soccer, tennis, and golf.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 2);

