-- =====================================================================
-- TopicLeap - richer lessons for Grade 1 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Counting to 120
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Counting to 120", "body": "Count forward and find what number comes next, all the way to 120."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What number comes next?  25, 26, ___\n\nThe answer is \"27\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What number comes right after 97?\n\nThe answer is \"98\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What number comes next?  102, 103, ___\n\nThe answer is \"104\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What number comes next?  28, 29, ___\n\nThe answer is 30."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What number comes right after 51?\n\nThe answer is 52."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What number comes next?  82, 83, ___\n\nThe answer is 84."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Counting to 120! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$counting-to-120$tl$ and t.grade_level = 1);

-- math: Addition within 20
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Addition within 20", "body": "Add two numbers that add up to 20 or less. Count on to find the total."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add: 2 + 15 = ?\n\nThe answer is \"17\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Add: 1 + 5 = ?\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add: 3 + 14 = ?\n\nThe answer is \"17\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Add: 10 + 9 = ?\n\nThe answer is 19."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Add: 10 + 3 = ?\n\nThe answer is 13."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Add: 10 + 2 = ?\n\nThe answer is 12."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Addition within 20! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$addition-within-20$tl$ and t.grade_level = 1);

-- math: Subtraction within 20
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subtraction within 20", "body": "Take away to find how many are left, with numbers up to 20."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Subtract: 18 - 8 = ?\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Subtract: 3 - 2 = ?\n\nThe answer is \"1\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Subtract: 15 - 14 = ?\n\nThe answer is \"1\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Subtract: 3 - 1 = ?\n\nThe answer is 2."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Subtract: 14 - 10 = ?\n\nThe answer is 4."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Subtract: 20 - 17 = ?\n\nThe answer is 3."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subtraction within 20! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$subtraction-within-20$tl$ and t.grade_level = 1);

-- math: Tens & Ones
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Tens & Ones", "body": "A two-digit number is made of tens and ones. In 34 there are 3 tens and 4 ones."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  How many TENS are in the number 94?\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  How many ONES are in the number 61?\n\nThe answer is \"1\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  How many TENS are in the number 25?\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  How many TENS are in the number 35?\n\nThe answer is 3."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  How many ONES are in the number 97?\n\nThe answer is 7."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  How many TENS are in the number 19?\n\nThe answer is 1."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Tens & Ones! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$tens-and-ones$tl$ and t.grade_level = 1);

-- math: Comparing Numbers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Numbers", "body": "Compare two numbers to tell which one is bigger (greater) or smaller (less)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which number is bigger: 37 or 43?\n\nThe answer is \"43\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which number is bigger: 19 or 4?\n\nThe answer is \"19\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which number is bigger: 14 or 21?\n\nThe answer is \"21\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is bigger: 90 or 5?", "choices": [{"id": "a", "label": "5"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "95"}, {"id": "d", "label": "90"}], "answer": "d", "explanation": "Yes! The answer is \"90\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is bigger: 46 or 49?", "choices": [{"id": "a", "label": "46"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "49"}, {"id": "d", "label": "95"}], "answer": "c", "explanation": "Yes! The answer is \"49\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which number is bigger: 12 or 74?", "choices": [{"id": "a", "label": "12"}, {"id": "b", "label": "They are equal"}, {"id": "c", "label": "74"}, {"id": "d", "label": "86"}], "answer": "c", "explanation": "Yes! The answer is \"74\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Numbers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$comparing-numbers$tl$ and t.grade_level = 1);

-- math: Adding Tens
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adding Tens", "body": "Add whole tens together, like 30 + 40, by counting the tens."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add the tens: 20 + 80 = ?\n\nThe answer is \"100\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Add the tens: 10 + 30 = ?\n\nThe answer is \"40\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add the tens: 20 + 40 = ?\n\nThe answer is \"60\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Add the tens: 20 + 70 = ?\n\nThe answer is 90."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Add the tens: 50 + 20 = ?\n\nThe answer is 70."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Add the tens: 30 + 40 = ?\n\nThe answer is 70."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adding Tens! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$adding-tens$tl$ and t.grade_level = 1);

-- math: Shapes
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Shapes", "body": "Learn the names of shapes like circle, square, triangle, and rectangle."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is a square?\n\nThe answer is \"\ud83d\udfe6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is a rectangle?\n\nThe answer is \"\u25ac\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is a circle?\n\nThe answer is \"\u2b55\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a square?", "choices": [{"id": "a", "label": "\u25ac"}, {"id": "b", "label": "\u2764\ufe0f"}, {"id": "c", "label": "\ud83d\udfe6"}, {"id": "d", "label": "\u2b55"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udfe6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a square?", "choices": [{"id": "a", "label": "\ud83d\udd3a"}, {"id": "b", "label": "\ud83d\udfe6"}, {"id": "c", "label": "\u25ac"}, {"id": "d", "label": "\u2b50"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udfe6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a square?", "choices": [{"id": "a", "label": "\ud83d\udfe6"}, {"id": "b", "label": "\ud83d\udd3a"}, {"id": "c", "label": "\u2b50"}, {"id": "d", "label": "\u2764\ufe0f"}], "answer": "a", "explanation": "Yes! The answer is \"\ud83d\udfe6\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Shapes! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$shapes$tl$ and t.grade_level = 1);

-- math: Telling Time (Hour)
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Telling Time (Hour)", "body": "When the big hand points to 12 and the little hand points to a number, it is that o'clock."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A clock's big hand points to 12 and the little hand points to 8. What time is it?\n\nThe answer is \"8:00\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A clock's big hand points to 12 and the little hand points to 11. What time is it?\n\nThe answer is \"11:00\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A clock's big hand points to 12 and the little hand points to 6. What time is it?\n\nThe answer is \"6:00\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A clock's big hand points to 12 and the little hand points to 4. What time is it?", "choices": [{"id": "a", "label": "4:00"}, {"id": "b", "label": "8:00"}, {"id": "c", "label": "3:00"}, {"id": "d", "label": "6:00"}], "answer": "a", "explanation": "Yes! The answer is \"4:00\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A clock's big hand points to 12 and the little hand points to 1. What time is it?", "choices": [{"id": "a", "label": "2:00"}, {"id": "b", "label": "10:00"}, {"id": "c", "label": "8:00"}, {"id": "d", "label": "1:00"}], "answer": "d", "explanation": "Yes! The answer is \"1:00\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A clock's big hand points to 12 and the little hand points to 11. What time is it?", "choices": [{"id": "a", "label": "7:00"}, {"id": "b", "label": "11:00"}, {"id": "c", "label": "8:00"}, {"id": "d", "label": "2:00"}], "answer": "b", "explanation": "Yes! The answer is \"11:00\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Telling Time (Hour)! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$time-to-the-hour$tl$ and t.grade_level = 1);

-- math: Number Order
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Number Order", "body": "Numbers come in order. Find the number that comes between two others."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What number comes between 91 and 93?\n\nThe answer is \"92\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What number comes between 23 and 25?\n\nThe answer is \"24\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What number comes between 20 and 22?\n\nThe answer is \"21\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What number comes between 113 and 115?\n\nThe answer is 114."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What number comes between 56 and 58?\n\nThe answer is 57."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What number comes between 59 and 61?\n\nThe answer is 60."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Number Order! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$number-order$tl$ and t.grade_level = 1);

-- math: Word Problems
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Word Problems", "body": "Read a short story and add or subtract to solve the problem."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Mia has 4 crayons and gets 1 more. How many crayons now?\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Ava has 5 blocks and gives away 2. How many blocks are left?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Ben has 10 marbles and gets 8 more. How many marbles now?\n\nThe answer is \"18\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Mia has 3 crayons and gets 3 more. How many crayons now?\n\nThe answer is 6."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Zoe has 8 stickers and gives away 4. How many stickers are left?\n\nThe answer is 4."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Sam has 6 blocks and gets 1 more. How many blocks now?\n\nThe answer is 7."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Word Problems! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$word-problems$tl$ and t.grade_level = 1);

-- science: Light & Seeing
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Light & Seeing", "body": "We need light to see. The Sun, lamps, and flashlights give off light."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What do your eyes need to be able to see things?\n\nThe answer is \"light\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  In a completely dark room with no light, you can:\n\nThe answer is \"see nothing\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which gives off light?\n\nThe answer is \"the Sun\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "At night we use a lamp or flashlight so we can:", "choices": [{"id": "a", "label": "see"}, {"id": "b", "label": "hear"}, {"id": "c", "label": "smell"}, {"id": "d", "label": "taste"}], "answer": "a", "explanation": "Yes! The answer is \"see\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which object makes its own light?", "choices": [{"id": "a", "label": "a candle"}, {"id": "b", "label": "a spoon"}, {"id": "c", "label": "a book"}, {"id": "d", "label": "a shoe"}], "answer": "a", "explanation": "Yes! The answer is \"a candle\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Why can you see the Moon at night?", "choices": [{"id": "a", "label": "it is on fire"}, {"id": "b", "label": "it is a lamp"}, {"id": "c", "label": "light bounces off it"}, {"id": "d", "label": "it makes sound"}], "answer": "c", "explanation": "Yes! The answer is \"light bounces off it\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Light & Seeing! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$light-and-seeing$tl$ and t.grade_level = 1);

-- science: Sound & Vibration
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sound & Vibration", "body": "Sound is made when something vibrates (shakes quickly), and we hear it with our ears."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Sound is made when something:\n\nThe answer is \"vibrates (shakes quickly)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  When you pluck a guitar string, it makes sound because it:\n\nThe answer is \"vibrates\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A drum makes sound when its top:\n\nThe answer is \"vibrates after you hit it\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To make a louder sound on a drum, you hit it:", "choices": [{"id": "a", "label": "harder"}, {"id": "b", "label": "softer"}, {"id": "c", "label": "not at all"}, {"id": "d", "label": "with a feather"}], "answer": "a", "explanation": "Yes! The answer is \"harder\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which would make a quiet sound?", "choices": [{"id": "a", "label": "a soft whisper"}, {"id": "b", "label": "a loud shout"}, {"id": "c", "label": "a banging drum"}, {"id": "d", "label": "a fire truck siren"}], "answer": "a", "explanation": "Yes! The answer is \"a soft whisper\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "You hear sounds with your:", "choices": [{"id": "a", "label": "ears"}, {"id": "b", "label": "eyes"}, {"id": "c", "label": "nose"}, {"id": "d", "label": "hands"}], "answer": "a", "explanation": "Yes! The answer is \"ears\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sound & Vibration! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$sound-and-vibration$tl$ and t.grade_level = 1);

-- science: Signals: Light & Sound
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Signals: Light & Sound", "body": "People use light and sound, like sirens and flashing lights, to send messages far away."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  People can send a message far away using:\n\nThe answer is \"light or sound signals\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A flashing light on a fire truck is used to:\n\nThe answer is \"send a warning signal\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A loud siren warns people to:\n\nThe answer is \"get out of the way\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A ringing school bell tells students it is time to:", "choices": [{"id": "a", "label": "change class or line up"}, {"id": "b", "label": "go swimming"}, {"id": "c", "label": "take a nap forever"}, {"id": "d", "label": "plant a tree"}], "answer": "a", "explanation": "Yes! The answer is \"change class or line up\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Sailors and campers can signal far away with a:", "choices": [{"id": "a", "label": "soft pillow"}, {"id": "b", "label": "bright flashlight"}, {"id": "c", "label": "cup of soup"}, {"id": "d", "label": "wet sponge"}], "answer": "b", "explanation": "Yes! The answer is \"bright flashlight\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A car horn (beep) is a sound used to:", "choices": [{"id": "a", "label": "clean the car"}, {"id": "b", "label": "get someone's attention"}, {"id": "c", "label": "cool the engine"}, {"id": "d", "label": "paint the road"}], "answer": "b", "explanation": "Yes! The answer is \"get someone's attention\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Signals: Light & Sound! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$communicating-with-light-and-sound$tl$ and t.grade_level = 1);

-- science: Plant Parts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plant Parts", "body": "Plants have roots, a stem, leaves, and flowers, and each part has a special job."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which plant part takes in water from the soil?\n\nThe answer is \"roots\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which plant part makes food using sunlight?\n\nThe answer is \"leaves\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which part holds the plant up and carries water?\n\nThe answer is \"the stem\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which plant part often becomes a fruit with seeds?", "choices": [{"id": "a", "label": "the flower"}, {"id": "b", "label": "the root"}, {"id": "c", "label": "the stem"}, {"id": "d", "label": "the leaf"}], "answer": "a", "explanation": "Yes! The answer is \"the flower\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which part of a carrot plant do we usually eat?", "choices": [{"id": "a", "label": "the flower"}, {"id": "b", "label": "the leaf"}, {"id": "c", "label": "the root"}, {"id": "d", "label": "the seed"}], "answer": "c", "explanation": "Yes! The answer is \"the root\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Most plants need water, air, and ____ to grow.", "choices": [{"id": "a", "label": "sunlight"}, {"id": "b", "label": "candy"}, {"id": "c", "label": "toys"}, {"id": "d", "label": "darkness"}], "answer": "a", "explanation": "Yes! The answer is \"sunlight\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plant Parts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$plant-parts$tl$ and t.grade_level = 1);

-- science: Animal Body Parts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Animal Body Parts", "body": "Animals have body parts like eyes, ears, legs, and wings that help them live."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which body part do animals use to see?\n\nThe answer is \"eyes\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An animal uses its ears to:\n\nThe answer is \"hear\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Sharp claws and teeth help an animal to:\n\nThe answer is \"catch and eat food\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Fur or feathers help an animal to:", "choices": [{"id": "a", "label": "run faster only"}, {"id": "b", "label": "taste food"}, {"id": "c", "label": "stay warm"}, {"id": "d", "label": "hear"}], "answer": "c", "explanation": "Yes! The answer is \"stay warm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A fish uses its fins to:", "choices": [{"id": "a", "label": "swim"}, {"id": "b", "label": "fly"}, {"id": "c", "label": "dig"}, {"id": "d", "label": "hear"}], "answer": "a", "explanation": "Yes! The answer is \"swim\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A bird uses its wings to:", "choices": [{"id": "a", "label": "dig tunnels"}, {"id": "b", "label": "fly"}, {"id": "c", "label": "swim deep"}, {"id": "d", "label": "chew"}], "answer": "b", "explanation": "Yes! The answer is \"fly\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Animal Body Parts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$animal-parts$tl$ and t.grade_level = 1);

-- science: Parents & Babies
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Parents & Babies", "body": "Baby animals look a lot like their parents and need them for food and safety."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Baby animals usually look like their:\n\nThe answer is \"parents\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A baby dog is called a:\n\nThe answer is \"puppy\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A baby cat is called a:\n\nThe answer is \"kitten\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A baby cow is called a:", "choices": [{"id": "a", "label": "puppy"}, {"id": "b", "label": "chick"}, {"id": "c", "label": "calf"}, {"id": "d", "label": "kitten"}], "answer": "c", "explanation": "Yes! The answer is \"calf\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A baby chicken is called a:", "choices": [{"id": "a", "label": "puppy"}, {"id": "b", "label": "calf"}, {"id": "c", "label": "chick"}, {"id": "d", "label": "cub"}], "answer": "c", "explanation": "Yes! The answer is \"chick\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Many baby animals need their parents for:", "choices": [{"id": "a", "label": "homework"}, {"id": "b", "label": "food and safety"}, {"id": "c", "label": "money"}, {"id": "d", "label": "cars"}], "answer": "b", "explanation": "Yes! The answer is \"food and safety\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Parents & Babies! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$animal-parents-and-babies$tl$ and t.grade_level = 1);

-- science: How Animals Survive
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: How Animals Survive", "body": "Animals need food, water, air, and shelter, and they have ways to stay safe."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Animals need food, water, air, and ____ to live.\n\nThe answer is \"shelter (a safe place)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A bird builds a nest to:\n\nThe answer is \"keep its eggs and babies safe\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Many animals hide or use camouflage to:\n\nThe answer is \"stay safe from predators\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In winter, some animals grow thicker fur to:", "choices": [{"id": "a", "label": "stay warm"}, {"id": "b", "label": "swim faster"}, {"id": "c", "label": "fly"}, {"id": "d", "label": "sing"}], "answer": "a", "explanation": "Yes! The answer is \"stay warm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Bees and ants live together in groups to help each other:", "choices": [{"id": "a", "label": "survive"}, {"id": "b", "label": "watch TV"}, {"id": "c", "label": "play tag"}, {"id": "d", "label": "sleep all year"}], "answer": "a", "explanation": "Yes! The answer is \"survive\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A turtle hides in its shell when it feels:", "choices": [{"id": "a", "label": "happy"}, {"id": "b", "label": "hungry only"}, {"id": "c", "label": "scared or in danger"}, {"id": "d", "label": "sleepy"}], "answer": "c", "explanation": "Yes! The answer is \"scared or in danger\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about How Animals Survive! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$how-animals-survive$tl$ and t.grade_level = 1);

-- science: Day & Night Sky
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Day & Night Sky", "body": "In the day we see the Sun; at night we see the Moon and stars, in a daily pattern."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which do we see in the sky during the DAY?\n\nThe answer is \"the Sun\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which do we usually see in the sky at NIGHT?\n\nThe answer is \"the Moon and stars\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The Sun gives Earth:\n\nThe answer is \"light and warmth\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Stars look tiny because they are:", "choices": [{"id": "a", "label": "very small rocks"}, {"id": "b", "label": "made of paper"}, {"id": "c", "label": "very far away"}, {"id": "d", "label": "close to us"}], "answer": "c", "explanation": "Yes! The answer is \"very far away\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Day and night happen in a:", "choices": [{"id": "a", "label": "repeating pattern"}, {"id": "b", "label": "random way"}, {"id": "c", "label": "one-time event"}, {"id": "d", "label": "sound"}], "answer": "a", "explanation": "Yes! The answer is \"repeating pattern\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When it is daytime, the sky is usually:", "choices": [{"id": "a", "label": "dark"}, {"id": "b", "label": "full of stars"}, {"id": "c", "label": "bright"}, {"id": "d", "label": "green"}], "answer": "c", "explanation": "Yes! The answer is \"bright\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Day & Night Sky! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$day-and-night-sky$tl$ and t.grade_level = 1);

-- science: Sun & Seasons
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sun & Seasons", "body": "The seasons change in a pattern, with more daylight in summer and less in winter."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which season is usually the coldest?\n\nThe answer is \"winter\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which season is usually the hottest?\n\nThe answer is \"summer\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  In which season do many flowers bloom and trees grow new leaves?\n\nThe answer is \"spring\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In which season do leaves often turn colors and fall?", "choices": [{"id": "a", "label": "spring"}, {"id": "b", "label": "fall (autumn)"}, {"id": "c", "label": "summer"}, {"id": "d", "label": "winter"}], "answer": "b", "explanation": "Yes! The answer is \"fall (autumn)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In summer there are more hours of:", "choices": [{"id": "a", "label": "daylight"}, {"id": "b", "label": "darkness"}, {"id": "c", "label": "snow"}, {"id": "d", "label": "rain only"}], "answer": "a", "explanation": "Yes! The answer is \"daylight\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In winter there are fewer hours of:", "choices": [{"id": "a", "label": "daylight"}, {"id": "b", "label": "nighttime"}, {"id": "c", "label": "wind"}, {"id": "d", "label": "clouds"}], "answer": "a", "explanation": "Yes! The answer is \"daylight\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sun & Seasons! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$sun-and-seasons$tl$ and t.grade_level = 1);

-- science: Weather
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Weather", "body": "Weather can be sunny, rainy, snowy, windy, or stormy, and it can change day to day."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the weather like on a sunny day?\n\nThe answer is \"bright and clear\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which tool measures how hot or cold it is?\n\nThe answer is \"a thermometer\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Rain, snow, and hail all fall from:\n\nThe answer is \"clouds\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "On a windy day, you might see leaves and flags:", "choices": [{"id": "a", "label": "frozen still"}, {"id": "b", "label": "melting"}, {"id": "c", "label": "glowing"}, {"id": "d", "label": "moving"}], "answer": "d", "explanation": "Yes! The answer is \"moving\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which weather would make you wear a raincoat?", "choices": [{"id": "a", "label": "sunny"}, {"id": "b", "label": "calm"}, {"id": "c", "label": "clear"}, {"id": "d", "label": "rainy"}], "answer": "d", "explanation": "Yes! The answer is \"rainy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Snow falls when the weather is very:", "choices": [{"id": "a", "label": "cold"}, {"id": "b", "label": "hot"}, {"id": "c", "label": "windy only"}, {"id": "d", "label": "sunny"}], "answer": "a", "explanation": "Yes! The answer is \"cold\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Weather! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$weather-patterns$tl$ and t.grade_level = 1);

-- reading: Main Topic
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Main Topic", "body": "The main topic is what a story or text is mostly about."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"My dog can run, jump, and catch a ball.\" This is mostly about:\n\nThe answer is \"what my dog can do\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Bees make honey. They visit many flowers.\" This is mostly about:\n\nThe answer is \"bees\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"I like to swim. The water is cool and fun.\" This is mostly about:\n\nThe answer is \"swimming\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The sun is hot. It gives us light in the day.\" This is mostly about:", "choices": [{"id": "a", "label": "the sun"}, {"id": "b", "label": "the moon"}, {"id": "c", "label": "a cat"}, {"id": "d", "label": "a hat"}], "answer": "a", "explanation": "Yes! The answer is \"the sun\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"We planted seeds. We water them every day.\" This is mostly about:", "choices": [{"id": "a", "label": "a car ride"}, {"id": "b", "label": "growing plants"}, {"id": "c", "label": "a party"}, {"id": "d", "label": "the beach"}], "answer": "b", "explanation": "Yes! The answer is \"growing plants\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Cats like to nap. They sleep a lot in the day.\" This is mostly about:", "choices": [{"id": "a", "label": "dogs running"}, {"id": "b", "label": "a big city"}, {"id": "c", "label": "cats sleeping"}, {"id": "d", "label": "a boat"}], "answer": "c", "explanation": "Yes! The answer is \"cats sleeping\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Main Topic! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$main-topic$tl$ and t.grade_level = 1);

-- reading: Key Details
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Key Details", "body": "Key details are the small facts in a text that answer who, what, and where."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Sam has a blue kite.\" What color is the kite?\n\nThe answer is \"blue\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"The cat sat on the soft mat.\" Where did the cat sit?\n\nThe answer is \"on the mat\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"We had grapes for snack.\" What did we eat?\n\nThe answer is \"grapes\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Mia ran fast to the bus.\" How did Mia move?", "choices": [{"id": "a", "label": "slowly"}, {"id": "b", "label": "fast"}, {"id": "c", "label": "backward"}, {"id": "d", "label": "by flying"}], "answer": "b", "explanation": "Yes! The answer is \"fast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Dad read three books.\" How many books?", "choices": [{"id": "a", "label": "three"}, {"id": "b", "label": "one"}, {"id": "c", "label": "five"}, {"id": "d", "label": "ten"}], "answer": "a", "explanation": "Yes! The answer is \"three\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The dog hid under the bed.\" Where did the dog hide?", "choices": [{"id": "a", "label": "in a tree"}, {"id": "b", "label": "on the roof"}, {"id": "c", "label": "in a box"}, {"id": "d", "label": "under the bed"}], "answer": "d", "explanation": "Yes! The answer is \"under the bed\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Key Details! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$key-details$tl$ and t.grade_level = 1);

-- reading: Retelling & Order
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Retelling & Order", "body": "Retelling means saying what happened first, next, and last, in order."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"First Ana woke up. Then she ate. Last she went to school.\" What did Ana do FIRST?\n\nThe answer is \"woke up\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"The seed grew. Then it had leaves. Last it bloomed.\" What happened LAST?\n\nThe answer is \"it bloomed\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"We packed a bag. Then we drove. Last we played.\" What happened SECOND?\n\nThe answer is \"we drove\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"He woke up, brushed his teeth, then ate.\" What did he do right BEFORE eating?", "choices": [{"id": "a", "label": "went to bed"}, {"id": "b", "label": "ran outside"}, {"id": "c", "label": "read a book"}, {"id": "d", "label": "brushed his teeth"}], "answer": "d", "explanation": "Yes! The answer is \"brushed his teeth\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"First it rained. Then the sun came out. Last we saw a rainbow.\" What came FIRST?", "choices": [{"id": "a", "label": "the rainbow"}, {"id": "b", "label": "it rained"}, {"id": "c", "label": "the sun set"}, {"id": "d", "label": "the snow"}], "answer": "b", "explanation": "Yes! The answer is \"it rained\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Mia drew a cat, colored it, and hung it up.\" What did Mia do LAST?", "choices": [{"id": "a", "label": "hung it up"}, {"id": "b", "label": "drew a cat"}, {"id": "c", "label": "colored it"}, {"id": "d", "label": "erased it"}], "answer": "a", "explanation": "Yes! The answer is \"hung it up\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Retelling & Order! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$retelling-stories$tl$ and t.grade_level = 1);

-- reading: Characters
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Characters", "body": "Characters are the people or animals a story is about."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Kind Mia helped the lost puppy.\" Who is the character?\n\nThe answer is \"Mia\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Brave Leo climbed the tall hill.\" What word describes Leo?\n\nThe answer is \"brave\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Grumpy Mr. Fox frowned all day.\" How does Mr. Fox feel?\n\nThe answer is \"grumpy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Happy Ana danced and smiled.\" How does Ana feel?", "choices": [{"id": "a", "label": "happy"}, {"id": "b", "label": "sad"}, {"id": "c", "label": "angry"}, {"id": "d", "label": "scared"}], "answer": "a", "explanation": "Yes! The answer is \"happy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The puppy named Bo wagged his tail.\" Who is the character?", "choices": [{"id": "a", "label": "a tree"}, {"id": "b", "label": "the sky"}, {"id": "c", "label": "a rock"}, {"id": "d", "label": "Bo the puppy"}], "answer": "d", "explanation": "Yes! The answer is \"Bo the puppy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Shy Sam hid behind his mom.\" What word describes Sam?", "choices": [{"id": "a", "label": "loud"}, {"id": "b", "label": "brave"}, {"id": "c", "label": "shy"}, {"id": "d", "label": "silly"}], "answer": "c", "explanation": "Yes! The answer is \"shy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Characters! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$characters$tl$ and t.grade_level = 1);

-- reading: Setting
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Setting", "body": "The setting is where and when a story takes place."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"At the beach, we built a sandcastle.\" Where does this happen?\n\nThe answer is \"at the beach\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"In the forest, the deer ran by.\" Where does this happen?\n\nThe answer is \"in the forest\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"It was snowy in the village.\" What is the setting?\n\nThe answer is \"a snowy village\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"At school, we read and write.\" Where does this happen?", "choices": [{"id": "a", "label": "at the zoo"}, {"id": "b", "label": "at school"}, {"id": "c", "label": "on a boat"}, {"id": "d", "label": "in space"}], "answer": "b", "explanation": "Yes! The answer is \"at school\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"On the farm, the rooster crowed.\" Where does this happen?", "choices": [{"id": "a", "label": "in a city"}, {"id": "b", "label": "in the sea"}, {"id": "c", "label": "on the moon"}, {"id": "d", "label": "on the farm"}], "answer": "d", "explanation": "Yes! The answer is \"on the farm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"In the kitchen, Mom made soup.\" Where does this happen?", "choices": [{"id": "a", "label": "in the car"}, {"id": "b", "label": "at the park"}, {"id": "c", "label": "in the kitchen"}, {"id": "d", "label": "in a boat"}], "answer": "c", "explanation": "Yes! The answer is \"in the kitchen\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Setting! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$setting$tl$ and t.grade_level = 1);

-- reading: Rhyming Words
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Rhyming Words", "body": "Rhyming words sound the same at the end, like cat and hat."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word rhymes with CAT?\n\nThe answer is \"hat\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word rhymes with DOG?\n\nThe answer is \"log\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word rhymes with SUN?\n\nThe answer is \"run\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with BEE?", "choices": [{"id": "a", "label": "book"}, {"id": "b", "label": "tree"}, {"id": "c", "label": "ball"}, {"id": "d", "label": "cup"}], "answer": "b", "explanation": "Yes! The answer is \"tree\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with CAR?", "choices": [{"id": "a", "label": "sun"}, {"id": "b", "label": "dog"}, {"id": "c", "label": "hat"}, {"id": "d", "label": "star"}], "answer": "d", "explanation": "Yes! The answer is \"star\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with CAKE?", "choices": [{"id": "a", "label": "lake"}, {"id": "b", "label": "milk"}, {"id": "c", "label": "ball"}, {"id": "d", "label": "top"}], "answer": "a", "explanation": "Yes! The answer is \"lake\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Rhyming Words! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$rhyming-words$tl$ and t.grade_level = 1);

-- reading: Sight Words
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sight Words", "body": "Sight words are common words we learn to read quickly, like the and you."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is 'the'?\n\nThe answer is \"the\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is 'and'?\n\nThe answer is \"and\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is 'you'?\n\nThe answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'said'?", "choices": [{"id": "a", "label": "see"}, {"id": "b", "label": "said"}, {"id": "c", "label": "go"}, {"id": "d", "label": "my"}], "answer": "b", "explanation": "Yes! The answer is \"said\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'have'?", "choices": [{"id": "a", "label": "have"}, {"id": "b", "label": "here"}, {"id": "c", "label": "this"}, {"id": "d", "label": "that"}], "answer": "a", "explanation": "Yes! The answer is \"have\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'they'?", "choices": [{"id": "a", "label": "then"}, {"id": "b", "label": "them"}, {"id": "c", "label": "there"}, {"id": "d", "label": "they"}], "answer": "d", "explanation": "Yes! The answer is \"they\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sight Words! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$sight-words$tl$ and t.grade_level = 1);

-- reading: Opposites
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Opposites", "body": "Opposites are words that mean very different things, like big and small."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the opposite of BIG?\n\nThe answer is \"small\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the opposite of HOT?\n\nThe answer is \"cold\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the opposite of UP?\n\nThe answer is \"down\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of DAY?", "choices": [{"id": "a", "label": "noon"}, {"id": "b", "label": "sun"}, {"id": "c", "label": "night"}, {"id": "d", "label": "sky"}], "answer": "c", "explanation": "Yes! The answer is \"night\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of HAPPY?", "choices": [{"id": "a", "label": "glad"}, {"id": "b", "label": "sad"}, {"id": "c", "label": "silly"}, {"id": "d", "label": "kind"}], "answer": "b", "explanation": "Yes! The answer is \"sad\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of FAST?", "choices": [{"id": "a", "label": "quick"}, {"id": "b", "label": "tall"}, {"id": "c", "label": "big"}, {"id": "d", "label": "slow"}], "answer": "d", "explanation": "Yes! The answer is \"slow\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Opposites! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$opposites$tl$ and t.grade_level = 1);

-- reading: Word Meaning
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Word Meaning", "body": "Use the other words in a sentence to figure out what a word means."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The tiny ant was so small I could hardly see it.\" What does \"tiny\" mean?\n\nThe answer is \"very small\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"I was so tired I fell asleep right away.\" What does \"tired\" mean?\n\nThe answer is \"sleepy\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The soup was hot, so I let it cool.\" What does \"hot\" mean here?\n\nThe answer is \"very warm\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The huge dog was bigger than me!\" What does \"huge\" mean?", "choices": [{"id": "a", "label": "very small"}, {"id": "b", "label": "very quiet"}, {"id": "c", "label": "very fast"}, {"id": "d", "label": "very big"}], "answer": "d", "explanation": "Yes! The answer is \"very big\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"It was quiet; no one made a sound.\" What does \"quiet\" mean?", "choices": [{"id": "a", "label": "very loud"}, {"id": "b", "label": "very bright"}, {"id": "c", "label": "very cold"}, {"id": "d", "label": "no sound"}], "answer": "d", "explanation": "Yes! The answer is \"no sound\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The happy baby giggled and smiled.\" What does \"happy\" mean?", "choices": [{"id": "a", "label": "sad"}, {"id": "b", "label": "angry"}, {"id": "c", "label": "glad"}, {"id": "d", "label": "sleepy"}], "answer": "c", "explanation": "Yes! The answer is \"glad\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Word Meaning! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$context-clues$tl$ and t.grade_level = 1);

-- reading: Cause & Effect
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Cause & Effect", "body": "A cause is why something happens; the effect is what happens."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"It rained, so we went inside.\" Why did they go inside?\n\nThe answer is \"because it rained\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Sam dropped the cup, so it broke.\" What happened to the cup?\n\nThe answer is \"it broke\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The dog was hungry, so it barked at its bowl.\" Why did the dog bark?\n\nThe answer is \"it was hungry\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She watered the plant, so it grew.\" Why did the plant grow?", "choices": [{"id": "a", "label": "she watered it"}, {"id": "b", "label": "it was dark"}, {"id": "c", "label": "it was cold"}, {"id": "d", "label": "nobody touched it"}], "answer": "a", "explanation": "Yes! The answer is \"she watered it\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The ice got hot, so it melted.\" Why did the ice melt?", "choices": [{"id": "a", "label": "it got cold"}, {"id": "b", "label": "it was night"}, {"id": "c", "label": "it was tiny"}, {"id": "d", "label": "it got hot"}], "answer": "d", "explanation": "Yes! The answer is \"it got hot\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Ben was sleepy, so he went to bed.\" Why did Ben go to bed?", "choices": [{"id": "a", "label": "he was sleepy"}, {"id": "b", "label": "he was hungry"}, {"id": "c", "label": "he was happy"}, {"id": "d", "label": "it was morning"}], "answer": "a", "explanation": "Yes! The answer is \"he was sleepy\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Cause & Effect! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$cause-and-effect$tl$ and t.grade_level = 1);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, or thing."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"island\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"farmer\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"village\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "march"}, {"id": "b", "label": "forest"}, {"id": "c", "label": "shiny"}, {"id": "d", "label": "wander"}], "answer": "b", "explanation": "Yes! The answer is \"forest\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "library"}, {"id": "b", "label": "gallop"}, {"id": "c", "label": "ancient"}, {"id": "d", "label": "gentle"}], "answer": "a", "explanation": "Yes! The answer is \"library\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "garden"}, {"id": "b", "label": "jump"}, {"id": "c", "label": "tiny"}, {"id": "d", "label": "stretch"}], "answer": "a", "explanation": "Yes! The answer is \"garden\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 1);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb is an action word that tells what someone does."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"paint\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"build\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"scribble\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "frozen"}, {"id": "b", "label": "shiny"}, {"id": "c", "label": "blanket"}, {"id": "d", "label": "march"}], "answer": "d", "explanation": "Yes! The answer is \"march\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "river"}, {"id": "b", "label": "swim"}, {"id": "c", "label": "stormy"}, {"id": "d", "label": "fluffy"}], "answer": "b", "explanation": "Yes! The answer is \"swim\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "island"}, {"id": "b", "label": "frozen"}, {"id": "c", "label": "explore"}, {"id": "d", "label": "curious"}], "answer": "c", "explanation": "Yes! The answer is \"explore\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 1);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun, like big, red, or soft."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"frozen\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"ancient\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"curious\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "wander"}, {"id": "b", "label": "farmer"}, {"id": "c", "label": "blanket"}, {"id": "d", "label": "fluffy"}], "answer": "d", "explanation": "Yes! The answer is \"fluffy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "jump"}, {"id": "b", "label": "slippery"}, {"id": "c", "label": "sister"}, {"id": "d", "label": "paint"}], "answer": "b", "explanation": "Yes! The answer is \"slippery\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "bounce"}, {"id": "b", "label": "jump"}, {"id": "c", "label": "swim"}, {"id": "d", "label": "enormous"}], "answer": "d", "explanation": "Yes! The answer is \"enormous\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 1);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun, like he, she, it, or they."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"we\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"I\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "swim"}, {"id": "b", "label": "whisper"}, {"id": "c", "label": "village"}, {"id": "d", "label": "us"}], "answer": "d", "explanation": "Yes! The answer is \"us\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "she"}, {"id": "b", "label": "library"}, {"id": "c", "label": "wander"}, {"id": "d", "label": "gallop"}], "answer": "a", "explanation": "Yes! The answer is \"she\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "doctor"}, {"id": "b", "label": "sister"}, {"id": "c", "label": "him"}, {"id": "d", "label": "engine"}], "answer": "c", "explanation": "Yes! The answer is \"him\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 1);

-- writing: Matching Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Matching Verbs", "body": "The verb must match the subject, like 'The dog runs.'"}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The singer ____ every day.\"\n\nThe answer is \"performs\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The engine ____ every day.\"\n\nThe answer is \"roars\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The artist ____ every day.\"\n\nThe answer is \"paints\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The kettle ____ every day.\"", "choices": [{"id": "a", "label": "whistle"}, {"id": "b", "label": "whistles"}, {"id": "c", "label": "whistlesed"}, {"id": "d", "label": "whistlesing"}], "answer": "b", "explanation": "Yes! The answer is \"whistles\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The clock ____ every day.\"", "choices": [{"id": "a", "label": "tick"}, {"id": "b", "label": "ticks"}, {"id": "c", "label": "ticksed"}, {"id": "d", "label": "ticksing"}], "answer": "b", "explanation": "Yes! The answer is \"ticks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The river ____ every day.\"", "choices": [{"id": "a", "label": "flow"}, {"id": "b", "label": "flowsed"}, {"id": "c", "label": "flows"}, {"id": "d", "label": "flowsing"}], "answer": "c", "explanation": "Yes! The answer is \"flows\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Matching Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 1);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs tell about something that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"run\"?\n\nThe answer is \"ran\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"eat\"?\n\nThe answer is \"ate\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"catch\"?\n\nThe answer is \"caught\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"give\"?\n\nThe answer is gave."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"throw\"?\n\nThe answer is threw."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"ride\"?\n\nThe answer is rode."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 1);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals mean more than one. Add -s or -es to most nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"brush\".\n\nThe answer is \"brushes\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"knife\".\n\nThe answer is \"knives\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"leaf\".\n\nThe answer is \"leaves\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"lady\".\n\nThe answer is ladies."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"fairy\".\n\nThe answer is fairies."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"wish\".\n\nThe answer is wishes."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 1);

-- writing: Capital Letters
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capital Letters", "body": "Start sentences and names with a capital (big) letter."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"New York\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Friday\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"October\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "month"}, {"id": "c", "label": "Tokyo"}, {"id": "d", "label": "river"}], "answer": "c", "explanation": "Yes! The answer is \"Tokyo\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "friend"}, {"id": "b", "label": "month"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "London"}], "answer": "d", "explanation": "Yes! The answer is \"London\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "month"}, {"id": "b", "label": "ocean"}, {"id": "c", "label": "friend"}, {"id": "d", "label": "Maria"}], "answer": "d", "explanation": "Yes! The answer is \"Maria\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capital Letters! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 1);

-- writing: End Marks
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Marks", "body": "End a sentence with a period, a question mark, or an exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"I love to read___\"\n\nThe answer is \".\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"How does it work___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"Where are we going___\"\n\nThe answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"When does it start___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "!"}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "c", "explanation": "Yes! The answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"The cake is delicious___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "."}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "b", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"What time is it___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "."}, {"id": "c", "label": "!"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"?\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Marks! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 1);

-- writing: Commas in a List
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a List", "body": "Use commas to separate three or more things in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like pencils, pens, and markers.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like cats, dogs, and fish.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like rain, snow, and hail.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like north south and east."}, {"id": "b", "label": "I like north, south and east"}, {"id": "c", "label": "I like, north south east."}, {"id": "d", "label": "I like north, south, and east."}], "answer": "d", "explanation": "Yes! The answer is \"I like north, south, and east.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like apples oranges and pears."}, {"id": "b", "label": "I like apples, oranges and pears"}, {"id": "c", "label": "I like apples, oranges, and pears."}, {"id": "d", "label": "I like, apples oranges pears."}], "answer": "c", "explanation": "Yes! The answer is \"I like apples, oranges, and pears.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like walk skip and hop."}, {"id": "b", "label": "I like walk, skip, and hop."}, {"id": "c", "label": "I like walk, skip and hop"}, {"id": "d", "label": "I like, walk skip hop."}], "answer": "b", "explanation": "Yes! The answer is \"I like walk, skip, and hop.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a List! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 1);

