-- =====================================================================
-- TopicLeap - richer lessons for Grade 6 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Ratios
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Ratios", "body": "A ratio compares two quantities. Worksheets use larger numbers as they go."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  There are 7 cats and 8 dogs. Write the ratio of cats to dogs (use a colon, like 3:4).\n\nThe answer is \"7:8\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  There are 2 red and 10 blue. Write the ratio of red to blue (use a colon, like 3:4).\n\nThe answer is \"2:10\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  There are 6 wins and 8 losses. Write the ratio of wins to losses (use a colon, like 3:4).\n\nThe answer is \"6:8\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  There are 10 boys and 4 girls. Write the ratio of boys to girls (use a colon, like 3:4).\n\nThe answer is 10:4."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  There are 11 wins and 17 losses. Write the ratio of wins to losses (use a colon, like 3:4).\n\nThe answer is 11:17."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  There are 15 apples and 15 oranges. Write the ratio of apples to oranges (use a colon, like 3:4).\n\nThe answer is 15:15."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Ratios! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$ratios$tl$ and t.grade_level = 6);

-- math: Unit Rates
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Unit Rates", "body": "A unit rate tells how much of one quantity per one of another, like miles per hour."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A car travels 24 miles in 3 hours at a steady speed. How many miles per hour is that?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A car travels 4 miles in 2 hours at a steady speed. How many miles per hour is that?\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A car travels 27 miles in 3 hours at a steady speed. How many miles per hour is that?\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A car travels 76 miles in 4 hours at a steady speed. How many miles per hour is that?\n\nThe answer is 19."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A car travels 51 miles in 3 hours at a steady speed. How many miles per hour is that?\n\nThe answer is 17."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A car travels 48 miles in 4 hours at a steady speed. How many miles per hour is that?\n\nThe answer is 12."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Unit Rates! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$unit-rates$tl$ and t.grade_level = 6);

-- math: Percents
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Percents", "body": "A percent is a part out of 100. To find a percent of a number, multiply and divide by 100."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is 10% of 100?\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is 25% of 300?\n\nThe answer is \"75\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is 10% of 300?\n\nThe answer is \"30\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is 50% of 600?\n\nThe answer is 300."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is 75% of 200?\n\nThe answer is 150."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is 20% of 400?\n\nThe answer is 80."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Percents! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$percent$tl$ and t.grade_level = 6);

-- math: Dividing Fractions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Dividing Fractions", "body": "To divide by a fraction, multiply by its reciprocal (flip the second fraction)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  2/3 / 1/3 = ?  (divide the fractions)\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  1/4 / 2/3 = ?  (divide the fractions)\n\nThe answer is \"3/8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  1/3 / 1/3 = ?  (divide the fractions)\n\nThe answer is \"1\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "2/4 / 1/2 = ?  (divide the fractions)", "choices": [{"id": "a", "label": "1/4"}, {"id": "b", "label": "2"}, {"id": "c", "label": "4/5"}, {"id": "d", "label": "1"}], "answer": "d", "explanation": "Yes! The answer is \"1\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/2 / 1/2 = ?  (divide the fractions)", "choices": [{"id": "a", "label": "2/3"}, {"id": "b", "label": "1"}, {"id": "c", "label": "3/3"}, {"id": "d", "label": "1/4"}], "answer": "b", "explanation": "Yes! The answer is \"1\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/3 / 1/5 = ?  (divide the fractions)", "choices": [{"id": "a", "label": "5/3"}, {"id": "b", "label": "1/15"}, {"id": "c", "label": "6/4"}, {"id": "d", "label": "5/4"}], "answer": "a", "explanation": "Yes! The answer is \"5/3\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Dividing Fractions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$divide-fractions$tl$ and t.grade_level = 6);

-- math: Decimal Operations
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Decimal Operations", "body": "Add, subtract, and multiply decimals carefully, keeping track of the decimal point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  0.7 + 0.9 = ?\n\nThe answer is \"1.6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  3.4 + 0.5 = ?\n\nThe answer is \"3.9\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  2 - 0.4 = ?\n\nThe answer is \"1.6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1.4 - 0.9 = ?", "choices": [{"id": "a", "label": "0.5"}, {"id": "b", "label": "5"}, {"id": "c", "label": "0.4"}, {"id": "d", "label": "0.6"}], "answer": "a", "explanation": "Yes! The answer is \"0.5\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "0.5 - 0.2 = ?", "choices": [{"id": "a", "label": "0.5"}, {"id": "b", "label": "0.3"}, {"id": "c", "label": "0.4"}, {"id": "d", "label": "0.2"}], "answer": "b", "explanation": "Yes! The answer is \"0.3\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "3.4 + 0.7 = ?", "choices": [{"id": "a", "label": "4"}, {"id": "b", "label": "4.2"}, {"id": "c", "label": "4.1"}, {"id": "d", "label": "41"}], "answer": "c", "explanation": "Yes! The answer is \"4.1\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Decimal Operations! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$decimal-operations$tl$ and t.grade_level = 6);

-- math: GCF & LCM
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: GCF & LCM", "body": "The GCF is the biggest factor two numbers share; the LCM is the smallest multiple they share."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the LCM (least common multiple) of 4 and 5?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the LCM (least common multiple) of 10 and 11?\n\nThe answer is \"110\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the LCM (least common multiple) of 2 and 6?\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the GCF (greatest common factor) of 9 and 16?\n\nThe answer is 1."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the GCF (greatest common factor) of 10 and 20?\n\nThe answer is 10."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the LCM (least common multiple) of 4 and 13?\n\nThe answer is 52."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about GCF & LCM! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$gcf-lcm$tl$ and t.grade_level = 6);

-- math: Integers & Absolute Value
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Integers & Absolute Value", "body": "Integers include negative numbers; absolute value is a number's distance from zero."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the absolute value |-2| ?\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the absolute value |-8| ?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the absolute value |-9| ?\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the absolute value |-5| ?\n\nThe answer is 5."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the absolute value |-14| ?\n\nThe answer is 14."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is 18 - 17 - 17 ?\n\nThe answer is -16."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Integers & Absolute Value! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$integers$tl$ and t.grade_level = 6);

-- math: Exponents
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Exponents", "body": "An exponent tells how many times to multiply a base by itself, like 2^3 = 8."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is 6^2 (that is 6 to the power 2)?\n\nThe answer is \"36\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is 7^2 (that is 7 to the power 2)?\n\nThe answer is \"49\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is 5^2 (that is 5 to the power 2)?\n\nThe answer is \"25\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is 12^2 (that is 12 to the power 2)?\n\nThe answer is 144."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is 9^2 (that is 9 to the power 2)?\n\nThe answer is 81."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is 11^2 (that is 11 to the power 2)?\n\nThe answer is 121."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Exponents! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$exponents$tl$ and t.grade_level = 6);

-- math: Evaluating Expressions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Evaluating Expressions", "body": "Substitute the given value for the variable, then follow the order of operations."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Evaluate 4x + 7 when x = 7.\n\nThe answer is \"35\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Evaluate 4x + 7 when x = 5.\n\nThe answer is \"27\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Evaluate 5x + 3 when x = 9.\n\nThe answer is \"48\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Evaluate 4x - 9 when x = 10.\n\nThe answer is 31."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Evaluate 7x - 3 when x = 10.\n\nThe answer is 67."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Evaluate 6x - 5 when x = 4.\n\nThe answer is 19."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Evaluating Expressions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$evaluate-expressions$tl$ and t.grade_level = 6);

-- math: One-Step Equations
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: One-Step Equations", "body": "Use the inverse operation to get the variable by itself and solve."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Solve for x:  x + 4 = 17\n\nThe answer is \"13\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Solve for x:  x + 12 = 17\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Solve for x:  x + 7 = 17\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Solve for x:  x - 5 = 12\n\nThe answer is 17."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Solve for x:  x - 14 = -11\n\nThe answer is 3."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Solve for x:  x - 18 = 0\n\nThe answer is 18."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about One-Step Equations! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$one-step-equations$tl$ and t.grade_level = 6);

-- science: Cells
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Cells", "body": "Cells are the basic building blocks of all living things; some have specialized parts."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The basic building block of all living things is the:\n\nThe answer is \"cell\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Living things made of many cells are called:\n\nThe answer is \"multicellular\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A living thing made of only one cell is:\n\nThe answer is \"unicellular\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The part of the cell that controls its activities is the:", "choices": [{"id": "a", "label": "nucleus"}, {"id": "b", "label": "cell wall"}, {"id": "c", "label": "vacuole"}, {"id": "d", "label": "ribosome"}], "answer": "a", "explanation": "Yes! The answer is \"nucleus\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Plant cells have a stiff outer layer that animal cells lack, the:", "choices": [{"id": "a", "label": "nucleus"}, {"id": "b", "label": "cytoplasm"}, {"id": "c", "label": "membrane"}, {"id": "d", "label": "cell wall"}], "answer": "d", "explanation": "Yes! The answer is \"cell wall\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The thin layer that controls what enters and leaves a cell is the:", "choices": [{"id": "a", "label": "cell wall"}, {"id": "b", "label": "nucleus"}, {"id": "c", "label": "cell membrane"}, {"id": "d", "label": "vacuole"}], "answer": "c", "explanation": "Yes! The answer is \"cell membrane\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Cells! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$cells$tl$ and t.grade_level = 6);

-- science: Body Systems
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Body Systems", "body": "The body's organ systems work together to keep an organism alive and healthy."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The system that pumps blood through the body is the:\n\nThe answer is \"circulatory system\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The system that breaks down food into nutrients is the:\n\nThe answer is \"digestive system\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The system that takes in oxygen and removes carbon dioxide is the:\n\nThe answer is \"respiratory system\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Bones that support and protect the body make up the:", "choices": [{"id": "a", "label": "muscular system"}, {"id": "b", "label": "skeletal system"}, {"id": "c", "label": "nervous system"}, {"id": "d", "label": "digestive system"}], "answer": "b", "explanation": "Yes! The answer is \"skeletal system\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Muscles that let the body move are part of the:", "choices": [{"id": "a", "label": "skeletal system"}, {"id": "b", "label": "muscular system"}, {"id": "c", "label": "nervous system"}, {"id": "d", "label": "circulatory system"}], "answer": "b", "explanation": "Yes! The answer is \"muscular system\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The brain, spinal cord, and nerves form the:", "choices": [{"id": "a", "label": "circulatory system"}, {"id": "b", "label": "digestive system"}, {"id": "c", "label": "respiratory system"}, {"id": "d", "label": "nervous system"}], "answer": "d", "explanation": "Yes! The answer is \"nervous system\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Body Systems! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$body-systems$tl$ and t.grade_level = 6);

-- science: Ecosystems & Energy
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Ecosystems & Energy", "body": "Energy flows and matter cycles through producers, consumers, and decomposers."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Energy enters most ecosystems from the:\n\nThe answer is \"Sun\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Organisms that make their own food are:\n\nThe answer is \"producers\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Organisms that eat other organisms are:\n\nThe answer is \"consumers\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Organisms that break down dead matter are:", "choices": [{"id": "a", "label": "producers"}, {"id": "b", "label": "decomposers"}, {"id": "c", "label": "predators"}, {"id": "d", "label": "herbivores"}], "answer": "b", "explanation": "Yes! The answer is \"decomposers\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In a food chain, arrows show the flow of:", "choices": [{"id": "a", "label": "energy"}, {"id": "b", "label": "water"}, {"id": "c", "label": "air"}, {"id": "d", "label": "money"}], "answer": "a", "explanation": "Yes! The answer is \"energy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "At each step of a food chain, most energy is lost as:", "choices": [{"id": "a", "label": "matter"}, {"id": "b", "label": "light"}, {"id": "c", "label": "heat"}, {"id": "d", "label": "sound"}], "answer": "c", "explanation": "Yes! The answer is \"heat\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Ecosystems & Energy! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$ecosystems-and-energy$tl$ and t.grade_level = 6);

-- science: Weather & Climate
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Weather & Climate", "body": "Weather is short-term; climate is long-term. Both depend on the atmosphere and oceans."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Weather is the condition of the atmosphere:\n\nThe answer is \"over a short time\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Climate is the typical weather of a place:\n\nThe answer is \"over many years\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Most weather happens in the lowest layer of the atmosphere, the:\n\nThe answer is \"troposphere\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Warm air tends to:", "choices": [{"id": "a", "label": "rise"}, {"id": "b", "label": "sink"}, {"id": "c", "label": "stay still"}, {"id": "d", "label": "freeze"}], "answer": "a", "explanation": "Yes! The answer is \"rise\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A large body of air with similar temperature and humidity is an:", "choices": [{"id": "a", "label": "ocean current"}, {"id": "b", "label": "mountain"}, {"id": "c", "label": "rock layer"}, {"id": "d", "label": "air mass"}], "answer": "d", "explanation": "Yes! The answer is \"air mass\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The boundary where two air masses meet is a:", "choices": [{"id": "a", "label": "coast"}, {"id": "b", "label": "front"}, {"id": "c", "label": "fault"}, {"id": "d", "label": "crater"}], "answer": "b", "explanation": "Yes! The answer is \"front\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Weather & Climate! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$weather-and-climate$tl$ and t.grade_level = 6);

-- science: Plate Tectonics
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plate Tectonics", "body": "Earth's plates move slowly, shaping continents and causing earthquakes and volcanoes."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Earth's outer shell is broken into large pieces called:\n\nThe answer is \"tectonic plates\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Tectonic plates float and move slowly on the:\n\nThe answer is \"mantle\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Where two plates pull apart, new crust can form. This is a:\n\nThe answer is \"divergent boundary\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Where two plates push together is a:", "choices": [{"id": "a", "label": "divergent boundary"}, {"id": "b", "label": "transform boundary"}, {"id": "c", "label": "valley"}, {"id": "d", "label": "convergent boundary"}], "answer": "d", "explanation": "Yes! The answer is \"convergent boundary\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Where two plates slide past each other is a:", "choices": [{"id": "a", "label": "divergent boundary"}, {"id": "b", "label": "transform boundary"}, {"id": "c", "label": "convergent boundary"}, {"id": "d", "label": "trench"}], "answer": "b", "explanation": "Yes! The answer is \"transform boundary\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Most earthquakes and volcanoes occur:", "choices": [{"id": "a", "label": "in the middle of plates only"}, {"id": "b", "label": "in the sky"}, {"id": "c", "label": "near plate boundaries"}, {"id": "d", "label": "underwater only"}], "answer": "c", "explanation": "Yes! The answer is \"near plate boundaries\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plate Tectonics! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$plate-tectonics$tl$ and t.grade_level = 6);

-- science: The Rock Cycle
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: The Rock Cycle", "body": "Rocks change between igneous, sedimentary, and metamorphic forms over time."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Rock formed from cooled magma or lava is:\n\nThe answer is \"igneous rock\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Rock formed from compacted layers of sediment is:\n\nThe answer is \"sedimentary rock\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Rock changed by heat and pressure is:\n\nThe answer is \"metamorphic rock\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Fossils are most commonly found in which rock type?", "choices": [{"id": "a", "label": "igneous"}, {"id": "b", "label": "metamorphic"}, {"id": "c", "label": "sedimentary"}, {"id": "d", "label": "molten"}], "answer": "c", "explanation": "Yes! The answer is \"sedimentary\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The breaking down of rock into smaller pieces is:", "choices": [{"id": "a", "label": "deposition"}, {"id": "b", "label": "melting"}, {"id": "c", "label": "cementing"}, {"id": "d", "label": "weathering"}], "answer": "d", "explanation": "Yes! The answer is \"weathering\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Wind and water moving sediment from place to place is:", "choices": [{"id": "a", "label": "weathering"}, {"id": "b", "label": "melting"}, {"id": "c", "label": "erosion"}, {"id": "d", "label": "cooling"}], "answer": "c", "explanation": "Yes! The answer is \"erosion\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about The Rock Cycle! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$rock-cycle$tl$ and t.grade_level = 6);

-- science: The Solar System
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: The Solar System", "body": "Gravity holds planets, moons, asteroids, and comets in orbit around the Sun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The Sun is at the center of our solar system and is a:\n\nThe answer is \"star\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The planets move around the Sun in paths called:\n\nThe answer is \"orbits\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which force keeps the planets in orbit around the Sun?\n\nThe answer is \"gravity\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The four inner planets are small and made mostly of:", "choices": [{"id": "a", "label": "gas"}, {"id": "b", "label": "ice only"}, {"id": "c", "label": "light"}, {"id": "d", "label": "rock"}], "answer": "d", "explanation": "Yes! The answer is \"rock\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The four outer planets are large and made mostly of:", "choices": [{"id": "a", "label": "rock"}, {"id": "b", "label": "metal only"}, {"id": "c", "label": "gas"}, {"id": "d", "label": "water"}], "answer": "c", "explanation": "Yes! The answer is \"gas\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Earth takes about one ____ to orbit the Sun.", "choices": [{"id": "a", "label": "day"}, {"id": "b", "label": "month"}, {"id": "c", "label": "hour"}, {"id": "d", "label": "year"}], "answer": "d", "explanation": "Yes! The answer is \"year\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about The Solar System! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$solar-system$tl$ and t.grade_level = 6);

-- science: Atoms & Matter
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Atoms & Matter", "body": "Matter is made of atoms; substances can be elements, compounds, or mixtures."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The smallest unit of an element is an:\n\nThe answer is \"atom\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Two or more atoms joined together form a:\n\nThe answer is \"molecule\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A substance made of only one kind of atom is an:\n\nThe answer is \"element\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Water (H2O) is made of hydrogen and oxygen, so it is a:", "choices": [{"id": "a", "label": "element"}, {"id": "b", "label": "mixture"}, {"id": "c", "label": "compound"}, {"id": "d", "label": "atom"}], "answer": "c", "explanation": "Yes! The answer is \"compound\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In a solid, particles are packed closely and:", "choices": [{"id": "a", "label": "move freely and far apart"}, {"id": "b", "label": "vibrate in place"}, {"id": "c", "label": "disappear"}, {"id": "d", "label": "do not exist"}], "answer": "b", "explanation": "Yes! The answer is \"vibrate in place\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In a gas, particles:", "choices": [{"id": "a", "label": "are locked in place"}, {"id": "b", "label": "are a liquid"}, {"id": "c", "label": "vanish"}, {"id": "d", "label": "move quickly and spread far apart"}], "answer": "d", "explanation": "Yes! The answer is \"move quickly and spread far apart\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Atoms & Matter! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$atoms-and-matter$tl$ and t.grade_level = 6);

-- science: Energy & Its Transfer
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Energy & Its Transfer", "body": "Energy can be stored or moving and is transferred by conduction, convection, and radiation."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Energy that an object has because it is moving is:\n\nThe answer is \"kinetic energy\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Stored energy due to position, like a raised ball, is:\n\nThe answer is \"potential energy\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Energy cannot be created or destroyed, only:\n\nThe answer is \"transferred or transformed\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Heat moving through a metal spoon in soup is:", "choices": [{"id": "a", "label": "convection"}, {"id": "b", "label": "radiation"}, {"id": "c", "label": "conduction"}, {"id": "d", "label": "reflection"}], "answer": "c", "explanation": "Yes! The answer is \"conduction\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Heat carried by moving liquids or gases is:", "choices": [{"id": "a", "label": "conduction"}, {"id": "b", "label": "convection"}, {"id": "c", "label": "radiation"}, {"id": "d", "label": "insulation"}], "answer": "b", "explanation": "Yes! The answer is \"convection\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Heat from the Sun reaching Earth through space is:", "choices": [{"id": "a", "label": "conduction"}, {"id": "b", "label": "convection"}, {"id": "c", "label": "radiation"}, {"id": "d", "label": "friction"}], "answer": "c", "explanation": "Yes! The answer is \"radiation\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Energy & Its Transfer! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$energy-transfer$tl$ and t.grade_level = 6);

-- science: Forces & Motion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Forces & Motion", "body": "Forces change motion; balanced forces keep it steady while unbalanced forces change it."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A push or a pull is a:\n\nThe answer is \"force\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The tendency of an object to resist changes in motion is:\n\nThe answer is \"inertia\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An object at rest stays at rest unless acted on by an:\n\nThe answer is \"unbalanced force\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Forces that are equal and opposite are:", "choices": [{"id": "a", "label": "unbalanced"}, {"id": "b", "label": "balanced"}, {"id": "c", "label": "negative"}, {"id": "d", "label": "invisible"}], "answer": "b", "explanation": "Yes! The answer is \"balanced\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Unbalanced forces cause an object's motion to:", "choices": [{"id": "a", "label": "stay exactly the same"}, {"id": "b", "label": "disappear"}, {"id": "c", "label": "change"}, {"id": "d", "label": "reverse time"}], "answer": "c", "explanation": "Yes! The answer is \"change\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The force that opposes motion between surfaces is:", "choices": [{"id": "a", "label": "gravity"}, {"id": "b", "label": "magnetism"}, {"id": "c", "label": "inertia"}, {"id": "d", "label": "friction"}], "answer": "d", "explanation": "Yes! The answer is \"friction\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Forces & Motion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$forces-and-motion$tl$ and t.grade_level = 6);

-- reading: Central Idea
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Central Idea", "body": "The central idea is a text's most important overall point, developed by details."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The central idea of a text is its:\n\nThe answer is \"most important overall point\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Supporting details in a text serve to:\n\nThe answer is \"develop the central idea\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Bees pollinate crops, support ecosystems, and produce honey, making them vital.\" The central idea is that bees are:\n\nThe answer is \"important to humans and nature\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To find the central idea, you should consider the text as a:", "choices": [{"id": "a", "label": "single word"}, {"id": "b", "label": "whole"}, {"id": "c", "label": "title only"}, {"id": "d", "label": "page number"}], "answer": "b", "explanation": "Yes! The answer is \"whole\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A central idea is usually:", "choices": [{"id": "a", "label": "supported by several details"}, {"id": "b", "label": "stated as a question"}, {"id": "c", "label": "a random fact"}, {"id": "d", "label": "the shortest sentence"}], "answer": "a", "explanation": "Yes! The answer is \"supported by several details\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Despite setbacks, the team kept testing until their rover finally worked.\" The central idea is about:", "choices": [{"id": "a", "label": "building cars"}, {"id": "b", "label": "spending money"}, {"id": "c", "label": "the color of the rover"}, {"id": "d", "label": "persistence leading to success"}], "answer": "d", "explanation": "Yes! The answer is \"persistence leading to success\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Central Idea! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$central-idea$tl$ and t.grade_level = 6);

-- reading: Theme
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Theme", "body": "A theme is a story's underlying message about life, shown through the characters."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A theme is a story's:\n\nThe answer is \"underlying message about life\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Theme differs from topic because theme is a:\n\nThe answer is \"complete idea or lesson\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Though small and doubted, the girl's idea saved the village.\" A theme is:\n\nThe answer is \"everyone's contribution matters\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Authors usually reveal theme through:", "choices": [{"id": "a", "label": "the title page only"}, {"id": "b", "label": "characters' actions and changes"}, {"id": "c", "label": "the font"}, {"id": "d", "label": "the price"}], "answer": "b", "explanation": "Yes! The answer is \"characters' actions and changes\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A story where greed leads to ruin develops a theme about the:", "choices": [{"id": "a", "label": "joy of greed"}, {"id": "b", "label": "size of houses"}, {"id": "c", "label": "dangers of greed"}, {"id": "d", "label": "weather"}], "answer": "c", "explanation": "Yes! The answer is \"dangers of greed\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Two very different stories can share a theme such as:", "choices": [{"id": "a", "label": "the same exact plot"}, {"id": "b", "label": "the same author"}, {"id": "c", "label": "courage in the face of fear"}, {"id": "d", "label": "the same length"}], "answer": "c", "explanation": "Yes! The answer is \"courage in the face of fear\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Theme! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$theme$tl$ and t.grade_level = 6);

-- reading: Objective Summary
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Objective Summary", "body": "An objective summary briefly restates the central idea and key details without opinion."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An objective summary should:\n\nThe answer is \"stay neutral and factual\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A good summary is ____ than the original.\n\nThe answer is \"shorter\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A summary should capture the central idea and the:\n\nThe answer is \"most important details\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When summarizing, restate ideas in your:", "choices": [{"id": "a", "label": "the author's exact words"}, {"id": "b", "label": "own words"}, {"id": "c", "label": "a code"}, {"id": "d", "label": "emojis only"}], "answer": "b", "explanation": "Yes! The answer is \"own words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which should be LEFT OUT of an objective summary?", "choices": [{"id": "a", "label": "your personal feelings"}, {"id": "b", "label": "the main idea"}, {"id": "c", "label": "key supporting points"}, {"id": "d", "label": "the topic"}], "answer": "a", "explanation": "Yes! The answer is \"your personal feelings\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Events in a narrative summary should appear in:", "choices": [{"id": "a", "label": "random order"}, {"id": "b", "label": "reverse only"}, {"id": "c", "label": "logical order"}, {"id": "d", "label": "no order"}], "answer": "c", "explanation": "Yes! The answer is \"logical order\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Objective Summary! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$summarizing$tl$ and t.grade_level = 6);

-- reading: Citing Text Evidence
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Citing Text Evidence", "body": "Support your ideas and inferences with specific evidence taken from the text."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Text evidence is information you take ____ from the text to support an answer.\n\nThe answer is \"directly\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  To support a claim about a text, you should cite:\n\nThe answer is \"specific details or quotes\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An inference must be supported by:\n\nThe answer is \"evidence in the text\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "'The text states...' is a phrase used to:", "choices": [{"id": "a", "label": "introduce evidence"}, {"id": "b", "label": "end an essay"}, {"id": "c", "label": "change topics"}, {"id": "d", "label": "give an opinion"}], "answer": "a", "explanation": "Yes! The answer is \"introduce evidence\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Strong evidence is:", "choices": [{"id": "a", "label": "relevant and from the text"}, {"id": "b", "label": "off-topic"}, {"id": "c", "label": "made up"}, {"id": "d", "label": "about the author's age"}], "answer": "a", "explanation": "Yes! The answer is \"relevant and from the text\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When asked 'how do you know?', a good reader:", "choices": [{"id": "a", "label": "guesses"}, {"id": "b", "label": "ignores the text"}, {"id": "c", "label": "talks about lunch"}, {"id": "d", "label": "points to text evidence"}], "answer": "d", "explanation": "Yes! The answer is \"points to text evidence\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Citing Text Evidence! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$citing-evidence$tl$ and t.grade_level = 6);

-- reading: Author's Purpose & View
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Author's Purpose & View", "body": "Authors write to inform, persuade, or entertain, often revealing a point of view."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An author's purpose for writing might be to inform, entertain, or:\n\nThe answer is \"persuade\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An author's point of view is their:\n\nThe answer is \"attitude or stance on a topic\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text that argues you should recycle is mainly meant to:\n\nThe answer is \"persuade\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Word choices that show strong feelings can reveal the author's:", "choices": [{"id": "a", "label": "page number"}, {"id": "b", "label": "font"}, {"id": "c", "label": "price"}, {"id": "d", "label": "point of view / bias"}], "answer": "d", "explanation": "Yes! The answer is \"point of view / bias\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An encyclopedia entry's purpose is usually to:", "choices": [{"id": "a", "label": "persuade"}, {"id": "b", "label": "entertain"}, {"id": "c", "label": "inform"}, {"id": "d", "label": "sell"}], "answer": "c", "explanation": "Yes! The answer is \"inform\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To find an author's purpose, ask:", "choices": [{"id": "a", "label": "how long is it?"}, {"id": "b", "label": "who printed it?"}, {"id": "c", "label": "what is the cover?"}, {"id": "d", "label": "why did they write this?"}], "answer": "d", "explanation": "Yes! The answer is \"why did they write this?\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Author's Purpose & View! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$authors-point-of-view$tl$ and t.grade_level = 6);

-- reading: Word Meaning
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Word Meaning", "body": "Use context clues, prefixes, suffixes, and roots to determine word meanings."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The benevolent leader gave generously to the poor.\" \"Benevolent\" means:\n\nThe answer is \"kind / generous\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"His incessant talking never stopped all day.\" \"Incessant\" means:\n\nThe answer is \"constant / nonstop\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The drought made the once-fertile land barren.\" \"Barren\" means:\n\nThe answer is \"empty / unable to grow life\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The prefix 'un-' in 'unhappy' means:", "choices": [{"id": "a", "label": "not"}, {"id": "b", "label": "very"}, {"id": "c", "label": "again"}, {"id": "d", "label": "before"}], "answer": "a", "explanation": "Yes! The answer is \"not\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The root 'aqua' in 'aquarium' relates to:", "choices": [{"id": "a", "label": "fire"}, {"id": "b", "label": "air"}, {"id": "c", "label": "water"}, {"id": "d", "label": "earth"}], "answer": "c", "explanation": "Yes! The answer is \"water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She was reluctant and hesitated to agree.\" \"Reluctant\" means:", "choices": [{"id": "a", "label": "eager"}, {"id": "b", "label": "angry"}, {"id": "c", "label": "unwilling"}, {"id": "d", "label": "tired"}], "answer": "c", "explanation": "Yes! The answer is \"unwilling\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Word Meaning! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$word-meaning$tl$ and t.grade_level = 6);

-- reading: Text Structure
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Text Structure", "body": "Authors organize texts as sequence, cause-effect, compare-contrast, or problem-solution."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A text organized by time order uses a ____ structure.\n\nThe answer is \"chronological / sequence\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A text explaining reasons and results uses:\n\nThe answer is \"cause and effect\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text showing similarities and differences uses:\n\nThe answer is \"compare and contrast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text that names an issue and offers fixes uses:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "problem and solution"}, {"id": "c", "label": "description"}, {"id": "d", "label": "compare"}], "answer": "b", "explanation": "Yes! The answer is \"problem and solution\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'first, then, finally' point to a ____ structure.", "choices": [{"id": "a", "label": "compare"}, {"id": "b", "label": "cause-effect"}, {"id": "c", "label": "problem-solution"}, {"id": "d", "label": "sequence"}], "answer": "d", "explanation": "Yes! The answer is \"sequence\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'because, therefore, as a result' point to:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "compare"}, {"id": "c", "label": "description"}, {"id": "d", "label": "cause and effect"}], "answer": "d", "explanation": "Yes! The answer is \"cause and effect\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Text Structure! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$text-structure$tl$ and t.grade_level = 6);

-- reading: Figurative Language
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Figurative Language", "body": "Similes, metaphors, personification, idioms, and hyperbole add meaning and imagery."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  \"The world is a stage\" is a:\n\nThe answer is \"metaphor\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  \"As brave as a lion\" is a:\n\nThe answer is \"simile\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Giving human traits to nonhuman things is:\n\nThe answer is \"personification\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"I have a ton of homework\" is an exaggeration called:", "choices": [{"id": "a", "label": "simile"}, {"id": "b", "label": "metaphor"}, {"id": "c", "label": "hyperbole"}, {"id": "d", "label": "idiom"}], "answer": "c", "explanation": "Yes! The answer is \"hyperbole\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An expression like 'spill the beans' whose meaning isn't literal is an:", "choices": [{"id": "a", "label": "idiom"}, {"id": "b", "label": "simile"}, {"id": "c", "label": "metaphor"}, {"id": "d", "label": "onomatopoeia"}], "answer": "a", "explanation": "Yes! The answer is \"idiom\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Words like 'crash' and 'hiss' that imitate sounds are:", "choices": [{"id": "a", "label": "similes"}, {"id": "b", "label": "onomatopoeia"}, {"id": "c", "label": "metaphors"}, {"id": "d", "label": "idioms"}], "answer": "b", "explanation": "Yes! The answer is \"onomatopoeia\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Figurative Language! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$figurative-language$tl$ and t.grade_level = 6);

-- reading: Comparing Texts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Texts", "body": "Comparing texts and genres on a topic reveals different viewpoints and approaches."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Comparing two texts on the same topic helps reveal their different:\n\nThe answer is \"approaches and viewpoints\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A memoir and a news article about the same event differ most in:\n\nThe answer is \"point of view and tone\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Two authors may present the same facts but reach different:\n\nThe answer is \"conclusions\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A poem and an essay on nature differ in their:", "choices": [{"id": "a", "label": "form and style"}, {"id": "b", "label": "subject"}, {"id": "c", "label": "truth"}, {"id": "d", "label": "alphabet"}], "answer": "a", "explanation": "Yes! The answer is \"form and style\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Reading multiple sources on a topic helps a reader:", "choices": [{"id": "a", "label": "build a fuller understanding"}, {"id": "b", "label": "get less information"}, {"id": "c", "label": "ignore facts"}, {"id": "d", "label": "memorize fonts"}], "answer": "a", "explanation": "Yes! The answer is \"build a fuller understanding\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A primary source is an account from:", "choices": [{"id": "a", "label": "a later textbook only"}, {"id": "b", "label": "fiction always"}, {"id": "c", "label": "someone who was there"}, {"id": "d", "label": "an unrelated topic"}], "answer": "c", "explanation": "Yes! The answer is \"someone who was there\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Texts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-texts$tl$ and t.grade_level = 6);

-- reading: Plot & Conflict
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plot & Conflict", "body": "Plot is the sequence of events; conflict is the central struggle that drives the story."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The series of events in a story is the:\n\nThe answer is \"plot\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The problem the characters face is the:\n\nThe answer is \"conflict\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A struggle between two characters is an example of:\n\nThe answer is \"character vs. character conflict\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A character battling a storm shows:", "choices": [{"id": "a", "label": "character vs. character"}, {"id": "b", "label": "character vs. nature"}, {"id": "c", "label": "character vs. self"}, {"id": "d", "label": "no conflict"}], "answer": "b", "explanation": "Yes! The answer is \"character vs. nature\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A character struggling with a tough decision shows:", "choices": [{"id": "a", "label": "character vs. nature"}, {"id": "b", "label": "character vs. character"}, {"id": "c", "label": "setting"}, {"id": "d", "label": "character vs. self"}], "answer": "d", "explanation": "Yes! The answer is \"character vs. self\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The part of the plot that builds tension toward the climax is the:", "choices": [{"id": "a", "label": "resolution"}, {"id": "b", "label": "exposition only"}, {"id": "c", "label": "theme"}, {"id": "d", "label": "rising action"}], "answer": "d", "explanation": "Yes! The answer is \"rising action\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plot & Conflict! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$plot-and-conflict$tl$ and t.grade_level = 6);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"library\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"balloon\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"puppy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "brave"}, {"id": "b", "label": "ancient"}, {"id": "c", "label": "curious"}, {"id": "d", "label": "sister"}], "answer": "d", "explanation": "Yes! The answer is \"sister\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "gallop"}, {"id": "b", "label": "narrow"}, {"id": "c", "label": "garden"}, {"id": "d", "label": "fluffy"}], "answer": "c", "explanation": "Yes! The answer is \"garden\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "whisper"}, {"id": "b", "label": "window"}, {"id": "c", "label": "fluffy"}, {"id": "d", "label": "bounce"}], "answer": "b", "explanation": "Yes! The answer is \"window\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 6);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action or a state of being."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"paint\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"scribble\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"march\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "build"}, {"id": "b", "label": "golden"}, {"id": "c", "label": "ancient"}, {"id": "d", "label": "narrow"}], "answer": "a", "explanation": "Yes! The answer is \"build\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "pencil"}, {"id": "b", "label": "ancient"}, {"id": "c", "label": "golden"}, {"id": "d", "label": "discover"}], "answer": "d", "explanation": "Yes! The answer is \"discover\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "frozen"}, {"id": "b", "label": "golden"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "bounce"}], "answer": "d", "explanation": "Yes! The answer is \"bounce\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 6);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"gentle\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"narrow\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"tiny\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "balloon"}, {"id": "b", "label": "brave"}, {"id": "c", "label": "bounce"}, {"id": "d", "label": "garden"}], "answer": "b", "explanation": "Yes! The answer is \"brave\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "explore"}, {"id": "b", "label": "doctor"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "slippery"}], "answer": "d", "explanation": "Yes! The answer is \"slippery\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "ancient"}, {"id": "b", "label": "engine"}, {"id": "c", "label": "explore"}, {"id": "d", "label": "gallop"}], "answer": "a", "explanation": "Yes! The answer is \"ancient\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 6);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"I\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"we\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"us\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "gallop"}, {"id": "b", "label": "kitchen"}, {"id": "c", "label": "you"}, {"id": "d", "label": "island"}], "answer": "c", "explanation": "Yes! The answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "her"}, {"id": "b", "label": "island"}, {"id": "c", "label": "build"}, {"id": "d", "label": "mountain"}], "answer": "a", "explanation": "Yes! The answer is \"her\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "they"}, {"id": "b", "label": "sister"}, {"id": "c", "label": "village"}, {"id": "d", "label": "kitchen"}], "answer": "a", "explanation": "Yes! The answer is \"they\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 6);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must agree with its subject in number."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The bird ____ every day.\"\n\nThe answer is \"sings\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The puppy ____ every day.\"\n\nThe answer is \"wags\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The river ____ every day.\"\n\nThe answer is \"flows\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The chef ____ every day.\"", "choices": [{"id": "a", "label": "cook"}, {"id": "b", "label": "cooks"}, {"id": "c", "label": "cooksed"}, {"id": "d", "label": "cooksing"}], "answer": "b", "explanation": "Yes! The answer is \"cooks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The farmer ____ every day.\"", "choices": [{"id": "a", "label": "plant"}, {"id": "b", "label": "plantsed"}, {"id": "c", "label": "plants"}, {"id": "d", "label": "plantsing"}], "answer": "c", "explanation": "Yes! The answer is \"plants\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The student ____ every day.\"", "choices": [{"id": "a", "label": "read"}, {"id": "b", "label": "readsed"}, {"id": "c", "label": "reads"}, {"id": "d", "label": "readsing"}], "answer": "c", "explanation": "Yes! The answer is \"reads\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 6);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs describe actions that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"run\"?\n\nThe answer is \"ran\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"fly\"?\n\nThe answer is \"flew\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"sing\"?\n\nThe answer is \"sang\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"buy\"?\n\nThe answer is bought."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"teach\"?\n\nThe answer is taught."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"go\"?\n\nThe answer is went."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 6);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals show more than one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"story\".\n\nThe answer is \"stories\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"lady\".\n\nThe answer is \"ladies\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"glass\".\n\nThe answer is \"glasses\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"cherry\".\n\nThe answer is cherries."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"loaf\".\n\nThe answer is loaves."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"shelf\".\n\nThe answer is shelves."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 6);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize sentence beginnings, I, and proper nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Pacific Ocean\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"December\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"London\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "day"}, {"id": "c", "label": "Canada"}, {"id": "d", "label": "river"}], "answer": "c", "explanation": "Yes! The answer is \"Canada\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "friend"}, {"id": "b", "label": "Friday"}, {"id": "c", "label": "ocean"}, {"id": "d", "label": "month"}], "answer": "b", "explanation": "Yes! The answer is \"Friday\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "day"}, {"id": "b", "label": "country"}, {"id": "c", "label": "city"}, {"id": "d", "label": "Tokyo"}], "answer": "d", "explanation": "Yes! The answer is \"Tokyo\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 6);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End sentences with a period, question mark, or exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"I love to read___\"\n\nThe answer is \".\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"Are you ready___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"Where are we going___\"\n\nThe answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"We won the game___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "!"}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "b", "explanation": "Yes! The answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Run for your life___\"", "choices": [{"id": "a", "label": "!"}, {"id": "b", "label": "."}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Watch out___\"", "choices": [{"id": "a", "label": "!"}, {"id": "b", "label": "."}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"!\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 6);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "Use commas to separate three or more items in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like walk, skip, and hop.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like apples, oranges, and pears.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like ham, cheese, and lettuce.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like cats, dogs, and fish."}, {"id": "b", "label": "I like cats dogs and fish."}, {"id": "c", "label": "I like cats, dogs and fish"}, {"id": "d", "label": "I like, cats dogs fish."}], "answer": "a", "explanation": "Yes! The answer is \"I like cats, dogs, and fish.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like milk eggs and bread."}, {"id": "b", "label": "I like milk, eggs and bread"}, {"id": "c", "label": "I like milk, eggs, and bread."}, {"id": "d", "label": "I like, milk eggs bread."}], "answer": "c", "explanation": "Yes! The answer is \"I like milk, eggs, and bread.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like rain snow and hail."}, {"id": "b", "label": "I like rain, snow and hail"}, {"id": "c", "label": "I like rain, snow, and hail."}, {"id": "d", "label": "I like, rain snow hail."}], "answer": "c", "explanation": "Yes! The answer is \"I like rain, snow, and hail.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 6);

