-- =====================================================================
-- TopicLeap - richer lessons for Grade 5 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Multi-Digit Multiplication
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Multi-Digit Multiplication", "body": "Multiply larger numbers by breaking them into place values. Worksheets get harder as the numbers grow."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Multiply: 19 x 5 = ?\n\nThe answer is \"95\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Multiply: 30 x 6 = ?\n\nThe answer is \"180\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Multiply: 12 x 4 = ?\n\nThe answer is \"48\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Multiply: 836 x 9 = ?\n\nThe answer is 7524."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Multiply: 587 x 3 = ?\n\nThe answer is 1761."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Multiply: 357 x 5 = ?\n\nThe answer is 1785."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Multi-Digit Multiplication! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$multi-digit-multiplication$tl$ and t.grade_level = 5);

-- math: Long Division
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Long Division", "body": "Divide larger numbers into equal groups. Each worksheet uses bigger numbers than the last."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Divide: 18 / 2 = ?\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Divide: 24 / 3 = ?\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Divide: 12 / 3 = ?\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Divide: 75 / 5 = ?\n\nThe answer is 15."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Divide: 48 / 2 = ?\n\nThe answer is 24."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Divide: 42 / 3 = ?\n\nThe answer is 14."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Long Division! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$long-division$tl$ and t.grade_level = 5);

-- math: Decimal Place Value
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Decimal Place Value", "body": "Each digit after the decimal point has a smaller place value: tenths, hundredths, thousandths."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the value of the digit 2 in 8.2?\n\nThe answer is \"0.2\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the value of the digit 3 in 3.4?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the value of the digit 2 in 2.8?\n\nThe answer is \"2\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the value of the digit 8 in 1.8?", "choices": [{"id": "a", "label": "80"}, {"id": "b", "label": "0.8"}, {"id": "c", "label": "8"}, {"id": "d", "label": "0.08"}], "answer": "b", "explanation": "Yes! The answer is \"0.8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the value of the digit 4 in 3.4?", "choices": [{"id": "a", "label": "0.04"}, {"id": "b", "label": "40"}, {"id": "c", "label": "4"}, {"id": "d", "label": "0.4"}], "answer": "d", "explanation": "Yes! The answer is \"0.4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the value of the digit 1 in 1.14?", "choices": [{"id": "a", "label": "0.1"}, {"id": "b", "label": "10"}, {"id": "c", "label": "1"}, {"id": "d", "label": "2"}], "answer": "c", "explanation": "Yes! The answer is \"1\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Decimal Place Value! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$decimal-place-value$tl$ and t.grade_level = 5);

-- math: Add & Subtract Decimals
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Add & Subtract Decimals", "body": "Line up the decimal points, then add or subtract just like whole numbers."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  0.1 + 1.2 = ?\n\nThe answer is \"1.3\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  2.5 + 0.3 = ?\n\nThe answer is \"2.8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  2 + 0.6 = ?\n\nThe answer is \"2.6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "0.4 + 0.7 = ?", "choices": [{"id": "a", "label": "1.1"}, {"id": "b", "label": "1.2"}, {"id": "c", "label": "0.4"}, {"id": "d", "label": "1"}], "answer": "a", "explanation": "Yes! The answer is \"1.1\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "2.2 + 2.1 = ?", "choices": [{"id": "a", "label": "4.2"}, {"id": "b", "label": "4.4"}, {"id": "c", "label": "2.2"}, {"id": "d", "label": "4.3"}], "answer": "d", "explanation": "Yes! The answer is \"4.3\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "6.6 + 3.8 = ?", "choices": [{"id": "a", "label": "6.6"}, {"id": "b", "label": "10.3"}, {"id": "c", "label": "10.4"}, {"id": "d", "label": "10.5"}], "answer": "c", "explanation": "Yes! The answer is \"10.4\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Add & Subtract Decimals! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$add-subtract-decimals$tl$ and t.grade_level = 5);

-- math: Multiply Decimals
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Multiply Decimals", "body": "Multiply the digits, then place the decimal point by counting decimal places."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  0.4 x 0.8 = ?\n\nThe answer is \"0.32\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  0.3 x 0.3 = ?\n\nThe answer is \"0.09\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  0.3 x 0.3 = ?\n\nThe answer is \"0.09\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "0.4 x 0.9 = ?", "choices": [{"id": "a", "label": "0.36"}, {"id": "b", "label": "36"}, {"id": "c", "label": "3.6"}, {"id": "d", "label": "0.036"}], "answer": "a", "explanation": "Yes! The answer is \"0.36\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "0.1 x 0.7 = ?", "choices": [{"id": "a", "label": "0.007"}, {"id": "b", "label": "0.7"}, {"id": "c", "label": "0.07"}, {"id": "d", "label": "0.17"}], "answer": "c", "explanation": "Yes! The answer is \"0.07\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "0.5 x 0.04 = ?", "choices": [{"id": "a", "label": "0.12"}, {"id": "b", "label": "0.02"}, {"id": "c", "label": "2"}, {"id": "d", "label": "0.002"}], "answer": "b", "explanation": "Yes! The answer is \"0.02\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Multiply Decimals! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$multiply-decimals$tl$ and t.grade_level = 5);

-- math: Add & Subtract Fractions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Add & Subtract Fractions", "body": "To add or subtract fractions with different denominators, first find a common denominator."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  2/3 + 1/2 = ?\n\nThe answer is \"7/6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  3/4 + 2/3 = ?\n\nThe answer is \"17/12\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  1/2 + 3/4 = ?\n\nThe answer is \"5/4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/3 + 1/2 = ?", "choices": [{"id": "a", "label": "5/6"}, {"id": "b", "label": "2/6"}, {"id": "c", "label": "1"}, {"id": "d", "label": "2/5"}], "answer": "a", "explanation": "Yes! The answer is \"5/6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/2 + 1/4 = ?", "choices": [{"id": "a", "label": "1"}, {"id": "b", "label": "2/8"}, {"id": "c", "label": "3/4"}, {"id": "d", "label": "2/6"}], "answer": "c", "explanation": "Yes! The answer is \"3/4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/4 + 1/3 = ?", "choices": [{"id": "a", "label": "2/7"}, {"id": "b", "label": "2/12"}, {"id": "c", "label": "7/12"}, {"id": "d", "label": "1"}], "answer": "c", "explanation": "Yes! The answer is \"7/12\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Add & Subtract Fractions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$add-subtract-fractions$tl$ and t.grade_level = 5);

-- math: Multiply Fractions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Multiply Fractions", "body": "To multiply fractions, multiply the numerators and multiply the denominators."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  1/2 x 1/2 = ?\n\nThe answer is \"1/4\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  3/4 x 2/4 = ?\n\nThe answer is \"3/8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  1/2 x 2/3 = ?\n\nThe answer is \"1/3\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "3/4 x 1/2 = ?", "choices": [{"id": "a", "label": "3/8"}, {"id": "b", "label": "4/8"}, {"id": "c", "label": "3/6"}, {"id": "d", "label": "1/2"}], "answer": "a", "explanation": "Yes! The answer is \"3/8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/3 x 1/2 = ?", "choices": [{"id": "a", "label": "1/3"}, {"id": "b", "label": "1/5"}, {"id": "c", "label": "1/6"}, {"id": "d", "label": "2/6"}], "answer": "c", "explanation": "Yes! The answer is \"1/6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "1/2 x 3/4 = ?", "choices": [{"id": "a", "label": "3/8"}, {"id": "b", "label": "3/6"}, {"id": "c", "label": "1/2"}, {"id": "d", "label": "4/8"}], "answer": "a", "explanation": "Yes! The answer is \"3/8\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Multiply Fractions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$multiply-fractions$tl$ and t.grade_level = 5);

-- math: Order of Operations
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Order of Operations", "body": "Do parentheses first, then multiply and divide, then add and subtract (left to right)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Solve using order of operations:  4 + 4 x 4 = ?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Solve using order of operations:  8 + 9 x 5 = ?\n\nThe answer is \"53\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Solve using order of operations:  6 + 5 x 3 = ?\n\nThe answer is \"21\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Solve using order of operations:  (6 + 2) x 8 = ?\n\nThe answer is 64."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Solve using order of operations:  (8 + 5) x 6 = ?\n\nThe answer is 78."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Solve using order of operations:  (4 + 8) x 5 = ?\n\nThe answer is 60."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Order of Operations! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$order-of-operations$tl$ and t.grade_level = 5);

-- math: Powers of Ten
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Powers of Ten", "body": "Multiplying by 10, 100, or 1000 shifts the digits left; dividing shifts them right."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  96 x 10 = ?\n\nThe answer is \"960\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  2 x 10 = ?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  5 x 10 = ?\n\nThe answer is \"50\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  76 x 100 = ?\n\nThe answer is 7600."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  53 x 100 = ?\n\nThe answer is 5300."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  52 x 100 = ?\n\nThe answer is 5200."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Powers of Ten! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$powers-of-ten$tl$ and t.grade_level = 5);

-- math: Volume
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Volume", "body": "The volume of a box is length x width x height, measured in cubic units."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A box is 4 units long, 2 wide, and 3 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is \"24\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A box is 4 units long, 4 wide, and 2 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is \"32\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A box is 3 units long, 3 wide, and 4 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is \"36\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A box is 6 units long, 5 wide, and 6 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is 180."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A box is 3 units long, 2 wide, and 6 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is 36."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A box is 3 units long, 2 wide, and 3 tall. What is its volume in cubic units?  (length x width x height)\n\nThe answer is 18."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Volume! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$volume$tl$ and t.grade_level = 5);

-- science: Matter & Its Properties
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Matter & Its Properties", "body": "Matter is anything with mass and volume; we identify materials by their properties."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Everything around us that has mass and takes up space is called:\n\nThe answer is \"matter\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The three common states of matter are solid, liquid, and:\n\nThe answer is \"gas\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is a property you can measure about matter?\n\nThe answer is \"mass\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Even a gas like air is made of tiny particles too small to:", "choices": [{"id": "a", "label": "weigh ever"}, {"id": "b", "label": "exist"}, {"id": "c", "label": "move"}, {"id": "d", "label": "see"}], "answer": "d", "explanation": "Yes! The answer is \"see\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A balloon filled with air shows that gas has:", "choices": [{"id": "a", "label": "no mass at all"}, {"id": "b", "label": "mass and takes up space"}, {"id": "c", "label": "no volume"}, {"id": "d", "label": "color only"}], "answer": "b", "explanation": "Yes! The answer is \"mass and takes up space\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which tool measures the mass of an object?", "choices": [{"id": "a", "label": "a ruler"}, {"id": "b", "label": "a thermometer"}, {"id": "c", "label": "a balance"}, {"id": "d", "label": "a clock"}], "answer": "c", "explanation": "Yes! The answer is \"a balance\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Matter & Its Properties! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$matter-and-properties$tl$ and t.grade_level = 5);

-- science: Mixtures & Solutions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Mixtures & Solutions", "body": "Mixtures can be separated; when a solid dissolves evenly in a liquid it forms a solution."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  When you stir sand into water, you make a:\n\nThe answer is \"mixture\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  When sugar dissolves completely in water, it forms a:\n\nThe answer is \"solution\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  In a solution, the dissolved substance seems to:\n\nThe answer is \"disappear (spread evenly)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which mixture can be separated by a strainer or filter?", "choices": [{"id": "a", "label": "salt fully dissolved in water"}, {"id": "b", "label": "sugar water"}, {"id": "c", "label": "sand and water"}, {"id": "d", "label": "air"}], "answer": "c", "explanation": "Yes! The answer is \"sand and water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "How can you separate salt from salt water?", "choices": [{"id": "a", "label": "use a magnet"}, {"id": "b", "label": "use a strainer"}, {"id": "c", "label": "freeze it once"}, {"id": "d", "label": "let the water evaporate"}], "answer": "d", "explanation": "Yes! The answer is \"let the water evaporate\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A magnet can be used to separate iron filings from:", "choices": [{"id": "a", "label": "salt water"}, {"id": "b", "label": "sugar"}, {"id": "c", "label": "air"}, {"id": "d", "label": "sand"}], "answer": "d", "explanation": "Yes! The answer is \"sand\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Mixtures & Solutions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$mixtures-and-solutions$tl$ and t.grade_level = 5);

-- science: Conservation of Matter
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Conservation of Matter", "body": "In ordinary changes, matter is never created or destroyed - total mass stays the same."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  When you mix two things, the total mass:\n\nThe answer is \"stays the same\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  If 50 g of water freezes into ice, the ice weighs about:\n\nThe answer is \"50 g\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Matter is never created or destroyed in ordinary changes - it is:\n\nThe answer is \"conserved\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When sugar dissolves in water, the mass of the solution equals:", "choices": [{"id": "a", "label": "sugar + water"}, {"id": "b", "label": "just the water"}, {"id": "c", "label": "just the sugar"}, {"id": "d", "label": "zero"}], "answer": "a", "explanation": "Yes! The answer is \"sugar + water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "If ice melts in a sealed cup, the water's mass is:", "choices": [{"id": "a", "label": "less"}, {"id": "b", "label": "more"}, {"id": "c", "label": "the same as the ice"}, {"id": "d", "label": "zero"}], "answer": "c", "explanation": "Yes! The answer is \"the same as the ice\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Burning a log seems to lose mass, but the gases released still count, so matter is:", "choices": [{"id": "a", "label": "conserved"}, {"id": "b", "label": "destroyed"}, {"id": "c", "label": "created"}, {"id": "d", "label": "gone"}], "answer": "a", "explanation": "Yes! The answer is \"conserved\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Conservation of Matter! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$conservation-of-matter$tl$ and t.grade_level = 5);

-- science: Food Webs & Energy
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Food Webs & Energy", "body": "Energy flows from the Sun to producers to consumers; decomposers recycle nutrients."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Almost all the energy in an ecosystem starts with the:\n\nThe answer is \"Sun\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Plants are called producers because they:\n\nThe answer is \"make their own food\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An animal that eats plants is a:\n\nThe answer is \"herbivore\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An animal that eats other animals is a:", "choices": [{"id": "a", "label": "herbivore"}, {"id": "b", "label": "carnivore"}, {"id": "c", "label": "producer"}, {"id": "d", "label": "plant"}], "answer": "b", "explanation": "Yes! The answer is \"carnivore\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In a food chain, an arrow points in the direction that:", "choices": [{"id": "a", "label": "animals walk"}, {"id": "b", "label": "the wind blows"}, {"id": "c", "label": "energy flows"}, {"id": "d", "label": "water falls"}], "answer": "c", "explanation": "Yes! The answer is \"energy flows\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Decomposers like fungi and bacteria break down dead things and return nutrients to the:", "choices": [{"id": "a", "label": "sky"}, {"id": "b", "label": "soil"}, {"id": "c", "label": "Sun"}, {"id": "d", "label": "ocean only"}], "answer": "b", "explanation": "Yes! The answer is \"soil\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Food Webs & Energy! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$food-webs-and-energy$tl$ and t.grade_level = 5);

-- science: How Plants Make Food
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: How Plants Make Food", "body": "Through photosynthesis, plants use sunlight, water, and air to make their own food."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Plants make their own food using sunlight in a process called:\n\nThe answer is \"photosynthesis\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Most of the material a plant uses to grow comes from:\n\nThe answer is \"air and water\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Plants take in carbon dioxide from the air through tiny openings in their:\n\nThe answer is \"leaves\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "During photosynthesis, plants release which gas that we breathe?", "choices": [{"id": "a", "label": "carbon dioxide"}, {"id": "b", "label": "helium"}, {"id": "c", "label": "smoke"}, {"id": "d", "label": "oxygen"}], "answer": "d", "explanation": "Yes! The answer is \"oxygen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The green substance in leaves that captures sunlight is:", "choices": [{"id": "a", "label": "water"}, {"id": "b", "label": "chlorophyll"}, {"id": "c", "label": "sugar"}, {"id": "d", "label": "soil"}], "answer": "b", "explanation": "Yes! The answer is \"chlorophyll\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Plants store the energy they make as:", "choices": [{"id": "a", "label": "sunlight"}, {"id": "b", "label": "sugar (food)"}, {"id": "c", "label": "oxygen"}, {"id": "d", "label": "water"}], "answer": "b", "explanation": "Yes! The answer is \"sugar (food)\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about How Plants Make Food! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$plants-make-food$tl$ and t.grade_level = 5);

-- science: Earth's Systems
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Earth's Systems", "body": "Earth's atmosphere, hydrosphere, geosphere, and biosphere constantly interact."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The layer of air surrounding Earth is the:\n\nThe answer is \"atmosphere\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  All of Earth's water - oceans, rivers, ice - makes up the:\n\nThe answer is \"hydrosphere\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Earth's rocks, soil, and land form the:\n\nThe answer is \"geosphere\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "All living things on Earth make up the:", "choices": [{"id": "a", "label": "atmosphere"}, {"id": "b", "label": "geosphere"}, {"id": "c", "label": "biosphere"}, {"id": "d", "label": "hydrosphere"}], "answer": "c", "explanation": "Yes! The answer is \"biosphere\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When rain (hydrosphere) helps a plant (biosphere) grow, two Earth systems are:", "choices": [{"id": "a", "label": "interacting"}, {"id": "b", "label": "disappearing"}, {"id": "c", "label": "stopping"}, {"id": "d", "label": "unrelated"}], "answer": "a", "explanation": "Yes! The answer is \"interacting\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Wind in the atmosphere shaping a sand dune shows the atmosphere affecting the:", "choices": [{"id": "a", "label": "biosphere only"}, {"id": "b", "label": "geosphere"}, {"id": "c", "label": "nothing"}, {"id": "d", "label": "Moon"}], "answer": "b", "explanation": "Yes! The answer is \"geosphere\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Earth's Systems! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$earth-systems$tl$ and t.grade_level = 5);

-- science: Water on Earth
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Water on Earth", "body": "Most of Earth's water is salty ocean; only a small fraction is usable fresh water."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  About what fraction of Earth's water is salty ocean water?\n\nThe answer is \"most of it\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Most of Earth's FRESH water is frozen in:\n\nThe answer is \"ice caps and glaciers\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is fresh water people can drink (when clean)?\n\nThe answer is \"river and lake water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Only a small amount of Earth's water is fresh water that is:", "choices": [{"id": "a", "label": "easy to use (liquid)"}, {"id": "b", "label": "salty"}, {"id": "c", "label": "frozen forever only"}, {"id": "d", "label": "in space"}], "answer": "a", "explanation": "Yes! The answer is \"easy to use (liquid)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Ocean water is not good for drinking because it is too:", "choices": [{"id": "a", "label": "cold"}, {"id": "b", "label": "clean"}, {"id": "c", "label": "salty"}, {"id": "d", "label": "fresh"}], "answer": "c", "explanation": "Yes! The answer is \"salty\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Underground water stored in soil and rock is called:", "choices": [{"id": "a", "label": "ocean water"}, {"id": "b", "label": "groundwater"}, {"id": "c", "label": "cloud water"}, {"id": "d", "label": "glacier ice"}], "answer": "b", "explanation": "Yes! The answer is \"groundwater\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Water on Earth! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$water-on-earth$tl$ and t.grade_level = 5);

-- science: Protecting Earth's Resources
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Protecting Earth's Resources", "body": "People can protect Earth by reducing, reusing, recycling, and using renewable energy."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Using fewer resources and reusing items helps:\n\nThe answer is \"protect the environment\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The three R's that reduce waste are reduce, reuse, and:\n\nThe answer is \"recycle\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which is a renewable energy source?\n\nThe answer is \"sunlight\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Burning fossil fuels like coal and oil adds pollution and:", "choices": [{"id": "a", "label": "greenhouse gases"}, {"id": "b", "label": "clean air"}, {"id": "c", "label": "fresh water"}, {"id": "d", "label": "oxygen"}], "answer": "a", "explanation": "Yes! The answer is \"greenhouse gases\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Planting trees helps because trees clean the air and provide:", "choices": [{"id": "a", "label": "plastic"}, {"id": "b", "label": "gasoline"}, {"id": "c", "label": "metal"}, {"id": "d", "label": "oxygen and habitat"}], "answer": "d", "explanation": "Yes! The answer is \"oxygen and habitat\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which action best conserves water?", "choices": [{"id": "a", "label": "letting taps run"}, {"id": "b", "label": "watering pavement"}, {"id": "c", "label": "ignoring leaks"}, {"id": "d", "label": "fixing leaky faucets"}], "answer": "d", "explanation": "Yes! The answer is \"fixing leaky faucets\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Protecting Earth's Resources! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$protecting-resources$tl$ and t.grade_level = 5);

-- science: Patterns in the Sky
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Patterns in the Sky", "body": "Earth's rotation and orbit cause day/night, seasons, shadows, and the Moon's phases."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The Sun appears to rise in the east and set in the:\n\nThe answer is \"west\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Day and night are caused by Earth:\n\nThe answer is \"rotating (spinning) once a day\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The seasons are caused by Earth's tilt as it:\n\nThe answer is \"orbits the Sun\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Stars appear to move across the night sky because Earth:", "choices": [{"id": "a", "label": "is exploding"}, {"id": "b", "label": "is shrinking"}, {"id": "c", "label": "makes the stars"}, {"id": "d", "label": "is rotating"}], "answer": "d", "explanation": "Yes! The answer is \"is rotating\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A shadow from a stick is longest when the Sun is:", "choices": [{"id": "a", "label": "directly overhead"}, {"id": "b", "label": "gone"}, {"id": "c", "label": "behind the Moon"}, {"id": "d", "label": "low in the sky"}], "answer": "d", "explanation": "Yes! The answer is \"low in the sky\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "At noon, when the Sun is highest, shadows are:", "choices": [{"id": "a", "label": "longest"}, {"id": "b", "label": "shortest"}, {"id": "c", "label": "gone forever"}, {"id": "d", "label": "pointing up"}], "answer": "b", "explanation": "Yes! The answer is \"shortest\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Patterns in the Sky! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$patterns-in-the-sky$tl$ and t.grade_level = 5);

-- science: Gravity
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Gravity", "body": "Gravity is a force that pulls objects toward Earth's center and holds planets in orbit."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The force that pulls objects toward Earth is:\n\nThe answer is \"gravity\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  When you drop a ball, gravity pulls it:\n\nThe answer is \"down toward Earth's center\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Gravity is what keeps the Moon in orbit around:\n\nThe answer is \"Earth\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Without gravity, objects on Earth would:", "choices": [{"id": "a", "label": "float away"}, {"id": "b", "label": "fall faster"}, {"id": "c", "label": "stay the same"}, {"id": "d", "label": "get heavier"}], "answer": "a", "explanation": "Yes! The answer is \"float away\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Weight is a measure of the pull of ____ on an object.", "choices": [{"id": "a", "label": "friction"}, {"id": "b", "label": "sound"}, {"id": "c", "label": "light"}, {"id": "d", "label": "gravity"}], "answer": "d", "explanation": "Yes! The answer is \"gravity\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Earth's gravity points toward Earth's:", "choices": [{"id": "a", "label": "the sky"}, {"id": "b", "label": "the Moon"}, {"id": "c", "label": "center"}, {"id": "d", "label": "the Sun"}], "answer": "c", "explanation": "Yes! The answer is \"center\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Gravity! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$gravity$tl$ and t.grade_level = 5);

-- reading: Main Idea & Details
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Main Idea & Details", "body": "The main idea is a text's key point; supporting details explain and back it up."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"Sea otters are vital to kelp forests. They eat sea urchins, which would otherwise destroy the kelp.\" The main idea is that sea otters:\n\nThe answer is \"help protect kelp forests\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Volcanoes can be destructive, but volcanic ash also enriches soil and creates fertile farmland.\" The main idea is that volcanoes:\n\nThe answer is \"can be both harmful and helpful\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  In the otter passage, which is a supporting detail?\n\nThe answer is \"they eat sea urchins\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Recycling conserves resources by saving trees, reducing energy use, and cutting landfill waste.\" A supporting detail is that recycling:", "choices": [{"id": "a", "label": "reduces energy use"}, {"id": "b", "label": "is colorful"}, {"id": "c", "label": "is difficult"}, {"id": "d", "label": "is loud"}], "answer": "a", "explanation": "Yes! The answer is \"reduces energy use\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The main idea of a paragraph is usually:", "choices": [{"id": "a", "label": "its most important point"}, {"id": "b", "label": "the longest sentence"}, {"id": "c", "label": "the first word"}, {"id": "d", "label": "a random fact"}], "answer": "a", "explanation": "Yes! The answer is \"its most important point\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Honeybee numbers are falling due to pesticides, disease, and habitat loss, threatening the crops they pollinate.\" The main idea is that:", "choices": [{"id": "a", "label": "declining bees endanger our crops"}, {"id": "b", "label": "bees make honey"}, {"id": "c", "label": "bees sting"}, {"id": "d", "label": "flowers are pretty"}], "answer": "a", "explanation": "Yes! The answer is \"declining bees endanger our crops\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Main Idea & Details! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$main-idea-and-details$tl$ and t.grade_level = 5);

-- reading: Theme
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Theme", "body": "A theme is the lesson or message a story conveys, usually shown through what characters learn."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A theme is the:\n\nThe answer is \"lesson or message of a story\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"After failing many times, Mia finally built her robot by never giving up.\" A theme is:\n\nThe answer is \"perseverance pays off\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A story where a selfish king learns to share teaches a theme about:\n\nThe answer is \"generosity / kindness\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Theme is different from plot because theme is the:", "choices": [{"id": "a", "label": "sequence of events"}, {"id": "b", "label": "list of characters"}, {"id": "c", "label": "the setting only"}, {"id": "d", "label": "underlying message"}], "answer": "d", "explanation": "Yes! The answer is \"underlying message\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The two rivals worked together to survive the storm and became friends.\" A theme is:", "choices": [{"id": "a", "label": "cooperation / friendship"}, {"id": "b", "label": "enemies forever"}, {"id": "c", "label": "storms are fun"}, {"id": "d", "label": "ignore others"}], "answer": "a", "explanation": "Yes! The answer is \"cooperation / friendship\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A common theme in many fables is:", "choices": [{"id": "a", "label": "honesty is important"}, {"id": "b", "label": "lying wins"}, {"id": "c", "label": "be cruel"}, {"id": "d", "label": "never learn"}], "answer": "a", "explanation": "Yes! The answer is \"honesty is important\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Theme! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$theme$tl$ and t.grade_level = 5);

-- reading: Summarizing
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Summarizing", "body": "A summary retells the main idea and key details briefly, in your own words."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A good summary includes the main idea and the:\n\nThe answer is \"most important details\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A summary should be:\n\nThe answer is \"shorter than the original\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  When summarizing, you should leave out:\n\nThe answer is \"unimportant details\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A summary should be written in:", "choices": [{"id": "a", "label": "the author's exact words"}, {"id": "b", "label": "a secret code"}, {"id": "c", "label": "your own words"}, {"id": "d", "label": "no words"}], "answer": "c", "explanation": "Yes! The answer is \"your own words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The first step to summarizing is to:", "choices": [{"id": "a", "label": "identify the main idea"}, {"id": "b", "label": "copy the whole text"}, {"id": "c", "label": "read only the title"}, {"id": "d", "label": "skip to the end"}], "answer": "a", "explanation": "Yes! The answer is \"identify the main idea\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A summary of a story should keep events in:", "choices": [{"id": "a", "label": "random order"}, {"id": "b", "label": "reverse only"}, {"id": "c", "label": "no order"}, {"id": "d", "label": "the correct order"}], "answer": "d", "explanation": "Yes! The answer is \"the correct order\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Summarizing! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$summarizing$tl$ and t.grade_level = 5);

-- reading: Making Inferences
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Making Inferences", "body": "An inference is a conclusion drawn from text clues plus what you already know."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An inference is a conclusion based on:\n\nThe answer is \"clues plus what you know\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Maria grabbed her umbrella and rain boots before leaving.\" You can infer:\n\nThe answer is \"it is raining or about to\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"Jake's stomach growled as he stared at the clock near noon.\" Infer that Jake is:\n\nThe answer is \"hungry\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The streets were empty and every shop was dark.\" You can infer it is:", "choices": [{"id": "a", "label": "a busy afternoon"}, {"id": "b", "label": "a parade"}, {"id": "c", "label": "lunchtime"}, {"id": "d", "label": "very early or very late"}], "answer": "d", "explanation": "Yes! The answer is \"very early or very late\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An author who doesn't state everything expects the reader to:", "choices": [{"id": "a", "label": "infer meaning from clues"}, {"id": "b", "label": "skip the text"}, {"id": "c", "label": "memorize it"}, {"id": "d", "label": "ignore details"}], "answer": "a", "explanation": "Yes! The answer is \"infer meaning from clues\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Tia hugged the trophy and beamed at the cheering crowd.\" Infer that Tia:", "choices": [{"id": "a", "label": "lost and is sad"}, {"id": "b", "label": "is bored"}, {"id": "c", "label": "won and is proud"}, {"id": "d", "label": "is afraid"}], "answer": "c", "explanation": "Yes! The answer is \"won and is proud\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Making Inferences! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$making-inferences$tl$ and t.grade_level = 5);

-- reading: Character Analysis
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Character Analysis", "body": "Understand characters through their words, actions, thoughts, and how they change."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  To understand a character, pay attention to their words, thoughts, and:\n\nThe answer is \"actions\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"Lia gave her lunch to the new student and offered to show him around.\" Lia is:\n\nThe answer is \"kind and welcoming\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A character who changes and grows during a story is called:\n\nThe answer is \"dynamic\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"No matter how many times he failed, Sam tried again.\" Sam is:", "choices": [{"id": "a", "label": "lazy"}, {"id": "b", "label": "determined"}, {"id": "c", "label": "fearful"}, {"id": "d", "label": "careless"}], "answer": "b", "explanation": "Yes! The answer is \"determined\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A character's motivation is the:", "choices": [{"id": "a", "label": "their height"}, {"id": "b", "label": "their clothes"}, {"id": "c", "label": "reason they act"}, {"id": "d", "label": "their name"}], "answer": "c", "explanation": "Yes! The answer is \"reason they act\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She lied to avoid blame, then felt guilty all night.\" This shows the character has a:", "choices": [{"id": "a", "label": "conscience (sense of right and wrong)"}, {"id": "b", "label": "fear of dogs"}, {"id": "c", "label": "love of math"}, {"id": "d", "label": "new bike"}], "answer": "a", "explanation": "Yes! The answer is \"conscience (sense of right and wrong)\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Character Analysis! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$character-analysis$tl$ and t.grade_level = 5);

-- reading: Point of View
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Point of View", "body": "Point of view is the perspective a story is told from - first or third person."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A story told using 'I' and 'me' is written in:\n\nThe answer is \"first person\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A story told using 'he', 'she', and 'they' is in:\n\nThe answer is \"third person\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The narrator is the:\n\nThe answer is \"one telling the story\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"I couldn't believe my eyes as I opened the door.\" This is:", "choices": [{"id": "a", "label": "first person"}, {"id": "b", "label": "third person"}, {"id": "c", "label": "second person"}, {"id": "d", "label": "no narrator"}], "answer": "a", "explanation": "Yes! The answer is \"first person\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She wondered what was behind the door as he waited.\" This is:", "choices": [{"id": "a", "label": "first person"}, {"id": "b", "label": "second person"}, {"id": "c", "label": "third person"}, {"id": "d", "label": "fourth person"}], "answer": "c", "explanation": "Yes! The answer is \"third person\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Point of view is the:", "choices": [{"id": "a", "label": "page count"}, {"id": "b", "label": "setting"}, {"id": "c", "label": "title"}, {"id": "d", "label": "perspective the story is told from"}], "answer": "d", "explanation": "Yes! The answer is \"perspective the story is told from\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Point of View! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$point-of-view$tl$ and t.grade_level = 5);

-- reading: Vocabulary in Context
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Vocabulary in Context", "body": "Use surrounding words to figure out the meaning of unfamiliar vocabulary."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Read: \"The arid desert had not seen rain in months.\" \"Arid\" means:\n\nThe answer is \"very dry\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Read: \"His ravenous appetite made him eat three plates.\" \"Ravenous\" means:\n\nThe answer is \"very hungry\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Read: \"The fragile glass shattered at the lightest touch.\" \"Fragile\" means:\n\nThe answer is \"easily broken\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"She was elated to win first prize.\" \"Elated\" means:", "choices": [{"id": "a", "label": "very happy"}, {"id": "b", "label": "very sad"}, {"id": "c", "label": "very bored"}, {"id": "d", "label": "very tired"}], "answer": "a", "explanation": "Yes! The answer is \"very happy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The vast ocean stretched beyond the horizon.\" \"Vast\" means:", "choices": [{"id": "a", "label": "huge"}, {"id": "b", "label": "tiny"}, {"id": "c", "label": "shallow"}, {"id": "d", "label": "loud"}], "answer": "a", "explanation": "Yes! The answer is \"huge\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"He spoke in an audible whisper we could just hear.\" \"Audible\" means:", "choices": [{"id": "a", "label": "silent"}, {"id": "b", "label": "bright"}, {"id": "c", "label": "sweet"}, {"id": "d", "label": "able to be heard"}], "answer": "d", "explanation": "Yes! The answer is \"able to be heard\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Vocabulary in Context! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$context-clues$tl$ and t.grade_level = 5);

-- reading: Text Structure
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Text Structure", "body": "Authors organize texts as sequence, cause-effect, compare-contrast, or problem-solution."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A text that lists steps in order uses a ____ structure.\n\nThe answer is \"sequence (chronological)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A text that explains why something happens and the results uses:\n\nThe answer is \"cause and effect\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text that tells how two things are alike and different uses:\n\nThe answer is \"compare and contrast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text that presents an issue and then ways to fix it uses:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "problem and solution"}, {"id": "c", "label": "description"}, {"id": "d", "label": "compare"}], "answer": "b", "explanation": "Yes! The answer is \"problem and solution\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Words like first, next, then, and finally signal a ____ structure.", "choices": [{"id": "a", "label": "compare"}, {"id": "b", "label": "sequence"}, {"id": "c", "label": "cause-effect"}, {"id": "d", "label": "problem-solution"}], "answer": "b", "explanation": "Yes! The answer is \"sequence\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Words like because, since, and as a result signal:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "cause and effect"}, {"id": "c", "label": "compare"}, {"id": "d", "label": "description"}], "answer": "b", "explanation": "Yes! The answer is \"cause and effect\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Text Structure! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$text-structure$tl$ and t.grade_level = 5);

-- reading: Comparing Texts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Texts", "body": "Comparing texts on the same topic reveals how they are alike and different."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  To compare two texts means to find how they are:\n\nThe answer is \"alike\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  To contrast two texts means to find how they are:\n\nThe answer is \"different\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Two articles on sharks, one scary and one scientific, differ mainly in their:\n\nThe answer is \"tone / purpose\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read accounts of the same storm by a sailor and a scientist; they likely differ in:", "choices": [{"id": "a", "label": "the date it happened"}, {"id": "b", "label": "whether it was a storm"}, {"id": "c", "label": "point of view and detail"}, {"id": "d", "label": "the planet"}], "answer": "c", "explanation": "Yes! The answer is \"point of view and detail\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A Venn diagram is a tool used to:", "choices": [{"id": "a", "label": "tell time"}, {"id": "b", "label": "measure mass"}, {"id": "c", "label": "compare and contrast"}, {"id": "d", "label": "spell words"}], "answer": "c", "explanation": "Yes! The answer is \"compare and contrast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Two recipes for bread are alike because both:", "choices": [{"id": "a", "label": "give steps to make bread"}, {"id": "b", "label": "are mystery novels"}, {"id": "c", "label": "are about cars"}, {"id": "d", "label": "are poems"}], "answer": "a", "explanation": "Yes! The answer is \"give steps to make bread\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Texts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-and-contrast$tl$ and t.grade_level = 5);

-- reading: Figurative Language
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Figurative Language", "body": "Similes, metaphors, personification, idioms, and hyperbole create vivid meaning."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  \"Her smile was as bright as the sun\" is a:\n\nThe answer is \"simile\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  \"Time is a thief\" is a:\n\nThe answer is \"metaphor\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A simile compares two things using:\n\nThe answer is \"like or as\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A metaphor compares two things by saying one:", "choices": [{"id": "a", "label": "is like the other"}, {"id": "b", "label": "is the other"}, {"id": "c", "label": "is near the other"}, {"id": "d", "label": "is bigger"}], "answer": "b", "explanation": "Yes! The answer is \"is the other\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"The wind whispered through the trees\" gives the wind human qualities, which is:", "choices": [{"id": "a", "label": "a simile"}, {"id": "b", "label": "a fact"}, {"id": "c", "label": "personification"}, {"id": "d", "label": "a hyperbole"}], "answer": "c", "explanation": "Yes! The answer is \"personification\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"I've told you a million times!\" is an exaggeration, called:", "choices": [{"id": "a", "label": "a simile"}, {"id": "b", "label": "a metaphor"}, {"id": "c", "label": "hyperbole"}, {"id": "d", "label": "onomatopoeia"}], "answer": "c", "explanation": "Yes! The answer is \"hyperbole\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Figurative Language! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$figurative-language$tl$ and t.grade_level = 5);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"river\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"teacher\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"library\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "slippery"}, {"id": "b", "label": "pencil"}, {"id": "c", "label": "scribble"}, {"id": "d", "label": "tiny"}], "answer": "b", "explanation": "Yes! The answer is \"pencil\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "explore"}, {"id": "b", "label": "golden"}, {"id": "c", "label": "gentle"}, {"id": "d", "label": "garden"}], "answer": "d", "explanation": "Yes! The answer is \"garden\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "whisper"}, {"id": "b", "label": "ancient"}, {"id": "c", "label": "curious"}, {"id": "d", "label": "engine"}], "answer": "d", "explanation": "Yes! The answer is \"engine\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 5);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action or a state of being."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"swim\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"paint\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"discover\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "curious"}, {"id": "b", "label": "scribble"}, {"id": "c", "label": "fluffy"}, {"id": "d", "label": "stormy"}], "answer": "b", "explanation": "Yes! The answer is \"scribble\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "kitchen"}, {"id": "b", "label": "brave"}, {"id": "c", "label": "window"}, {"id": "d", "label": "march"}], "answer": "d", "explanation": "Yes! The answer is \"march\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "cheerful"}, {"id": "b", "label": "window"}, {"id": "c", "label": "gallop"}, {"id": "d", "label": "narrow"}], "answer": "c", "explanation": "Yes! The answer is \"gallop\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 5);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun - what kind, how many, or which one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"slippery\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"frozen\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"shiny\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "wander"}, {"id": "b", "label": "cheerful"}, {"id": "c", "label": "teacher"}, {"id": "d", "label": "discover"}], "answer": "b", "explanation": "Yes! The answer is \"cheerful\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "golden"}, {"id": "b", "label": "kitchen"}, {"id": "c", "label": "scribble"}, {"id": "d", "label": "gallop"}], "answer": "a", "explanation": "Yes! The answer is \"golden\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "brave"}, {"id": "b", "label": "build"}, {"id": "c", "label": "whisper"}, {"id": "d", "label": "pencil"}], "answer": "a", "explanation": "Yes! The answer is \"brave\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 5);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"her\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"you\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"she\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "wander"}, {"id": "b", "label": "shout"}, {"id": "c", "label": "swim"}, {"id": "d", "label": "we"}], "answer": "d", "explanation": "Yes! The answer is \"we\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "march"}, {"id": "b", "label": "scribble"}, {"id": "c", "label": "it"}, {"id": "d", "label": "discover"}], "answer": "c", "explanation": "Yes! The answer is \"it\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "shout"}, {"id": "b", "label": "library"}, {"id": "c", "label": "I"}, {"id": "d", "label": "bounce"}], "answer": "c", "explanation": "Yes! The answer is \"I\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 5);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must agree with its subject in number."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The boy ____ every day.\"\n\nThe answer is \"plays\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The snake ____ every day.\"\n\nThe answer is \"slithers\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The clock ____ every day.\"\n\nThe answer is \"ticks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The chef ____ every day.\"", "choices": [{"id": "a", "label": "cook"}, {"id": "b", "label": "cooks"}, {"id": "c", "label": "cooksed"}, {"id": "d", "label": "cooksing"}], "answer": "b", "explanation": "Yes! The answer is \"cooks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The cat ____ every day.\"", "choices": [{"id": "a", "label": "sleep"}, {"id": "b", "label": "sleepsed"}, {"id": "c", "label": "sleeps"}, {"id": "d", "label": "sleepsing"}], "answer": "c", "explanation": "Yes! The answer is \"sleeps\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The student ____ every day.\"", "choices": [{"id": "a", "label": "read"}, {"id": "b", "label": "readsed"}, {"id": "c", "label": "reads"}, {"id": "d", "label": "readsing"}], "answer": "c", "explanation": "Yes! The answer is \"reads\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 5);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs describe actions that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"teach\"?\n\nThe answer is \"taught\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"make\"?\n\nThe answer is \"made\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"go\"?\n\nThe answer is \"went\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"give\"?\n\nThe answer is gave."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"eat\"?\n\nThe answer is ate."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"buy\"?\n\nThe answer is bought."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 5);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals show more than one, using -s, -es, or special spellings."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"cherry\".\n\nThe answer is \"cherries\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"penny\".\n\nThe answer is \"pennies\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"shelf\".\n\nThe answer is \"shelves\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"half\".\n\nThe answer is halves."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"knife\".\n\nThe answer is knives."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"box\".\n\nThe answer is boxes."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 5);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize sentence beginnings, the word I, and proper nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Nile River\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Australia\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Africa\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "mountain"}, {"id": "b", "label": "city"}, {"id": "c", "label": "month"}, {"id": "d", "label": "India"}], "answer": "d", "explanation": "Yes! The answer is \"India\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "London"}, {"id": "b", "label": "country"}, {"id": "c", "label": "day"}, {"id": "d", "label": "city"}], "answer": "a", "explanation": "Yes! The answer is \"London\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "Maria"}, {"id": "b", "label": "month"}, {"id": "c", "label": "city"}, {"id": "d", "label": "ocean"}], "answer": "a", "explanation": "Yes! The answer is \"Maria\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 5);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End sentences with a period, question mark, or exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"Can you help me___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"Where are we going___\"\n\nThe answer is \"?\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"The sky is blue___\"\n\nThe answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"She likes apples___\"", "choices": [{"id": "a", "label": "?"}, {"id": "b", "label": "!"}, {"id": "c", "label": "."}, {"id": "d", "label": ","}], "answer": "c", "explanation": "Yes! The answer is \".\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"That is amazing___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": ","}, {"id": "d", "label": "!"}], "answer": "d", "explanation": "Yes! The answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Run for your life___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "?"}, {"id": "c", "label": ","}, {"id": "d", "label": "!"}], "answer": "d", "explanation": "Yes! The answer is \"!\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 5);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "Use commas to separate three or more items in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like ham, cheese, and lettuce.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like walk, skip, and hop.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like trains, planes, and buses.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like apples grapes and plums."}, {"id": "b", "label": "I like apples, grapes and plums"}, {"id": "c", "label": "I like apples, grapes, and plums."}, {"id": "d", "label": "I like, apples grapes plums."}], "answer": "c", "explanation": "Yes! The answer is \"I like apples, grapes, and plums.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like pencils pens and markers."}, {"id": "b", "label": "I like pencils, pens and markers"}, {"id": "c", "label": "I like pencils, pens, and markers."}, {"id": "d", "label": "I like, pencils pens markers."}], "answer": "c", "explanation": "Yes! The answer is \"I like pencils, pens, and markers.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like north, south, and east."}, {"id": "b", "label": "I like north south and east."}, {"id": "c", "label": "I like north, south and east"}, {"id": "d", "label": "I like, north south east."}], "answer": "a", "explanation": "Yes! The answer is \"I like north, south, and east.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 5);

