-- =====================================================================
-- TopicLeap - richer lessons for Grade 7 (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Proportions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Proportions", "body": "A proportion sets two ratios equal. Cross-multiply to solve for the unknown."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Solve the proportion:  3/6 = 15/x .  x = ?\n\nThe answer is \"30\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Solve the proportion:  4/5 = 24/x .  x = ?\n\nThe answer is \"30\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Solve the proportion:  5/6 = 15/x .  x = ?\n\nThe answer is \"18\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Solve the proportion:  2/9 = 8/x .  x = ?\n\nThe answer is 36."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Solve the proportion:  5/8 = 20/x .  x = ?\n\nThe answer is 32."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Solve the proportion:  2/5 = 12/x .  x = ?\n\nThe answer is 30."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Proportions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$proportions$tl$ and t.grade_level = 7);

-- math: Unit Rates
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Unit Rates", "body": "A unit rate gives the amount per single unit, like miles per hour or cost per item."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A car goes 14 miles in 2 hours. What is the speed in miles per hour?\n\nThe answer is \"7\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A car goes 30 miles in 5 hours. What is the speed in miles per hour?\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A car goes 48 miles in 4 hours. What is the speed in miles per hour?\n\nThe answer is \"12\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A car goes 125 miles in 5 hours. What is the speed in miles per hour?\n\nThe answer is 25."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A car goes 85 miles in 5 hours. What is the speed in miles per hour?\n\nThe answer is 17."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A car goes 140 miles in 5 hours. What is the speed in miles per hour?\n\nThe answer is 28."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Unit Rates! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$unit-rates$tl$ and t.grade_level = 7);

-- math: Percent Problems
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Percent Problems", "body": "Use percents to solve real problems: percent of a number, discounts, tips, and increases."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is 50% of 200?\n\nThe answer is \"100\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is 25% of 200?\n\nThe answer is \"50\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is 10% of 100?\n\nThe answer is \"10\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A $400 item is 10% off. How many dollars do you save?\n\nThe answer is 40."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A $200 item is 40% off. How many dollars do you save?\n\nThe answer is 80."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A $400 item is 20% off. How many dollars do you save?\n\nThe answer is 80."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Percent Problems! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$percent-problems$tl$ and t.grade_level = 7);

-- math: Adding & Subtracting Integers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adding & Subtracting Integers", "body": "Add and subtract positive and negative numbers using a number line or rules of signs."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  1 - 7 = ?\n\nThe answer is \"-6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  -9 - 9 = ?\n\nThe answer is \"-18\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  -1 - 10 = ?\n\nThe answer is \"-11\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  -2 - 8 = ?\n\nThe answer is -10."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  -20 - 2 = ?\n\nThe answer is -22."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  -16 + 5 = ?\n\nThe answer is -11."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adding & Subtracting Integers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$add-subtract-integers$tl$ and t.grade_level = 7);

-- math: Multiplying & Dividing Integers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Multiplying & Dividing Integers", "body": "A negative times a positive is negative; a negative times a negative is positive."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  -9 x -7 = ?\n\nThe answer is \"63\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  40 / -8 = ?\n\nThe answer is \"-5\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  -5 x -4 = ?\n\nThe answer is \"20\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  -5 x -10 = ?\n\nThe answer is 50."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  -3 x -10 = ?\n\nThe answer is 30."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  -10 x 11 = ?\n\nThe answer is -110."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Multiplying & Dividing Integers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$multiply-divide-integers$tl$ and t.grade_level = 7);

-- math: Order of Operations with Integers
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Order of Operations with Integers", "body": "Follow order of operations carefully, watching the signs of negative numbers."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  5 + 9 x (-9) = ?\n\nThe answer is \"-76\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  7 + 6 x (-5) = ?\n\nThe answer is \"-23\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  2 + 7 x (-7) = ?\n\nThe answer is \"-47\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  (-4) x 9 + 7 = ?\n\nThe answer is -29."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  (-6) x 8 + 3 = ?\n\nThe answer is -45."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  (-6) x 3 + 9 = ?\n\nThe answer is -9."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Order of Operations with Integers! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$order-of-operations$tl$ and t.grade_level = 7);

-- math: Two-Step Equations
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Two-Step Equations", "body": "Undo addition or subtraction first, then multiplication or division, to solve for x."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Solve for x:  4x + 6 = 18\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Solve for x:  5x + 7 = 47\n\nThe answer is \"8\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Solve for x:  2x + 8 = 20\n\nThe answer is \"6\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Solve for x:  8x - 6 = 74\n\nThe answer is 10."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Solve for x:  2x - 13 = 7\n\nThe answer is 10."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Solve for x:  6x - 3 = 45\n\nThe answer is 8."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Two-Step Equations! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$two-step-equations$tl$ and t.grade_level = 7);

-- math: Combining Like Terms
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Combining Like Terms", "body": "Add the coefficients of like terms to simplify an expression."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Simplify:  3x + 2 + 2x\n\nThe answer is \"5x + 2\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Simplify:  3x + 4 + 6x\n\nThe answer is \"9x + 4\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Simplify:  4x + 4 + 6x\n\nThe answer is \"10x + 4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Simplify:  4x + 1 + 4x", "choices": [{"id": "a", "label": "9x"}, {"id": "b", "label": "16x + 1"}, {"id": "c", "label": "8x + 1"}, {"id": "d", "label": "8x + 2"}], "answer": "c", "explanation": "Yes! The answer is \"8x + 1\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Simplify:  4x + 5 + 4x", "choices": [{"id": "a", "label": "13x"}, {"id": "b", "label": "16x + 5"}, {"id": "c", "label": "8x + 5"}, {"id": "d", "label": "8x + 6"}], "answer": "c", "explanation": "Yes! The answer is \"8x + 5\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Simplify:  7x + 2 + 4x", "choices": [{"id": "a", "label": "11x + 3"}, {"id": "b", "label": "13x"}, {"id": "c", "label": "28x + 2"}, {"id": "d", "label": "11x + 2"}], "answer": "d", "explanation": "Yes! The answer is \"11x + 2\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Combining Like Terms! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$combining-like-terms$tl$ and t.grade_level = 7);

-- math: Area & Circumference of Circles
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Area & Circumference of Circles", "body": "Area = pi x r x r; circumference = 2 x pi x r. Use 3.14 as an estimate for pi."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Find the AREA of a circle with radius 4. Use 3.14 for pi. (area = pi x r x r)\n\nThe answer is \"50.24\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Find the AREA of a circle with radius 5. Use 3.14 for pi. (area = pi x r x r)\n\nThe answer is \"78.5\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Find the AREA of a circle with radius 4. Use 3.14 for pi. (area = pi x r x r)\n\nThe answer is \"50.24\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the AREA of a circle with radius 2. Use 3.14 for pi. (area = pi x r x r)", "choices": [{"id": "a", "label": "25.12"}, {"id": "b", "label": "6.28"}, {"id": "c", "label": "4"}, {"id": "d", "label": "12.56"}], "answer": "d", "explanation": "Yes! The answer is \"12.56\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the AREA of a circle with radius 5. Use 3.14 for pi. (area = pi x r x r)", "choices": [{"id": "a", "label": "78.5"}, {"id": "b", "label": "25"}, {"id": "c", "label": "15.7"}, {"id": "d", "label": "157"}], "answer": "a", "explanation": "Yes! The answer is \"78.5\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Find the CIRCUMFERENCE of a circle with radius 7. Use 3.14 for pi. (C = 2 x pi x r)", "choices": [{"id": "a", "label": "14"}, {"id": "b", "label": "153.86"}, {"id": "c", "label": "43.96"}, {"id": "d", "label": "21.98"}], "answer": "c", "explanation": "Yes! The answer is \"43.96\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Area & Circumference of Circles! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$circles$tl$ and t.grade_level = 7);

-- math: Volume of Prisms
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Volume of Prisms", "body": "Volume of a prism is the area of its base times its length (or height)."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A rectangular prism is 2 by 3 by 5 units. What is its volume in cubic units?\n\nThe answer is \"30\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A rectangular prism is 4 by 3 by 4 units. What is its volume in cubic units?\n\nThe answer is \"48\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A rectangular prism is 4 by 5 by 5 units. What is its volume in cubic units?\n\nThe answer is \"100\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  A rectangular prism is 6 by 2 by 7 units. What is its volume in cubic units?\n\nThe answer is 84."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  A rectangular prism is 4 by 2 by 4 units. What is its volume in cubic units?\n\nThe answer is 32."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  A rectangular prism is 8 by 3 by 4 units. What is its volume in cubic units?\n\nThe answer is 96."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Volume of Prisms! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$volume-of-prisms$tl$ and t.grade_level = 7);

-- science: Photosynthesis & Respiration
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Photosynthesis & Respiration", "body": "Plants make food in photosynthesis; cells release that energy in respiration."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  In photosynthesis, plants use sunlight, water, and carbon dioxide to make:\n\nThe answer is \"glucose (sugar) and oxygen\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which gas do plants take IN during photosynthesis?\n\nThe answer is \"carbon dioxide\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which gas do plants RELEASE during photosynthesis?\n\nThe answer is \"oxygen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Cellular respiration releases energy from food using:", "choices": [{"id": "a", "label": "sunlight"}, {"id": "b", "label": "soil"}, {"id": "c", "label": "nitrogen"}, {"id": "d", "label": "oxygen"}], "answer": "d", "explanation": "Yes! The answer is \"oxygen\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Respiration produces carbon dioxide, water, and:", "choices": [{"id": "a", "label": "sugar"}, {"id": "b", "label": "energy (ATP)"}, {"id": "c", "label": "soil"}, {"id": "d", "label": "sunlight"}], "answer": "b", "explanation": "Yes! The answer is \"energy (ATP)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Photosynthesis happens in plant cell parts called:", "choices": [{"id": "a", "label": "mitochondria"}, {"id": "b", "label": "nuclei"}, {"id": "c", "label": "chloroplasts"}, {"id": "d", "label": "ribosomes"}], "answer": "c", "explanation": "Yes! The answer is \"chloroplasts\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Photosynthesis & Respiration! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$photosynthesis-respiration$tl$ and t.grade_level = 7);

-- science: Matter & Energy in Ecosystems
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Matter & Energy in Ecosystems", "body": "Energy flows one way and is lost as heat; matter is recycled through ecosystems."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Energy enters most ecosystems as:\n\nThe answer is \"sunlight\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Matter such as carbon and water is:\n\nThe answer is \"recycled through the ecosystem\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Energy moves through an ecosystem and is mostly lost as:\n\nThe answer is \"heat\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Decomposers return nutrients (matter) to the:", "choices": [{"id": "a", "label": "Sun"}, {"id": "b", "label": "atmosphere only"}, {"id": "c", "label": "ocean only"}, {"id": "d", "label": "soil"}], "answer": "d", "explanation": "Yes! The answer is \"soil\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An energy pyramid shows that available energy decreases as you go:", "choices": [{"id": "a", "label": "down the levels"}, {"id": "b", "label": "into the Sun"}, {"id": "c", "label": "up the levels"}, {"id": "d", "label": "sideways"}], "answer": "c", "explanation": "Yes! The answer is \"up the levels\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "About how much energy passes to the next trophic level?", "choices": [{"id": "a", "label": "roughly 10%"}, {"id": "b", "label": "100%"}, {"id": "c", "label": "90%"}, {"id": "d", "label": "0%"}], "answer": "a", "explanation": "Yes! The answer is \"roughly 10%\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Matter & Energy in Ecosystems! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$matter-and-energy-in-ecosystems$tl$ and t.grade_level = 7);

-- science: Natural Selection
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Natural Selection", "body": "Helpful inherited traits become more common over generations as organisms survive."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Traits that help an organism survive and reproduce are:\n\nThe answer is \"favored by natural selection\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Differences among individuals of a species are called:\n\nThe answer is \"variation\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Organisms with helpful traits are more likely to:\n\nThe answer is \"survive and have offspring\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Over many generations, helpful traits become:", "choices": [{"id": "a", "label": "less common"}, {"id": "b", "label": "more common"}, {"id": "c", "label": "random"}, {"id": "d", "label": "extinct"}], "answer": "b", "explanation": "Yes! The answer is \"more common\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A heritable trait that improves survival is an:", "choices": [{"id": "a", "label": "accident"}, {"id": "b", "label": "habitat"}, {"id": "c", "label": "fossil"}, {"id": "d", "label": "adaptation"}], "answer": "d", "explanation": "Yes! The answer is \"adaptation\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Natural selection acts on traits that are:", "choices": [{"id": "a", "label": "learned in life"}, {"id": "b", "label": "inherited"}, {"id": "c", "label": "painted on"}, {"id": "d", "label": "temporary"}], "answer": "b", "explanation": "Yes! The answer is \"inherited\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Natural Selection! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$natural-selection$tl$ and t.grade_level = 7);

-- science: Heredity & Genes
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Heredity & Genes", "body": "Genes made of DNA carry traits from parents to offspring; alleles can be dominant or recessive."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The molecule that carries genetic information is:\n\nThe answer is \"DNA\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A segment of DNA that codes for a trait is a:\n\nThe answer is \"gene\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Offspring inherit genes from:\n\nThe answer is \"both parents\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Different versions of a gene are called:", "choices": [{"id": "a", "label": "cells"}, {"id": "b", "label": "proteins"}, {"id": "c", "label": "organs"}, {"id": "d", "label": "alleles"}], "answer": "d", "explanation": "Yes! The answer is \"alleles\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A trait that is expressed when at least one allele is present is:", "choices": [{"id": "a", "label": "recessive"}, {"id": "b", "label": "dominant"}, {"id": "c", "label": "blended"}, {"id": "d", "label": "extinct"}], "answer": "b", "explanation": "Yes! The answer is \"dominant\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A trait shown only when both alleles match is:", "choices": [{"id": "a", "label": "dominant"}, {"id": "b", "label": "mutated"}, {"id": "c", "label": "recessive"}, {"id": "d", "label": "learned"}], "answer": "c", "explanation": "Yes! The answer is \"recessive\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Heredity & Genes! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$heredity-and-genes$tl$ and t.grade_level = 7);

-- science: Chemical Reactions
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Chemical Reactions", "body": "Reactions rearrange atoms to form new substances while conserving mass."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  In a chemical reaction, the starting substances are the:\n\nThe answer is \"reactants\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The new substances formed are the:\n\nThe answer is \"products\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A chemical reaction forms substances with:\n\nThe answer is \"new properties\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "In any reaction, the total mass of reactants equals the total mass of:", "choices": [{"id": "a", "label": "nothing"}, {"id": "b", "label": "products"}, {"id": "c", "label": "the catalyst"}, {"id": "d", "label": "the gas only"}], "answer": "b", "explanation": "Yes! The answer is \"products\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "This equality of mass is the law of:", "choices": [{"id": "a", "label": "gravity"}, {"id": "b", "label": "conservation of mass"}, {"id": "c", "label": "motion"}, {"id": "d", "label": "reflection"}], "answer": "b", "explanation": "Yes! The answer is \"conservation of mass\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signs of a chemical change include a color change, gas, light, or:", "choices": [{"id": "a", "label": "a new shape only"}, {"id": "b", "label": "temperature change"}, {"id": "c", "label": "melting only"}, {"id": "d", "label": "dissolving only"}], "answer": "b", "explanation": "Yes! The answer is \"temperature change\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Chemical Reactions! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$chemical-reactions$tl$ and t.grade_level = 7);

-- science: Atoms & the Periodic Table
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Atoms & the Periodic Table", "body": "Atoms are made of protons, neutrons, and electrons; the periodic table organizes the elements."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The smallest unit of an element is an:\n\nThe answer is \"atom\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The center of an atom is the:\n\nThe answer is \"nucleus\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Positively charged particles in the nucleus are:\n\nThe answer is \"protons\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Particles in the nucleus with no charge are:", "choices": [{"id": "a", "label": "protons"}, {"id": "b", "label": "neutrons"}, {"id": "c", "label": "electrons"}, {"id": "d", "label": "photons"}], "answer": "b", "explanation": "Yes! The answer is \"neutrons\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Negatively charged particles outside the nucleus are:", "choices": [{"id": "a", "label": "electrons"}, {"id": "b", "label": "protons"}, {"id": "c", "label": "neutrons"}, {"id": "d", "label": "atoms"}], "answer": "a", "explanation": "Yes! The answer is \"electrons\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The number of protons in an atom is its:", "choices": [{"id": "a", "label": "mass number"}, {"id": "b", "label": "atomic number"}, {"id": "c", "label": "charge"}, {"id": "d", "label": "weight"}], "answer": "b", "explanation": "Yes! The answer is \"atomic number\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Atoms & the Periodic Table! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$atoms-and-periodic-table$tl$ and t.grade_level = 7);

-- science: Newton's Laws of Motion
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Newton's Laws of Motion", "body": "Newton's three laws describe inertia, force = mass x acceleration, and action-reaction."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An object stays at rest or in motion unless acted on by a force. This is:\n\nThe answer is \"Newton's first law (inertia)\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The resistance of an object to a change in motion is:\n\nThe answer is \"inertia\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Force equals mass times acceleration is:\n\nThe answer is \"Newton's second law\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "For every action there is an equal and opposite reaction is:", "choices": [{"id": "a", "label": "the first law"}, {"id": "b", "label": "the second law"}, {"id": "c", "label": "Newton's third law"}, {"id": "d", "label": "inertia"}], "answer": "c", "explanation": "Yes! The answer is \"Newton's third law\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "If mass stays the same and force increases, acceleration:", "choices": [{"id": "a", "label": "decreases"}, {"id": "b", "label": "increases"}, {"id": "c", "label": "stays zero"}, {"id": "d", "label": "reverses time"}], "answer": "b", "explanation": "Yes! The answer is \"increases\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A heavier object needs ____ force to reach the same acceleration as a lighter one.", "choices": [{"id": "a", "label": "less"}, {"id": "b", "label": "no"}, {"id": "c", "label": "negative"}, {"id": "d", "label": "more"}], "answer": "d", "explanation": "Yes! The answer is \"more\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Newton's Laws of Motion! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$newtons-laws$tl$ and t.grade_level = 7);

-- science: Energy & Heat
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Energy & Heat", "body": "Energy changes form and is conserved; heat moves by conduction, convection, and radiation."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Heat naturally flows from ____ objects to colder ones.\n\nThe answer is \"hotter\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Thermal energy is related to the motion of an object's:\n\nThe answer is \"particles\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Heat transfer through direct contact is:\n\nThe answer is \"conduction\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Heat transfer by moving fluids (liquids/gases) is:", "choices": [{"id": "a", "label": "conduction"}, {"id": "b", "label": "radiation"}, {"id": "c", "label": "convection"}, {"id": "d", "label": "reflection"}], "answer": "c", "explanation": "Yes! The answer is \"convection\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Heat transfer by waves through space is:", "choices": [{"id": "a", "label": "conduction"}, {"id": "b", "label": "convection"}, {"id": "c", "label": "friction"}, {"id": "d", "label": "radiation"}], "answer": "d", "explanation": "Yes! The answer is \"radiation\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A material that slows heat transfer is an:", "choices": [{"id": "a", "label": "conductor"}, {"id": "b", "label": "catalyst"}, {"id": "c", "label": "insulator"}, {"id": "d", "label": "ion"}], "answer": "c", "explanation": "Yes! The answer is \"insulator\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Energy & Heat! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$energy-and-heat$tl$ and t.grade_level = 7);

-- science: Waves
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Waves", "body": "Waves carry energy; amplitude, wavelength, and frequency describe them."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A wave transfers ____ from one place to another.\n\nThe answer is \"energy\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The height of a wave from rest to crest is its:\n\nThe answer is \"amplitude\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  The distance between two crests is the:\n\nThe answer is \"wavelength\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The number of waves passing a point per second is the:", "choices": [{"id": "a", "label": "frequency"}, {"id": "b", "label": "amplitude"}, {"id": "c", "label": "wavelength"}, {"id": "d", "label": "speed"}], "answer": "a", "explanation": "Yes! The answer is \"frequency\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Sound waves need a ____ to travel.", "choices": [{"id": "a", "label": "medium (like air)"}, {"id": "b", "label": "vacuum"}, {"id": "c", "label": "shadow"}, {"id": "d", "label": "magnet"}], "answer": "a", "explanation": "Yes! The answer is \"medium (like air)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Light waves can travel through:", "choices": [{"id": "a", "label": "only water"}, {"id": "b", "label": "only metal"}, {"id": "c", "label": "empty space (a vacuum)"}, {"id": "d", "label": "only air"}], "answer": "c", "explanation": "Yes! The answer is \"empty space (a vacuum)\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Waves! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$waves$tl$ and t.grade_level = 7);

-- science: Human Impact on Earth
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Human Impact on Earth", "body": "Human activities affect Earth's systems; conservation and clean energy reduce harm."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Burning fossil fuels increases carbon dioxide, contributing to:\n\nThe answer is \"climate change\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Cutting down forests for land is called:\n\nThe answer is \"deforestation\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A way to reduce waste is to reduce, reuse, and:\n\nThe answer is \"recycle\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Renewable resources include solar, wind, and:", "choices": [{"id": "a", "label": "coal"}, {"id": "b", "label": "oil"}, {"id": "c", "label": "natural gas"}, {"id": "d", "label": "hydropower"}], "answer": "d", "explanation": "Yes! The answer is \"hydropower\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Pollution that runs off into rivers and oceans harms:", "choices": [{"id": "a", "label": "only the air"}, {"id": "b", "label": "aquatic life"}, {"id": "c", "label": "only rocks"}, {"id": "d", "label": "nothing"}], "answer": "b", "explanation": "Yes! The answer is \"aquatic life\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Protecting many species and ecosystems preserves:", "choices": [{"id": "a", "label": "pollution"}, {"id": "b", "label": "traffic"}, {"id": "c", "label": "biodiversity"}, {"id": "d", "label": "erosion"}], "answer": "c", "explanation": "Yes! The answer is \"biodiversity\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Human Impact on Earth! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$human-impact$tl$ and t.grade_level = 7);

-- reading: Central Idea & Analysis
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Central Idea & Analysis", "body": "Determine a central idea and analyze how details develop it over the text."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The central idea of a text is the:\n\nThe answer is \"most important overall point\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Supporting details function to:\n\nThe answer is \"develop and explain the central idea\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text may develop its central idea over:\n\nThe answer is \"the whole passage\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Renewable energy is growing because it is cleaner, increasingly cheaper, and more reliable than before.\" The central idea is that renewable energy is:", "choices": [{"id": "a", "label": "expensive"}, {"id": "b", "label": "becoming more practical and appealing"}, {"id": "c", "label": "useless"}, {"id": "d", "label": "disappearing"}], "answer": "b", "explanation": "Yes! The answer is \"becoming more practical and appealing\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To determine a central idea, a strong reader looks for the point that:", "choices": [{"id": "a", "label": "the details all support"}, {"id": "b", "label": "appears only once"}, {"id": "c", "label": "is in the title"}, {"id": "d", "label": "is the shortest"}], "answer": "a", "explanation": "Yes! The answer is \"the details all support\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "An objective summary of a central idea avoids the reader's:", "choices": [{"id": "a", "label": "main point"}, {"id": "b", "label": "key details"}, {"id": "c", "label": "personal opinions"}, {"id": "d", "label": "topic"}], "answer": "c", "explanation": "Yes! The answer is \"personal opinions\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Central Idea & Analysis! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$central-idea$tl$ and t.grade_level = 7);

-- reading: Theme Development
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Theme Development", "body": "Trace how a theme develops through the plot and characters' choices."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A theme is a story's:\n\nThe answer is \"central message about life\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Authors develop theme through plot events and:\n\nThe answer is \"character choices\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Theme differs from topic because theme is a:\n\nThe answer is \"complete idea or insight\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"Though warned, the crew ignored the storm signs and lost their ship.\" A theme is:", "choices": [{"id": "a", "label": "ignoring wisdom has consequences"}, {"id": "b", "label": "storms are fun"}, {"id": "c", "label": "ships are old"}, {"id": "d", "label": "sailing is easy"}], "answer": "a", "explanation": "Yes! The answer is \"ignoring wisdom has consequences\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A recurring symbol in a story often reinforces the:", "choices": [{"id": "a", "label": "index"}, {"id": "b", "label": "glossary"}, {"id": "c", "label": "theme"}, {"id": "d", "label": "page count"}], "answer": "c", "explanation": "Yes! The answer is \"theme\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To trace theme development, note how it appears:", "choices": [{"id": "a", "label": "only at the start"}, {"id": "b", "label": "across the whole text"}, {"id": "c", "label": "in the title only"}, {"id": "d", "label": "never"}], "answer": "b", "explanation": "Yes! The answer is \"across the whole text\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Theme Development! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$theme-development$tl$ and t.grade_level = 7);

-- reading: Objective Summary
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Objective Summary", "body": "Summarize a text's central idea and key points objectively, without opinion."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An objective summary should remain:\n\nThe answer is \"neutral and factual\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A summary is ____ than the original.\n\nThe answer is \"shorter\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A good summary captures the central idea and the:\n\nThe answer is \"most important details\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Summaries should be written in:", "choices": [{"id": "a", "label": "the author's exact words"}, {"id": "b", "label": "code"}, {"id": "c", "label": "your own words"}, {"id": "d", "label": "emojis"}], "answer": "c", "explanation": "Yes! The answer is \"your own words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What should be LEFT OUT of an objective summary?", "choices": [{"id": "a", "label": "the main idea"}, {"id": "b", "label": "key points"}, {"id": "c", "label": "your personal reaction"}, {"id": "d", "label": "the topic"}], "answer": "c", "explanation": "Yes! The answer is \"your personal reaction\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Narrative summaries keep events in:", "choices": [{"id": "a", "label": "logical order"}, {"id": "b", "label": "random order"}, {"id": "c", "label": "reverse only"}, {"id": "d", "label": "no order"}], "answer": "a", "explanation": "Yes! The answer is \"logical order\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Objective Summary! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$summarizing$tl$ and t.grade_level = 7);

-- reading: Textual Evidence & Inference
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Textual Evidence & Inference", "body": "Cite specific evidence to support both explicit answers and inferences."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Textual evidence is information taken ____ from the text.\n\nThe answer is \"directly\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  To support an inference, you must cite:\n\nThe answer is \"evidence from the text\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Strong evidence is both relevant and:\n\nThe answer is \"accurate (truly in the text)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Quotation marks indicate words that are the:", "choices": [{"id": "a", "label": "your words"}, {"id": "b", "label": "a summary"}, {"id": "c", "label": "author's exact words"}, {"id": "d", "label": "a title"}], "answer": "c", "explanation": "Yes! The answer is \"author's exact words\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which best supports the claim 'the character felt anxious'?", "choices": [{"id": "a", "label": "The book is long."}, {"id": "b", "label": "It was Friday."}, {"id": "c", "label": "'Her hands trembled and her voice shook.'"}, {"id": "d", "label": "The cover is red."}], "answer": "c", "explanation": "Yes! The answer is \"'Her hands trembled and her voice shook.'\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When asked 'how do you know?', a strong reader:", "choices": [{"id": "a", "label": "guesses"}, {"id": "b", "label": "ignores the text"}, {"id": "c", "label": "points to text evidence"}, {"id": "d", "label": "changes topic"}], "answer": "c", "explanation": "Yes! The answer is \"points to text evidence\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Textual Evidence & Inference! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$textual-evidence$tl$ and t.grade_level = 7);

-- reading: Author's Purpose & Perspective
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Author's Purpose & Perspective", "body": "Analyze an author's purpose, perspective, and how word choice reveals it."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  An author's purpose may be to inform, entertain, or:\n\nThe answer is \"persuade\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  An author's perspective is their:\n\nThe answer is \"attitude toward the topic\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  An editorial mainly expresses the writer's:\n\nThe answer is \"opinion\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Loaded or emotional word choices reveal the author's:", "choices": [{"id": "a", "label": "page number"}, {"id": "b", "label": "font"}, {"id": "c", "label": "binding"}, {"id": "d", "label": "bias / perspective"}], "answer": "d", "explanation": "Yes! The answer is \"bias / perspective\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text presenting only one side of an issue is likely:", "choices": [{"id": "a", "label": "objective"}, {"id": "b", "label": "biased"}, {"id": "c", "label": "fictional"}, {"id": "d", "label": "a poem"}], "answer": "b", "explanation": "Yes! The answer is \"biased\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "To find an author's purpose, ask:", "choices": [{"id": "a", "label": "how long is it?"}, {"id": "b", "label": "why did they write this?"}, {"id": "c", "label": "who printed it?"}, {"id": "d", "label": "what font?"}], "answer": "b", "explanation": "Yes! The answer is \"why did they write this?\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Author's Purpose & Perspective! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$authors-perspective$tl$ and t.grade_level = 7);

-- reading: Word Meaning & Connotation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Word Meaning & Connotation", "body": "Distinguish denotation from connotation and use clues, roots, and affixes for meaning."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A word's denotation is its:\n\nThe answer is \"dictionary meaning\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A word's connotation is the:\n\nThe answer is \"feeling or association it carries\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  'Thrifty' and 'cheap' have similar denotations but different:\n\nThe answer is \"connotations\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word has a more POSITIVE connotation?", "choices": [{"id": "a", "label": "scrawny"}, {"id": "b", "label": "skinny"}, {"id": "c", "label": "bony"}, {"id": "d", "label": "slender"}], "answer": "d", "explanation": "Yes! The answer is \"slender\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word has a more NEGATIVE connotation?", "choices": [{"id": "a", "label": "determined"}, {"id": "b", "label": "persistent"}, {"id": "c", "label": "firm"}, {"id": "d", "label": "stubborn"}], "answer": "d", "explanation": "Yes! The answer is \"stubborn\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Read: \"The aroma of bread filled the kitchen.\" \"Aroma\" has a ____ connotation.", "choices": [{"id": "a", "label": "negative"}, {"id": "b", "label": "positive"}, {"id": "c", "label": "neutral only"}, {"id": "d", "label": "no"}], "answer": "b", "explanation": "Yes! The answer is \"positive\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Word Meaning & Connotation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$word-connotation$tl$ and t.grade_level = 7);

-- reading: Text Structure
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Text Structure", "body": "Analyze how an author organizes a text and how the structure shapes ideas."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  A text organized by time order uses a ____ structure.\n\nThe answer is \"chronological / sequence\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A text explaining reasons and results uses:\n\nThe answer is \"cause and effect\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A text showing similarities and differences uses:\n\nThe answer is \"compare and contrast\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A text presenting an issue and remedies uses:", "choices": [{"id": "a", "label": "problem and solution"}, {"id": "b", "label": "sequence"}, {"id": "c", "label": "description"}, {"id": "d", "label": "compare"}], "answer": "a", "explanation": "Yes! The answer is \"problem and solution\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'because, therefore, as a result' indicate:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "compare"}, {"id": "c", "label": "cause and effect"}, {"id": "d", "label": "description"}], "answer": "c", "explanation": "Yes! The answer is \"cause and effect\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Signal words 'however, similarly, unlike' indicate:", "choices": [{"id": "a", "label": "sequence"}, {"id": "b", "label": "cause-effect"}, {"id": "c", "label": "compare and contrast"}, {"id": "d", "label": "problem-solution"}], "answer": "c", "explanation": "Yes! The answer is \"compare and contrast\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Text Structure! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$text-structure$tl$ and t.grade_level = 7);

-- reading: Figurative Language & Tone
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Figurative Language & Tone", "body": "Identify figurative language and analyze how word choice creates tone and mood."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  \"The city never sleeps\" gives the city a human trait, so it is:\n\nThe answer is \"personification\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  \"As cold as ice\" is a:\n\nThe answer is \"simile\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  \"Her words were daggers\" is a:\n\nThe answer is \"metaphor\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "\"I've said this a thousand times\" is an exaggeration called:", "choices": [{"id": "a", "label": "hyperbole"}, {"id": "b", "label": "simile"}, {"id": "c", "label": "metaphor"}, {"id": "d", "label": "idiom"}], "answer": "a", "explanation": "Yes! The answer is \"hyperbole\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "'Hit the books' meaning to study is an:", "choices": [{"id": "a", "label": "idiom"}, {"id": "b", "label": "literal action"}, {"id": "c", "label": "simile"}, {"id": "d", "label": "fact"}], "answer": "a", "explanation": "Yes! The answer is \"idiom\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tone is the author's ____ toward the subject.", "choices": [{"id": "a", "label": "attitude"}, {"id": "b", "label": "page count"}, {"id": "c", "label": "font"}, {"id": "d", "label": "spelling"}], "answer": "a", "explanation": "Yes! The answer is \"attitude\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Figurative Language & Tone! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$figurative-tone$tl$ and t.grade_level = 7);

-- reading: Comparing Authors & Accounts
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Comparing Authors & Accounts", "body": "Compare how different authors present the same topic or event."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Comparing two texts on a topic reveals their different:\n\nThe answer is \"approaches and viewpoints\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  A memoir and a news article on the same event differ most in:\n\nThe answer is \"perspective and tone\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Two authors may share facts yet reach different:\n\nThe answer is \"conclusions\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Reading multiple sources helps a reader:", "choices": [{"id": "a", "label": "learn less"}, {"id": "b", "label": "ignore facts"}, {"id": "c", "label": "form a fuller, balanced view"}, {"id": "d", "label": "memorize fonts"}], "answer": "c", "explanation": "Yes! The answer is \"form a fuller, balanced view\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A primary source is an account from:", "choices": [{"id": "a", "label": "someone who experienced the event"}, {"id": "b", "label": "a later textbook only"}, {"id": "c", "label": "fiction always"}, {"id": "d", "label": "an unrelated topic"}], "answer": "a", "explanation": "Yes! The answer is \"someone who experienced the event\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A secondary source typically:", "choices": [{"id": "a", "label": "is always firsthand"}, {"id": "b", "label": "analyzes events after the fact"}, {"id": "c", "label": "is fiction"}, {"id": "d", "label": "has no facts"}], "answer": "b", "explanation": "Yes! The answer is \"analyzes events after the fact\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Comparing Authors & Accounts! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$compare-authors$tl$ and t.grade_level = 7);

-- reading: Plot & Character Development
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plot & Character Development", "body": "Analyze how plot events and characters develop and interact over a story."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  The sequence of events in a story is the:\n\nThe answer is \"plot\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  The central problem characters face is the:\n\nThe answer is \"conflict\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  A character who changes over the story is:\n\nThe answer is \"dynamic\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A character who stays the same is:", "choices": [{"id": "a", "label": "dynamic"}, {"id": "b", "label": "static"}, {"id": "c", "label": "the protagonist always"}, {"id": "d", "label": "the villain"}], "answer": "b", "explanation": "Yes! The answer is \"static\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "The turning point of greatest tension is the:", "choices": [{"id": "a", "label": "exposition"}, {"id": "b", "label": "climax"}, {"id": "c", "label": "resolution"}, {"id": "d", "label": "setting"}], "answer": "b", "explanation": "Yes! The answer is \"climax\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Events that build tension before the climax are the:", "choices": [{"id": "a", "label": "resolution"}, {"id": "b", "label": "rising action"}, {"id": "c", "label": "exposition"}, {"id": "d", "label": "falling action"}], "answer": "b", "explanation": "Yes! The answer is \"rising action\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plot & Character Development! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$plot-character-development$tl$ and t.grade_level = 7);

-- writing: Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Nouns", "body": "A noun names a person, place, thing, or idea."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"balloon\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"blanket\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a noun (a person, place, or thing)?\n\nThe answer is \"mountain\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "scribble"}, {"id": "b", "label": "garden"}, {"id": "c", "label": "gentle"}, {"id": "d", "label": "narrow"}], "answer": "b", "explanation": "Yes! The answer is \"garden\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "swim"}, {"id": "b", "label": "stretch"}, {"id": "c", "label": "island"}, {"id": "d", "label": "curious"}], "answer": "c", "explanation": "Yes! The answer is \"island\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a noun (a person, place, or thing)?", "choices": [{"id": "a", "label": "shiny"}, {"id": "b", "label": "shout"}, {"id": "c", "label": "window"}, {"id": "d", "label": "stretch"}], "answer": "c", "explanation": "Yes! The answer is \"window\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$nouns$tl$ and t.grade_level = 7);

-- writing: Action Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Action Verbs", "body": "A verb shows action or a state of being."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an action verb (something you can do)?\n\nThe answer is \"march\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an action verb (something you can do)?\n\nThe answer is \"bounce\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an action verb (something you can do)?\n\nThe answer is \"shout\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "wander"}, {"id": "b", "label": "garden"}, {"id": "c", "label": "tiny"}, {"id": "d", "label": "mountain"}], "answer": "a", "explanation": "Yes! The answer is \"wander\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "cheerful"}, {"id": "b", "label": "enormous"}, {"id": "c", "label": "slippery"}, {"id": "d", "label": "build"}], "answer": "d", "explanation": "Yes! The answer is \"build\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an action verb (something you can do)?", "choices": [{"id": "a", "label": "discover"}, {"id": "b", "label": "frozen"}, {"id": "c", "label": "slippery"}, {"id": "d", "label": "gentle"}], "answer": "a", "explanation": "Yes! The answer is \"discover\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Action Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$action-verbs$tl$ and t.grade_level = 7);

-- writing: Adjectives
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adjectives", "body": "An adjective describes a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"slippery\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"gentle\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is an adjective (it describes a noun)?\n\nThe answer is \"fluffy\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "scribble"}, {"id": "b", "label": "river"}, {"id": "c", "label": "enormous"}, {"id": "d", "label": "pencil"}], "answer": "c", "explanation": "Yes! The answer is \"enormous\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "teacher"}, {"id": "b", "label": "march"}, {"id": "c", "label": "ancient"}, {"id": "d", "label": "island"}], "answer": "c", "explanation": "Yes! The answer is \"ancient\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is an adjective (it describes a noun)?", "choices": [{"id": "a", "label": "gallop"}, {"id": "b", "label": "brave"}, {"id": "c", "label": "scribble"}, {"id": "d", "label": "island"}], "answer": "b", "explanation": "Yes! The answer is \"brave\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adjectives! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$adjectives$tl$ and t.grade_level = 7);

-- writing: Pronouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Pronouns", "body": "A pronoun takes the place of a noun."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"them\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"you\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is a pronoun (it takes the place of a noun)?\n\nThe answer is \"they\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "jump"}, {"id": "b", "label": "gallop"}, {"id": "c", "label": "march"}, {"id": "d", "label": "it"}], "answer": "d", "explanation": "Yes! The answer is \"it\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "build"}, {"id": "b", "label": "mountain"}, {"id": "c", "label": "us"}, {"id": "d", "label": "gallop"}], "answer": "c", "explanation": "Yes! The answer is \"us\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is a pronoun (it takes the place of a noun)?", "choices": [{"id": "a", "label": "kitchen"}, {"id": "b", "label": "engine"}, {"id": "c", "label": "farmer"}, {"id": "d", "label": "I"}], "answer": "d", "explanation": "Yes! The answer is \"I\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Pronouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$pronouns$tl$ and t.grade_level = 7);

-- writing: Subject-Verb Agreement
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Subject-Verb Agreement", "body": "The verb must agree with its subject in number."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Choose the correct verb: \"The singer ____ every day.\"\n\nThe answer is \"performs\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Choose the correct verb: \"The river ____ every day.\"\n\nThe answer is \"flows\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Choose the correct verb: \"The student ____ every day.\"\n\nThe answer is \"reads\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The puppy ____ every day.\"", "choices": [{"id": "a", "label": "wag"}, {"id": "b", "label": "wagsed"}, {"id": "c", "label": "wagsing"}, {"id": "d", "label": "wags"}], "answer": "d", "explanation": "Yes! The answer is \"wags\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The chef ____ every day.\"", "choices": [{"id": "a", "label": "cooks"}, {"id": "b", "label": "cook"}, {"id": "c", "label": "cooksed"}, {"id": "d", "label": "cooksing"}], "answer": "a", "explanation": "Yes! The answer is \"cooks\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Choose the correct verb: \"The cat ____ every day.\"", "choices": [{"id": "a", "label": "sleep"}, {"id": "b", "label": "sleeps"}, {"id": "c", "label": "sleepsed"}, {"id": "d", "label": "sleepsing"}], "answer": "b", "explanation": "Yes! The answer is \"sleeps\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Subject-Verb Agreement! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$subject-verb-agreement$tl$ and t.grade_level = 7);

-- writing: Past-Tense Verbs
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Past-Tense Verbs", "body": "Past-tense verbs describe actions that already happened."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the past tense of the verb \"drink\"?\n\nThe answer is \"drank\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the past tense of the verb \"go\"?\n\nThe answer is \"went\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the past tense of the verb \"write\"?\n\nThe answer is \"wrote\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  What is the past tense of the verb \"sing\"?\n\nThe answer is sang."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  What is the past tense of the verb \"draw\"?\n\nThe answer is drew."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  What is the past tense of the verb \"see\"?\n\nThe answer is saw."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Past-Tense Verbs! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$past-tense-verbs$tl$ and t.grade_level = 7);

-- writing: Plural Nouns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Plural Nouns", "body": "Plurals show more than one."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Write the plural of \"bus\".\n\nThe answer is \"buses\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Write the plural of \"glass\".\n\nThe answer is \"glasses\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Write the plural of \"wolf\".\n\nThe answer is \"wolves\"."}, {"type": "worked_example", "title": "Worked example 4", "body": "Example 4.  Write the plural of \"cherry\".\n\nThe answer is cherries."}, {"type": "worked_example", "title": "Worked example 5", "body": "Example 5.  Write the plural of \"city\".\n\nThe answer is cities."}, {"type": "worked_example", "title": "Worked example 6", "body": "Example 6.  Write the plural of \"branch\".\n\nThe answer is branches."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Plural Nouns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$plural-nouns$tl$ and t.grade_level = 7);

-- writing: Capitalization
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Capitalization", "body": "Capitalize sentence beginnings, I, and proper nouns."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Amazon River\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Mount Everest\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word or phrase is a proper noun that must be capitalized?\n\nThe answer is \"Monday\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "Nile River"}, {"id": "b", "label": "friend"}, {"id": "c", "label": "river"}, {"id": "d", "label": "day"}], "answer": "a", "explanation": "Yes! The answer is \"Nile River\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "river"}, {"id": "b", "label": "Saturn"}, {"id": "c", "label": "mountain"}, {"id": "d", "label": "day"}], "answer": "b", "explanation": "Yes! The answer is \"Saturn\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word or phrase is a proper noun that must be capitalized?", "choices": [{"id": "a", "label": "friend"}, {"id": "b", "label": "month"}, {"id": "c", "label": "Australia"}, {"id": "d", "label": "city"}], "answer": "c", "explanation": "Yes! The answer is \"Australia\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Capitalization! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$capitalization$tl$ and t.grade_level = 7);

-- writing: End Punctuation
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: End Punctuation", "body": "End sentences with a period, question mark, or exclamation point."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which end mark best completes the sentence?  \"Run for your life___\"\n\nThe answer is \"!\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which end mark best completes the sentence?  \"What a great show___\"\n\nThe answer is \"!\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which end mark best completes the sentence?  \"What time is it___\"\n\nThe answer is \"?\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"That is amazing___\"", "choices": [{"id": "a", "label": "!"}, {"id": "b", "label": "."}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"We won the game___\"", "choices": [{"id": "a", "label": "!"}, {"id": "b", "label": "."}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "a", "explanation": "Yes! The answer is \"!\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which end mark best completes the sentence?  \"Watch out___\"", "choices": [{"id": "a", "label": "."}, {"id": "b", "label": "!"}, {"id": "c", "label": "?"}, {"id": "d", "label": ","}], "answer": "b", "explanation": "Yes! The answer is \"!\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about End Punctuation! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$end-punctuation$tl$ and t.grade_level = 7);

-- writing: Commas in a Series
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Commas in a Series", "body": "Use commas to separate three or more items in a list."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like gold, silver, and bronze.\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like piano, drums, and guitar.\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which sentence uses commas correctly in a list?\n\nThe answer is \"I like run, jump, and swim.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like red green and blue."}, {"id": "b", "label": "I like red, green and blue"}, {"id": "c", "label": "I like, red green blue."}, {"id": "d", "label": "I like red, green, and blue."}], "answer": "d", "explanation": "Yes! The answer is \"I like red, green, and blue.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like milk, eggs, and bread."}, {"id": "b", "label": "I like milk eggs and bread."}, {"id": "c", "label": "I like milk, eggs and bread"}, {"id": "d", "label": "I like, milk eggs bread."}], "answer": "a", "explanation": "Yes! The answer is \"I like milk, eggs, and bread.\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which sentence uses commas correctly in a list?", "choices": [{"id": "a", "label": "I like apples oranges and pears."}, {"id": "b", "label": "I like apples, oranges and pears"}, {"id": "c", "label": "I like apples, oranges, and pears."}, {"id": "d", "label": "I like, apples oranges pears."}], "answer": "c", "explanation": "Yes! The answer is \"I like apples, oranges, and pears.\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Commas in a Series! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$writing$tl$ and t.slug = $tl$commas-in-a-series$tl$ and t.grade_level = 7);

