-- =====================================================================
-- TopicLeap - richer lessons for Kindergarten (UPDATE existing lessons)
-- Replaces each lesson's steps with a longer, swipeable version.
-- Non-destructive: only updates lessons.steps. Safe to re-run.
-- =====================================================================

-- math: Counting to 10
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Counting to 10", "body": "Count the pictures one by one to find how many there are, all the way up to 10."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  How many do you see?  \ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\ud83c\udf38\n\nThe answer is \"9\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  How many do you see?  \ud83d\udc36\ud83d\udc36\ud83d\udc36\ud83d\udc36\ud83d\udc36\n\nThe answer is \"5\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  How many do you see?  \ud83d\udc36\ud83d\udc36\ud83d\udc36\ud83d\udc36\ud83d\udc36\ud83d\udc36\n\nThe answer is \"6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "How many do you see?  \ud83d\ude97\ud83d\ude97", "choices": [{"id": "a", "label": "4"}, {"id": "b", "label": "6"}, {"id": "c", "label": "8"}, {"id": "d", "label": "2"}], "answer": "d", "explanation": "Yes! The answer is \"2\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "How many do you see?  \ud83d\ude97\ud83d\ude97", "choices": [{"id": "a", "label": "6"}, {"id": "b", "label": "10"}, {"id": "c", "label": "3"}, {"id": "d", "label": "2"}], "answer": "d", "explanation": "Yes! The answer is \"2\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "How many do you see?  \ud83d\udc22\ud83d\udc22", "choices": [{"id": "a", "label": "2"}, {"id": "b", "label": "3"}, {"id": "c", "label": "6"}, {"id": "d", "label": "5"}], "answer": "a", "explanation": "Yes! The answer is \"2\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Counting to 10! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$counting-to-10$tl$ and t.grade_level = 0);

-- math: Number Recognition
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Number Recognition", "body": "Learn to spot and name the numbers 0 to 10 when you see them."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is the number 2?\n\nThe answer is \"2\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is the number 3?\n\nThe answer is \"3\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is the number 8?\n\nThe answer is \"8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is the number 6?", "choices": [{"id": "a", "label": "9"}, {"id": "b", "label": "10"}, {"id": "c", "label": "4"}, {"id": "d", "label": "6"}], "answer": "d", "explanation": "Yes! The answer is \"6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is the number 8?", "choices": [{"id": "a", "label": "1"}, {"id": "b", "label": "2"}, {"id": "c", "label": "8"}, {"id": "d", "label": "5"}], "answer": "c", "explanation": "Yes! The answer is \"8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is the number 2?", "choices": [{"id": "a", "label": "6"}, {"id": "b", "label": "9"}, {"id": "c", "label": "1"}, {"id": "d", "label": "2"}], "answer": "d", "explanation": "Yes! The answer is \"2\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Number Recognition! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$number-recognition$tl$ and t.grade_level = 0);

-- math: Shapes
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Shapes", "body": "Learn the names of basic shapes like circle, square, triangle, star, and heart."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is a square?\n\nThe answer is \"\ud83d\udfe6\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is a triangle?\n\nThe answer is \"\ud83d\udd3a\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is a star?\n\nThe answer is \"\u2b50\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a square?", "choices": [{"id": "a", "label": "\u2b55"}, {"id": "b", "label": "\ud83d\udd3a"}, {"id": "c", "label": "\ud83d\udfe6"}, {"id": "d", "label": "\u2764\ufe0f"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udfe6\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a heart?", "choices": [{"id": "a", "label": "\ud83d\udfe6"}, {"id": "b", "label": "\u2b50"}, {"id": "c", "label": "\ud83d\udd3a"}, {"id": "d", "label": "\u2764\ufe0f"}], "answer": "d", "explanation": "Yes! The answer is \"\u2764\ufe0f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a triangle?", "choices": [{"id": "a", "label": "\ud83d\udd3a"}, {"id": "b", "label": "\ud83d\udd36"}, {"id": "c", "label": "\ud83d\udfe6"}, {"id": "d", "label": "\u2764\ufe0f"}], "answer": "a", "explanation": "Yes! The answer is \"\ud83d\udd3a\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Shapes! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$shapes-basic$tl$ and t.grade_level = 0);

-- math: More & Fewer
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: More & Fewer", "body": "Compare groups of things to see which group has more and which has fewer."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which group has the MOST?\n\nThe answer is \"\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which group has the MOST?\n\nThe answer is \"\ud83c\udf6a\ud83c\udf6a\ud83c\udf6a\ud83c\udf6a\ud83c\udf6a\ud83c\udf6a\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which group has the MOST?\n\nThe answer is \"\ud83d\udc1f\ud83d\udc1f\ud83d\udc1f\ud83d\udc1f\ud83d\udc1f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which group has the MOST?", "choices": [{"id": "a", "label": "\u2b50\u2b50"}, {"id": "b", "label": "\u2b50"}, {"id": "c", "label": "\u2b50\u2b50\u2b50\u2b50\u2b50"}, {"id": "d", "label": "\u2b50\u2b50\u2b50"}], "answer": "c", "explanation": "Yes! The answer is \"\u2b50\u2b50\u2b50\u2b50\u2b50\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which group has the MOST?", "choices": [{"id": "a", "label": "\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c"}, {"id": "b", "label": "\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c"}, {"id": "c", "label": "\ud83c\udf4c"}, {"id": "d", "label": "\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c"}], "answer": "a", "explanation": "Yes! The answer is \"\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\ud83c\udf4c\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which group has the MOST?", "choices": [{"id": "a", "label": "\ud83d\ude97"}, {"id": "b", "label": "\ud83d\ude97\ud83d\ude97\ud83d\ude97"}, {"id": "c", "label": "\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97"}, {"id": "d", "label": "\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\ud83d\ude97\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about More & Fewer! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$more-and-fewer$tl$ and t.grade_level = 0);

-- math: Adding to 5
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Adding to 5", "body": "Put two small groups together and count them all to add up to 5."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Add them up:  \ud83d\udfe1\ud83d\udfe1\ud83d\udfe1 + \ud83d\udfe1 = ?\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Add them up:  \ud83d\udd35\ud83d\udd35 + \ud83d\udd35\ud83d\udd35 = ?\n\nThe answer is \"4\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Add them up:  \ud83d\udd34\ud83d\udd34 + \ud83d\udd34 = ?\n\nThe answer is \"3\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Add them up:  \ud83d\udfe2\ud83d\udfe2\ud83d\udfe2 + \ud83d\udfe2 = ?", "choices": [{"id": "a", "label": "2"}, {"id": "b", "label": "6"}, {"id": "c", "label": "5"}, {"id": "d", "label": "4"}], "answer": "d", "explanation": "Yes! The answer is \"4\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Add them up:  \ud83d\udfe1\ud83d\udfe1 + \ud83d\udfe1\ud83d\udfe1\ud83d\udfe1 = ?", "choices": [{"id": "a", "label": "8"}, {"id": "b", "label": "5"}, {"id": "c", "label": "9"}, {"id": "d", "label": "7"}], "answer": "b", "explanation": "Yes! The answer is \"5\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Add them up:  \ud83d\udfe2\ud83d\udfe2\ud83d\udfe2\ud83d\udfe2 + \ud83d\udfe2 = ?", "choices": [{"id": "a", "label": "6"}, {"id": "b", "label": "5"}, {"id": "c", "label": "3"}, {"id": "d", "label": "2"}], "answer": "b", "explanation": "Yes! The answer is \"5\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Adding to 5! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$adding-to-5$tl$ and t.grade_level = 0);

-- math: Patterns
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Patterns", "body": "A pattern repeats over and over. Find what comes next in the pattern."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What comes next?  \ud83d\udd34\ud83d\udd35\ud83d\udd34\ud83d\udd35 ___\n\nThe answer is \"\ud83d\udd34\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What comes next?  \u2b50\ud83c\udf19\u2b50\ud83c\udf19\u2b50\ud83c\udf19 ___\n\nThe answer is \"\u2b50\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What comes next?  \ud83d\udd34\ud83d\udd35\ud83d\udd34\ud83d\udd35 ___\n\nThe answer is \"\ud83d\udd34\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What comes next?  \u2b50\ud83c\udf19\u2b50\ud83c\udf19 ___", "choices": [{"id": "a", "label": "\ud83c\udf19"}, {"id": "b", "label": "\ud83d\udd34"}, {"id": "c", "label": "\u2b50"}, {"id": "d", "label": "\ud83d\udd3a"}], "answer": "c", "explanation": "Yes! The answer is \"\u2b50\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What comes next?  \ud83d\udd3a\ud83d\udfe6\ud83d\udd3a\ud83d\udfe6\ud83d\udd3a\ud83d\udfe6 ___", "choices": [{"id": "a", "label": "\ud83d\udfe6"}, {"id": "b", "label": "\ud83d\udd35"}, {"id": "c", "label": "\ud83d\udc31"}, {"id": "d", "label": "\ud83d\udd3a"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83d\udd3a\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What comes next?  \ud83d\udd3a\ud83d\udfe6\ud83d\udd3a\ud83d\udfe6\ud83d\udd3a\ud83d\udfe6 ___", "choices": [{"id": "a", "label": "\ud83d\udfe6"}, {"id": "b", "label": "\ud83c\udf19"}, {"id": "c", "label": "\ud83d\udd3a"}, {"id": "d", "label": "\ud83d\udc31"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udd3a\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Patterns! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$math$tl$ and t.slug = $tl$patterns$tl$ and t.grade_level = 0);

-- science: Living & Nonliving
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Living & Nonliving", "body": "Living things grow, eat, and need water. Nonliving things do not. Tell them apart!"}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is ALIVE (living)?\n\nThe answer is \"\ud83c\udf33\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is ALIVE (living)?\n\nThe answer is \"\ud83d\udc36\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is ALIVE (living)?\n\nThe answer is \"\ud83c\udf38\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is ALIVE (living)?", "choices": [{"id": "a", "label": "\u231a"}, {"id": "b", "label": "\u270f\ufe0f"}, {"id": "c", "label": "\ud83e\udd64"}, {"id": "d", "label": "\ud83d\udc1f"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83d\udc1f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is ALIVE (living)?", "choices": [{"id": "a", "label": "\ud83d\udcfa"}, {"id": "b", "label": "\ud83e\udde6"}, {"id": "c", "label": "\ud83c\udf7d\ufe0f"}, {"id": "d", "label": "\ud83d\udc26"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83d\udc26\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is ALIVE (living)?", "choices": [{"id": "a", "label": "\ud83d\udeb2"}, {"id": "b", "label": "\ud83d\udd28"}, {"id": "c", "label": "\ud83e\udd8b"}, {"id": "d", "label": "\ud83e\uddf4"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83e\udd8b\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Living & Nonliving! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$living-and-nonliving$tl$ and t.grade_level = 0);

-- science: The Five Senses
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: The Five Senses", "body": "We use our eyes, ears, nose, tongue, and hands to see, hear, smell, taste, and touch."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which part do you SEE with?\n\nThe answer is \"\ud83d\udc41\ufe0f\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which part do you HEAR with?\n\nThe answer is \"\ud83d\udc42\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which part do you SMELL with?\n\nThe answer is \"\ud83d\udc43\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which part do you TASTE with?", "choices": [{"id": "a", "label": "\ud83d\udc43"}, {"id": "b", "label": "\ud83d\udc45"}, {"id": "c", "label": "\ud83d\udc42"}, {"id": "d", "label": "\ud83d\udc41\ufe0f"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udc45\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which part do you TOUCH and feel with?", "choices": [{"id": "a", "label": "\ud83d\udc41\ufe0f"}, {"id": "b", "label": "\ud83d\udc42"}, {"id": "c", "label": "\ud83d\udc43"}, {"id": "d", "label": "\u270b"}], "answer": "d", "explanation": "Yes! The answer is \"\u270b\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "You use your eyes to:", "choices": [{"id": "a", "label": "hear"}, {"id": "b", "label": "smell"}, {"id": "c", "label": "see"}, {"id": "d", "label": "taste"}], "answer": "c", "explanation": "Yes! The answer is \"see\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about The Five Senses! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$five-senses$tl$ and t.grade_level = 0);

-- science: Weather
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Weather", "body": "Weather can be sunny, rainy, snowy, cloudy, or stormy. Learn what each one looks like."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one shows RAIN?\n\nThe answer is \"\ud83c\udf27\ufe0f\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one shows SUN?\n\nThe answer is \"\u2600\ufe0f\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one shows SNOW?\n\nThe answer is \"\u2744\ufe0f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one shows a RAINBOW?", "choices": [{"id": "a", "label": "\ud83c\udf08"}, {"id": "b", "label": "\u2601\ufe0f"}, {"id": "c", "label": "\u2744\ufe0f"}, {"id": "d", "label": "\u2600\ufe0f"}], "answer": "a", "explanation": "Yes! The answer is \"\ud83c\udf08\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one shows CLOUDS?", "choices": [{"id": "a", "label": "\u2600\ufe0f"}, {"id": "b", "label": "\ud83c\udf08"}, {"id": "c", "label": "\u2601\ufe0f"}, {"id": "d", "label": "\u2744\ufe0f"}], "answer": "c", "explanation": "Yes! The answer is \"\u2601\ufe0f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one shows a STORM?", "choices": [{"id": "a", "label": "\u2600\ufe0f"}, {"id": "b", "label": "\u26c8\ufe0f"}, {"id": "c", "label": "\ud83c\udf08"}, {"id": "d", "label": "\u2744\ufe0f"}], "answer": "b", "explanation": "Yes! The answer is \"\u26c8\ufe0f\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Weather! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$weather-basics$tl$ and t.grade_level = 0);

-- science: Animals & Sounds
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Animals & Sounds", "body": "Different animals make different sounds and live in different places."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which animal says 'moo'?\n\nThe answer is \"\ud83d\udc04\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which animal says 'woof'?\n\nThe answer is \"\ud83d\udc36\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which animal says 'meow'?\n\nThe answer is \"\ud83d\udc31\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which animal says 'quack'?", "choices": [{"id": "a", "label": "\ud83d\udc36"}, {"id": "b", "label": "\ud83e\udd86"}, {"id": "c", "label": "\ud83d\udc31"}, {"id": "d", "label": "\ud83d\udc04"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83e\udd86\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which animal says 'baa'?", "choices": [{"id": "a", "label": "\ud83d\udc37"}, {"id": "b", "label": "\ud83d\udc11"}, {"id": "c", "label": "\ud83d\udc14"}, {"id": "d", "label": "\ud83d\udc36"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udc11\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which animal says 'oink'?", "choices": [{"id": "a", "label": "\ud83d\udc11"}, {"id": "b", "label": "\ud83d\udc37"}, {"id": "c", "label": "\ud83d\udc04"}, {"id": "d", "label": "\ud83d\udc31"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udc37\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Animals & Sounds! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$animals-and-sounds$tl$ and t.grade_level = 0);

-- science: What Plants Need
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: What Plants Need", "body": "Plants need water, sunlight, air, and soil to grow big and strong."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What do plants need to grow?\n\nThe answer is \"water and sunlight\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which helps a plant grow?\n\nThe answer is \"sunlight\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Plants drink:\n\nThe answer is \"water\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Where do most plants grow?", "choices": [{"id": "a", "label": "in the soil (dirt)"}, {"id": "b", "label": "in the closet"}, {"id": "c", "label": "in a box of toys"}, {"id": "d", "label": "in the fridge"}], "answer": "a", "explanation": "Yes! The answer is \"in the soil (dirt)\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What part of a plant grows under the ground?", "choices": [{"id": "a", "label": "flowers"}, {"id": "b", "label": "leaves"}, {"id": "c", "label": "fruit"}, {"id": "d", "label": "roots"}], "answer": "d", "explanation": "Yes! The answer is \"roots\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "A plant in a dark room with no light will:", "choices": [{"id": "a", "label": "grow super fast"}, {"id": "b", "label": "turn into an animal"}, {"id": "c", "label": "not grow well"}, {"id": "d", "label": "fly away"}], "answer": "c", "explanation": "Yes! The answer is \"not grow well\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about What Plants Need! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$what-plants-need$tl$ and t.grade_level = 0);

-- science: Day & Night
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Day & Night", "body": "In the day we see the Sun. At night we see the Moon and stars."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which do you see at NIGHT?\n\nThe answer is \"\ud83c\udf19\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which do you see in the DAY sky?\n\nThe answer is \"\u2600\ufe0f\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which comes out at night?\n\nThe answer is \"\u2b50\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When is it dark outside?", "choices": [{"id": "a", "label": "at night"}, {"id": "b", "label": "at noon"}, {"id": "c", "label": "in the morning"}, {"id": "d", "label": "at lunchtime"}], "answer": "a", "explanation": "Yes! The answer is \"at night\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "When is it bright outside?", "choices": [{"id": "a", "label": "in the day"}, {"id": "b", "label": "at midnight"}, {"id": "c", "label": "at night"}, {"id": "d", "label": "in dreams"}], "answer": "a", "explanation": "Yes! The answer is \"in the day\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which animal is awake at night?", "choices": [{"id": "a", "label": "\ud83d\udc14"}, {"id": "b", "label": "\ud83d\udc1d"}, {"id": "c", "label": "\ud83e\udd8b"}, {"id": "d", "label": "\ud83e\udd89"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83e\udd89\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Day & Night! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$science$tl$ and t.slug = $tl$day-and-night$tl$ and t.grade_level = 0);

-- reading: Colors
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Colors", "body": "Learn to name colors like red, blue, green, yellow, and more."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is RED?\n\nThe answer is \"\ud83d\udfe5\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is BLUE?\n\nThe answer is \"\ud83d\udfe6\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is GREEN?\n\nThe answer is \"\ud83d\udfe9\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is YELLOW?", "choices": [{"id": "a", "label": "\ud83d\udfe7"}, {"id": "b", "label": "\ud83d\udfe9"}, {"id": "c", "label": "\ud83d\udfe6"}, {"id": "d", "label": "\ud83d\udfe8"}], "answer": "d", "explanation": "Yes! The answer is \"\ud83d\udfe8\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is ORANGE?", "choices": [{"id": "a", "label": "\ud83d\udfe8"}, {"id": "b", "label": "\ud83d\udfe5"}, {"id": "c", "label": "\ud83d\udfe7"}, {"id": "d", "label": "\ud83d\udfea"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udfe7\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is PURPLE?", "choices": [{"id": "a", "label": "\ud83d\udfe6"}, {"id": "b", "label": "\ud83d\udfe5"}, {"id": "c", "label": "\ud83d\udfea"}, {"id": "d", "label": "\ud83d\udfe9"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udfea\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Colors! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$colors$tl$ and t.grade_level = 0);

-- reading: Rhyming Words
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Rhyming Words", "body": "Rhyming words sound the same at the end, like cat and hat."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word rhymes with CAT?\n\nThe answer is \"hat\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word rhymes with DOG?\n\nThe answer is \"log\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word rhymes with SUN?\n\nThe answer is \"bun\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with BEE?", "choices": [{"id": "a", "label": "book"}, {"id": "b", "label": "ball"}, {"id": "c", "label": "cup"}, {"id": "d", "label": "tree"}], "answer": "d", "explanation": "Yes! The answer is \"tree\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with CAR?", "choices": [{"id": "a", "label": "star"}, {"id": "b", "label": "sun"}, {"id": "c", "label": "dog"}, {"id": "d", "label": "hat"}], "answer": "a", "explanation": "Yes! The answer is \"star\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word rhymes with CAKE?", "choices": [{"id": "a", "label": "lake"}, {"id": "b", "label": "milk"}, {"id": "c", "label": "ball"}, {"id": "d", "label": "top"}], "answer": "a", "explanation": "Yes! The answer is \"lake\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Rhyming Words! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$rhyming-words$tl$ and t.grade_level = 0);

-- reading: Same & Different
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Same & Different", "body": "Look closely to find the picture that is different from the others."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is DIFFERENT?\n\nThe answer is \"\ud83d\udc31\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is DIFFERENT?\n\nThe answer is \"\u2b50\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is DIFFERENT?\n\nThe answer is \"\ud83d\udd35\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is DIFFERENT?", "choices": [{"id": "a", "label": "\ud83c\udf38"}, {"id": "b", "label": "\ud83d\udc1f"}, {"id": "c", "label": "\ud83c\udf38"}, {"id": "d", "label": "\ud83c\udf38"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udc1f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is DIFFERENT?", "choices": [{"id": "a", "label": "\ud83d\ude97"}, {"id": "b", "label": "\ud83d\udc36"}, {"id": "c", "label": "\ud83d\udc36"}, {"id": "d", "label": "\ud83d\udc36"}], "answer": "a", "explanation": "Yes! The answer is \"\ud83d\ude97\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is DIFFERENT?", "choices": [{"id": "a", "label": "\u2b50"}, {"id": "b", "label": "\ud83c\udf4c"}, {"id": "c", "label": "\u2b50"}, {"id": "d", "label": "\u2b50"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83c\udf4c\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Same & Different! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$same-and-different$tl$ and t.grade_level = 0);

-- reading: Beginning Sounds
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Beginning Sounds", "body": "Listen for the first sound in a word, like the B sound at the start of 'bee'."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which picture starts with the B sound?\n\nThe answer is \"\ud83d\udc1d\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which picture starts with the S sound?\n\nThe answer is \"\u2600\ufe0f\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which picture starts with the C sound?\n\nThe answer is \"\ud83d\udc31\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which picture starts with the D sound?", "choices": [{"id": "a", "label": "\ud83d\udc31"}, {"id": "b", "label": "\ud83c\udf4e"}, {"id": "c", "label": "\ud83d\udc36"}, {"id": "d", "label": "\ud83d\udc1d"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83d\udc36\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which picture starts with the F sound?", "choices": [{"id": "a", "label": "\ud83d\udc31"}, {"id": "b", "label": "\ud83d\udc1f"}, {"id": "c", "label": "\ud83c\udf47"}, {"id": "d", "label": "\ud83c\udfa9"}], "answer": "b", "explanation": "Yes! The answer is \"\ud83d\udc1f\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which picture starts with the A sound?", "choices": [{"id": "a", "label": "\ud83d\udc36"}, {"id": "b", "label": "\ud83d\udc1d"}, {"id": "c", "label": "\ud83c\udf4e"}, {"id": "d", "label": "\u2600\ufe0f"}], "answer": "c", "explanation": "Yes! The answer is \"\ud83c\udf4e\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Beginning Sounds! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$beginning-sounds$tl$ and t.grade_level = 0);

-- reading: Sight Words
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Sight Words", "body": "Sight words are little words we see a lot, like the, and, you, and see."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which word is 'the'?\n\nThe answer is \"the\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which word is 'and'?\n\nThe answer is \"and\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which word is 'you'?\n\nThe answer is \"you\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'see'?", "choices": [{"id": "a", "label": "the"}, {"id": "b", "label": "see"}, {"id": "c", "label": "my"}, {"id": "d", "label": "go"}], "answer": "b", "explanation": "Yes! The answer is \"see\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'go'?", "choices": [{"id": "a", "label": "go"}, {"id": "b", "label": "is"}, {"id": "c", "label": "you"}, {"id": "d", "label": "and"}], "answer": "a", "explanation": "Yes! The answer is \"go\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which word is 'my'?", "choices": [{"id": "a", "label": "to"}, {"id": "b", "label": "the"}, {"id": "c", "label": "see"}, {"id": "d", "label": "my"}], "answer": "d", "explanation": "Yes! The answer is \"my\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Sight Words! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$sight-words$tl$ and t.grade_level = 0);

-- reading: Opposites
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Opposites", "body": "Opposites are words that mean very different things, like big and small."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  What is the opposite of BIG?\n\nThe answer is \"small\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  What is the opposite of HOT?\n\nThe answer is \"cold\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  What is the opposite of UP?\n\nThe answer is \"down\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of DAY?", "choices": [{"id": "a", "label": "night"}, {"id": "b", "label": "noon"}, {"id": "c", "label": "sun"}, {"id": "d", "label": "sky"}], "answer": "a", "explanation": "Yes! The answer is \"night\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of HAPPY?", "choices": [{"id": "a", "label": "glad"}, {"id": "b", "label": "silly"}, {"id": "c", "label": "kind"}, {"id": "d", "label": "sad"}], "answer": "d", "explanation": "Yes! The answer is \"sad\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "What is the opposite of FAST?", "choices": [{"id": "a", "label": "quick"}, {"id": "b", "label": "tall"}, {"id": "c", "label": "slow"}, {"id": "d", "label": "big"}], "answer": "c", "explanation": "Yes! The answer is \"slow\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Opposites! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$reading$tl$ and t.slug = $tl$opposites$tl$ and t.grade_level = 0);

-- letters: Uppercase Letters
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Uppercase Letters", "body": "Uppercase (big) letters are the tall capital letters like A, B, and C."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Tap the big (uppercase) letter Q.\n\nThe answer is \"Q\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Tap the big (uppercase) letter J.\n\nThe answer is \"J\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Tap the big (uppercase) letter U.\n\nThe answer is \"U\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the big (uppercase) letter S.", "choices": [{"id": "a", "label": "E"}, {"id": "b", "label": "S"}, {"id": "c", "label": "T"}, {"id": "d", "label": "Y"}], "answer": "b", "explanation": "Yes! The answer is \"S\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the big (uppercase) letter H.", "choices": [{"id": "a", "label": "N"}, {"id": "b", "label": "Z"}, {"id": "c", "label": "H"}, {"id": "d", "label": "E"}], "answer": "c", "explanation": "Yes! The answer is \"H\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the big (uppercase) letter P.", "choices": [{"id": "a", "label": "S"}, {"id": "b", "label": "Z"}, {"id": "c", "label": "P"}, {"id": "d", "label": "R"}], "answer": "c", "explanation": "Yes! The answer is \"P\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Uppercase Letters! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$uppercase-letters$tl$ and t.grade_level = 0);

-- letters: Lowercase Letters
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Lowercase Letters", "body": "Lowercase (small) letters are the little letters like a, b, and c."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Tap the small (lowercase) letter d.\n\nThe answer is \"d\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Tap the small (lowercase) letter o.\n\nThe answer is \"o\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Tap the small (lowercase) letter h.\n\nThe answer is \"h\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the small (lowercase) letter g.", "choices": [{"id": "a", "label": "g"}, {"id": "b", "label": "c"}, {"id": "c", "label": "m"}, {"id": "d", "label": "w"}], "answer": "a", "explanation": "Yes! The answer is \"g\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the small (lowercase) letter m.", "choices": [{"id": "a", "label": "g"}, {"id": "b", "label": "p"}, {"id": "c", "label": "r"}, {"id": "d", "label": "m"}], "answer": "d", "explanation": "Yes! The answer is \"m\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Tap the small (lowercase) letter j.", "choices": [{"id": "a", "label": "j"}, {"id": "b", "label": "o"}, {"id": "c", "label": "y"}, {"id": "d", "label": "m"}], "answer": "a", "explanation": "Yes! The answer is \"j\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Lowercase Letters! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$lowercase-letters$tl$ and t.grade_level = 0);

-- letters: Match Big & Small
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Match Big & Small", "body": "Every big letter has a matching small letter, like A and a."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which small letter matches D?\n\nThe answer is \"d\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which small letter matches R?\n\nThe answer is \"r\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which small letter matches I?\n\nThe answer is \"i\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which small letter matches D?", "choices": [{"id": "a", "label": "p"}, {"id": "b", "label": "d"}, {"id": "c", "label": "i"}, {"id": "d", "label": "w"}], "answer": "b", "explanation": "Yes! The answer is \"d\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which small letter matches U?", "choices": [{"id": "a", "label": "k"}, {"id": "b", "label": "a"}, {"id": "c", "label": "j"}, {"id": "d", "label": "u"}], "answer": "d", "explanation": "Yes! The answer is \"u\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which small letter matches U?", "choices": [{"id": "a", "label": "h"}, {"id": "b", "label": "f"}, {"id": "c", "label": "u"}, {"id": "d", "label": "v"}], "answer": "c", "explanation": "Yes! The answer is \"u\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Match Big & Small! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$match-upper-and-lower$tl$ and t.grade_level = 0);

-- letters: Alphabet Order
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Alphabet Order", "body": "The letters of the alphabet go in order: A, B, C, D, and on to Z."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which letter comes right after G?\n\nThe answer is \"H\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which letter comes right after O?\n\nThe answer is \"P\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which letter comes right after G?\n\nThe answer is \"H\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter comes right after K?", "choices": [{"id": "a", "label": "V"}, {"id": "b", "label": "L"}, {"id": "c", "label": "G"}, {"id": "d", "label": "Z"}], "answer": "b", "explanation": "Yes! The answer is \"L\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter comes right after L?", "choices": [{"id": "a", "label": "M"}, {"id": "b", "label": "D"}, {"id": "c", "label": "C"}, {"id": "d", "label": "R"}], "answer": "a", "explanation": "Yes! The answer is \"M\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter comes right after U?", "choices": [{"id": "a", "label": "I"}, {"id": "b", "label": "C"}, {"id": "c", "label": "G"}, {"id": "d", "label": "V"}], "answer": "d", "explanation": "Yes! The answer is \"V\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Alphabet Order! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$alphabet-order$tl$ and t.grade_level = 0);

-- letters: Vowels
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: Vowels", "body": "The vowels are A, E, I, O, and U. Every word needs a vowel."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which one is a vowel?\n\nThe answer is \"I\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which one is a vowel?\n\nThe answer is \"I\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which one is a vowel?\n\nThe answer is \"E\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a vowel?", "choices": [{"id": "a", "label": "D"}, {"id": "b", "label": "O"}, {"id": "c", "label": "B"}, {"id": "d", "label": "N"}], "answer": "b", "explanation": "Yes! The answer is \"O\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a vowel?", "choices": [{"id": "a", "label": "R"}, {"id": "b", "label": "U"}, {"id": "c", "label": "S"}, {"id": "d", "label": "W"}], "answer": "b", "explanation": "Yes! The answer is \"U\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which one is a vowel?", "choices": [{"id": "a", "label": "V"}, {"id": "b", "label": "H"}, {"id": "c", "label": "D"}, {"id": "d", "label": "I"}], "answer": "d", "explanation": "Yes! The answer is \"I\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about Vowels! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$vowels$tl$ and t.grade_level = 0);

-- letters: First Letters
update public.lessons set steps = $tl$[{"type": "explain", "title": "Let's learn: First Letters", "body": "Match a picture to the letter its name begins with."}, {"type": "worked_example", "title": "Worked example 1", "body": "Example 1.  Which letter does this word start with?  \ud83c\udf4e (apple)\n\nThe answer is \"A\"."}, {"type": "worked_example", "title": "Worked example 2", "body": "Example 2.  Which letter does this word start with?  \ud83d\udc1d (bee)\n\nThe answer is \"B\"."}, {"type": "worked_example", "title": "Worked example 3", "body": "Example 3.  Which letter does this word start with?  \ud83d\udc31 (cat)\n\nThe answer is \"C\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter does this word start with?  \ud83d\udc36 (dog)", "choices": [{"id": "a", "label": "B"}, {"id": "b", "label": "D"}, {"id": "c", "label": "C"}, {"id": "d", "label": "P"}], "answer": "b", "explanation": "Yes! The answer is \"D\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter does this word start with?  \ud83e\udd5a (egg)", "choices": [{"id": "a", "label": "A"}, {"id": "b", "label": "I"}, {"id": "c", "label": "O"}, {"id": "d", "label": "E"}], "answer": "d", "explanation": "Yes! The answer is \"E\"."}, {"type": "check", "title": "Your turn", "body": "Pick the best answer.", "prompt": "Which letter does this word start with?  \ud83d\udc1f (fish)", "choices": [{"id": "a", "label": "F"}, {"id": "b", "label": "S"}, {"id": "c", "label": "V"}, {"id": "d", "label": "T"}], "answer": "a", "explanation": "Yes! The answer is \"F\"."}, {"type": "explain", "title": "You've got this!", "body": "Great work learning about First Letters! Now tap a worksheet to practice and earn points. You can always come back to this lesson."}]$tl$::jsonb
where topic_id in (select t.id from public.topics t join public.subjects s on s.id = t.subject_id
  where s.slug = $tl$letters$tl$ and t.slug = $tl$beginning-letter$tl$ and t.grade_level = 0);

